# -*- coding: utf-8 -*-
# Sorular 64-80

SECTIONS = []
Q = []

SECTIONS.append(dict(
    rng=(64, 69),
    title="ARAPÇADAN TÜRKÇEYE ÇEVİRİ",
    instr="64.-69. sorularda, verilen Arapça cümleye anlamca en yakın Türkçe cümleyi bulunuz.",
    skill="Bu bölüm; Arapça cümlenin zamanını, özne-yüklem ilişkisini, edat ve bağlaçların işlevini, olumsuzluk ve derecelendirme ifadelerini Türkçeye anlam kaybı olmadan aktarabilme becerisini ölçer.",
    strategy="Önce Arapça cümlenin iskeletini (fiil, fâil, mef‘ûl ve temel bağlaç) çıkarın; ardından şıklarda bu iskeletin korunup korunmadığına bakın. Özellikle sebep-sonucun ters çevrildiği, “bazı / birçok / tüm” gibi niceleyicilerin değiştirildiği ve “-abilir / kesinlikle” gibi derece farklarının eklendiği şıkları eleyin; birebir kelime çevirisi değil anlam eşdeğerliği aranır.",
))

Q += [
dict(n=64,
 stem="يرى كثير من علماء الاجتماع أن التحولات السريعة التي تشهدها بنية الأسرة الحديثة تعود في جزء كبير منها إلى العوامل الاقتصادية.",
 opts=["Birçok sosyolog, modern aile yapısında yaşanan hızlı dönüşümlerin ekonomik etkenleri büyük ölçüde etkilediği görüşündedir.",
       "Birçok sosyolog, modern aile yapısının tanık olduğu hızlı dönüşümlerin büyük ölçüde ekonomik etkenlerden kaynaklandığını düşünmektedir.",
       "Birçok sosyoloğa göre modern aile yapısının tanık olduğu hızlı dönüşümler yalnızca ekonomik etkenlerden kaynaklanmaktadır.",
       "Sosyologların çoğu, modern aile yapısındaki dönüşümlerin hızını büyük ölçüde ekonomik etkenlerin belirlediğini ileri sürmektedir.",
       "Birçok sosyolog, modern aile yapısının geçirdiği hızlı dönüşümlerin kısmen de olsa ekonomik etkenlere bağlı olabileceğini düşünmektedir."], ans="B",
 harakat="يَرَى كَثِيرٌ مِنْ عُلَمَاءِ الِاجْتِمَاعِ أَنَّ التَّحَوُّلَاتِ السَّرِيعَةَ الَّتِي تَشْهَدُهَا بِنْيَةُ الْأُسْرَةِ الْحَدِيثَةِ تَعُودُ فِي جُزْءٍ كَبِيرٍ مِنْهَا إِلَى الْعَوَامِلِ الِاقْتِصَادِيَّةِ.",
 keys=[("يَرَى كَثِيرٌ مِنْ", "birçok ... düşünmektedir / görüşündedir"),
       ("التَّحَوُّلَاتُ السَّرِيعَةُ الَّتِي تَشْهَدُهَا", "tanık olduğu / yaşadığı hızlı dönüşümler"),
       ("تَعُودُ ... إِلَى", "...den kaynaklanır, ...e dayanır"),
       ("فِي جُزْءٍ كَبِيرٍ مِنْهَا", "büyük ölçüde")],
 a2=["Cümlede sebep ekonomik etkenler, sonuç ise aile yapısındaki hızlı dönüşümlerdir: تَعُودُ إِلَى “...e dayanır, ...den kaynaklanır”. فِي جُزْءٍ كَبِيرٍ مِنْهَا “büyük ölçüde” anlamında bir derecelendirmedir; “tamamen” de “kısmen” de değildir. Özne كَثِيرٌ مِنْ “birçok”tur; “çoğu” değildir.",
     "A: Bütün kelimeleri korur, ama sebep-sonucu ters çevirir (dönüşümler ekonomik etkenleri etkiliyor gibi). C: “yalnızca” ifadesi, “büyük ölçüde” derecelendirmesini mutlak hâle getirir. D: Özneyi “sosyologların çoğu”na çevirir ve ekonomik etkenlerin dönüşümün kendisini değil “hızını” belirlediğini söyler. E: “büyük ölçüde”yi “kısmen de olsa ... olabilir” diyerek zayıflatır.",
     "B şıkkında تَشْهَدُهَا “tanık olduğu”, تَعُودُ إِلَى “kaynaklandığı”, فِي جُزْءٍ كَبِيرٍ “büyük ölçüde” olarak eksiksiz karşılanmıştır.",
     "Doğru cevabımız B."]),

dict(n=65,
 stem="لم يكن للاكتشافات الجغرافية الكبرى أن تتحقق لولا التطور الذي شهدته صناعة السفن وأدوات الملاحة.",
 opts=["Büyük coğrafi keşifler, gemi yapımı ve seyir araçlarında yaşanan gelişmelerin başlıca nedeni olmuştur.",
       "Gemi yapımı ve seyir araçlarındaki gelişme olmasaydı büyük coğrafi keşifler bu kadar hızlı gerçekleşmezdi.",
       "Gemi yapımı ve seyir araçlarında yaşanan gelişmelere rağmen büyük coğrafi keşifler kolayca gerçekleşememiştir.",
       "Büyük coğrafi keşiflerin gerçekleşmesinde gemi yapımı ve seyir araçlarındaki gelişmenin de payı olmuştur.",
       "Gemi yapımı ve seyir araçlarında yaşanan gelişme olmasaydı büyük coğrafi keşifler gerçekleşemezdi."], ans="E",
 harakat="لَمْ يَكُنْ لِلِاكْتِشَافَاتِ الْجُغْرَافِيَّةِ الْكُبْرَى أَنْ تَتَحَقَّقَ لَوْلَا التَّطَوُّرُ الَّذِي شَهِدَتْهُ صِنَاعَةُ السُّفُنِ وَأَدَوَاتِ الْمِلَاحَةِ.",
 keys=[("لَمْ يَكُنْ لِـ ... أَنْ ...", "...mesi mümkün değildi / ...mezdi"),
       ("لَوْلَا", "...olmasaydı"),
       ("التَّطَوُّرُ الَّذِي شَهِدَتْهُ صِنَاعَةُ السُّفُنِ", "gemi yapımının yaşadığı gelişme")],
 a2=["لَمْ يَكُنْ لِـ X أَنْ يَفْعَلَ yapısı “X'in ... yapması mümkün değildi / X ... yapamazdı” anlamını verir. لَوْلَا ise “... olmasaydı” demektir ve bir şeyin varlığı sayesinde diğerinin gerçekleştiğini bildirir. Birleşik anlam: “Gemi yapımındaki gelişme olmasaydı büyük keşifler gerçekleşemezdi.” Yani gelişme, keşiflerin zorunlu şartıdır. لَوْلَا'dan sonraki التَّطَوُّرُ mübtedâdır, haberi hazfedilmiştir.",
     "E şıkkı bu yapıyı birebir karşılar. A: Sebep-sonucu ters çevirir. B: Yapıyı korur, ama “bu kadar hızlı” ifadesini ekleyerek zorunlu şartı yalnızca hızla ilgili bir etkene dönüştürür; en güçlü çeldirici budur. C: Keşiflerin gerçekleşmediğini söyler; oysa لَوْلَا yapısı keşiflerin gerçekleştiğini ima eder. D: “payı olmuştur” diyerek zorunlu şartı birçok etkenden biri hâline getirir.",
     "Doğru cevabımız E."]),

dict(n=66,
 stem="تتطلب مواجهة الأوبئة العابرة للحدود تنسيقا دوليا وثيقا يتجاوز الاعتبارات السياسية الضيقة.",
 opts=["Sınır ötesi salgınlarla mücadele, dar siyasi kaygıları aşan sıkı bir uluslararası koordinasyonu gerektirmektedir.",
       "Sınır ötesi salgınlarla mücadelede sıkı bir uluslararası koordinasyon, dar siyasi kaygılar yüzünden sağlanamamaktadır.",
       "Sınır ötesi salgınlarla mücadele, siyasi kaygıları da gözeten sıkı bir uluslararası koordinasyonu gerektirmektedir.",
       "Sınır ötesi salgınların önlenmesi, her ülkenin dar siyasi kaygılarını aşarak kendi tedbirlerini almasını gerektirmektedir.",
       "Salgınların sınırları aşarak yayılması, uluslararası koordinasyonun dar siyasi kaygılarla sınırlı kalmasından kaynaklanmaktadır."], ans="A",
 harakat="تَتَطَلَّبُ مُوَاجَهَةُ الْأَوْبِئَةِ الْعَابِرَةِ لِلْحُدُودِ تَنْسِيقًا دَوْلِيًّا وَثِيقًا يَتَجَاوَزُ الِاعْتِبَارَاتِ السِّيَاسِيَّةَ الضَّيِّقَةَ.",
 keys=[("تَتَطَلَّبُ", "gerektirir"),
       ("مُوَاجَهَةُ الْأَوْبِئَةِ الْعَابِرَةِ لِلْحُدُودِ", "sınır ötesi salgınlarla mücadele"),
       ("تَنْسِيقًا دَوْلِيًّا وَثِيقًا", "sıkı bir uluslararası koordinasyon"),
       ("يَتَجَاوَزُ الِاعْتِبَارَاتِ السِّيَاسِيَّةَ الضَّيِّقَةَ", "dar siyasi kaygıları aşan")],
 a2=["Cümlenin fiili تَتَطَلَّبُ (gerektirir), fâili مُوَاجَهَةُ (mücadele), mef‘ûlü تَنْسِيقًا (koordinasyon)'dır. يَتَجَاوَزُ ... cümlesi nekre olan تَنْسِيقًا kelimesinin sıfatıdır (cümle hâlinde sıfat): “... aşan bir koordinasyon”.",
     "A şıkkı bütün unsurları doğru sırayla ve doğru ilişkilerle verir. B: Bir gereklilik yerine “sağlanamamaktadır” diyerek bir tespit yapar. C: Yapıyı korur, ama يَتَجَاوَزُ (aşan) fiilini “gözeten” diye çevirerek anlamı tersine çevirir; en güçlü çeldirici budur. D: “Uluslararası koordinasyon” yerine her ülkenin kendi tedbirlerini koyar. E: Cümlede olmayan bir sebep-sonuç ilişkisi kurar.",
     "Doğru cevabımız A."]),

dict(n=67,
 stem="كلما ازداد اعتماد الطلاب على محركات البحث في الحصول على المعلومات، تراجعت قدرتهم على الاحتفاظ بها في الذاكرة لفترات طويلة.",
 opts=["Öğrencilerin bilgiye ulaşmada arama motorlarına bağımlılığı arttıkça, bu bilgileri kısa sürede unutma eğilimleri azalmaktadır.",
       "Öğrencilerin bilgileri uzun süre hafızalarında tutma yetenekleri azaldıkça, arama motorlarına olan bağımlılıkları artmaktadır.",
       "Öğrencilerin bilgiye ulaşmada arama motorlarına bağımlılığı arttıkça, bu bilgileri uzun süre hafızalarında tutma yetenekleri azalmaktadır.",
       "Arama motorlarına bağımlı olan öğrencilerin bilgileri uzun süre hafızalarında tutma yetenekleri, diğer öğrencilere göre daha zayıftır.",
       "Öğrenciler arama motorlarına daha az bağımlı olsalardı, bilgileri hafızalarında çok daha uzun süre tutabilirlerdi."], ans="C",
 harakat="كُلَّمَا ازْدَادَ اعْتِمَادُ الطُّلَّابِ عَلَى مُحَرِّكَاتِ الْبَحْثِ فِي الْحُصُولِ عَلَى الْمَعْلُومَاتِ، تَرَاجَعَتْ قُدْرَتُهُمْ عَلَى الِاحْتِفَاظِ بِهَا فِي الذَّاكِرَةِ لِفَتَرَاتٍ طَوِيلَةٍ.",
 keys=[("كُلَّمَا ازْدَادَ ... تَرَاجَعَتْ", "... arttıkça ... azalır"),
       ("اعْتِمَادُ ... عَلَى", "...e dayanma, bağımlılık"),
       ("الِاحْتِفَاظُ بِهَا فِي الذَّاكِرَةِ", "onları hafızada tutma")],
 a2=["كُلَّمَا yapısı iki durum arasında orantı kurar; burada ters orantı söz konusudur: biri arttıkça diğeri azalır. Artan “arama motorlarına bağımlılık”, azalan ise “bilgileri uzun süre hafızada tutma yeteneği”dir. Mazi fiiller (ازْدَادَ، تَرَاجَعَتْ) genel bir hüküm bildirdiği için Türkçede geniş / şimdiki zamanla çevrilir.",
     "C şıkkı orantıyı ve yönü doğru verir. A: Orantı yapısını korur, ama “unutma eğilimi azalır” demek “hafızada tutma yeteneği artar” demektir; yön ters çevrilmiştir. B: Sebep ile sonucun yerini değiştirir. D: “arttıkça ... azalır” orantısı yerine iki öğrenci grubu arasında bir karşılaştırma yapar. E: Varsayım (şart) cümlesidir; cümledeki orantıyı ve süreklilik anlamını vermez.",
     "Doğru cevabımız C."]),

dict(n=68,
 stem="لا تكمن قيمة المخطوطات القديمة في ندرتها فحسب، بل في ما تحمله من معارف تكشف جوانب مجهولة من تاريخ الحضارات.",
 opts=["Eski el yazmalarının değeri, medeniyet tarihinin bilinmeyen yönlerini açığa çıkaran bilgilerden çok nadir bulunmalarından kaynaklanmaktadır.",
       "Eski el yazmalarının değeri nadir olmalarında değil, yalnızca medeniyet tarihinin bilinmeyen yönlerini açığa çıkaran bilgileri içermelerindedir.",
       "Medeniyet tarihinin bilinmeyen yönleri, nadir bulunan eski el yazmalarındaki bilgiler sayesinde tamamen açığa çıkarılmıştır.",
       "Eski el yazmalarının değeri yalnızca nadir olmalarında değil, medeniyet tarihinin bilinmeyen yönlerini açığa çıkaran bilgileri içermelerinde de yatmaktadır.",
       "Eski el yazmaları, hem nadir olmaları hem de içerdikleri bilgiler nedeniyle medeniyet tarihinin en değerli kaynakları arasındadır."], ans="D",
 harakat="لَا تَكْمُنُ قِيمَةُ الْمَخْطُوطَاتِ الْقَدِيمَةِ فِي نُدْرَتِهَا فَحَسْبُ، بَلْ فِي مَا تَحْمِلُهُ مِنْ مَعَارِفَ تَكْشِفُ جَوَانِبَ مَجْهُولَةً مِنْ تَارِيخِ الْحَضَارَاتِ.",
 keys=[("لَا تَكْمُنُ ... فَحَسْبُ، بَلْ ...", "yalnızca ...de değil, ...de de yatmaktadır"),
       ("مَا تَحْمِلُهُ مِنْ مَعَارِفَ", "taşıdıkları / barındırdıkları bilgiler"),
       ("تَكْشِفُ جَوَانِبَ مَجْهُولَةً", "bilinmeyen yönleri açığa çıkaran")],
 a2=["لَا ... فَحَسْبُ، بَلْ ... yapısı “yalnızca ... değil, aynı zamanda ...” anlamında ekleme bildirir. İki unsur da (nadirlik ve bilgi içeriği) değerin kaynağıdır; ikincisi vurgulanır. مَا تَحْمِلُهُ مِنْ مَعَارِفَ ifadesinde مِنْ beyan içindir: “taşıdığı bilgiler”. تَكْشِفُ ... cümlesi nekre olan مَعَارِفَ kelimesinin sıfatıdır.",
     "D şıkkı ekleme yapısını ve bütün unsurları korur. A: Ağırlığı nadirliğe verir; cümledeki vurguyu ters çevirir. B: “yalnızca”nın yerini değiştirir: “nadirlikte değil, yalnızca bilgilerde” diyerek nadirliği değer kaynağı olmaktan çıkarır; en güçlü çeldirici budur. C: “tamamen açığa çıkarılmıştır” gibi cümlede olmayan bir sonuç ekler. E: “en değerli kaynaklar arasında” diyerek bir üstünlük hükmü ekler ve “bilinmeyen yönleri açığa çıkarma” unsurunu düşürür.",
     "Doğru cevabımız D."]),

dict(n=69,
 stem="دفعت موجات الجفاف المتكررة آلاف المزارعين إلى هجرة أراضيهم والنزوح نحو المدن بحثا عن مصادر رزق بديلة.",
 opts=["Tekrarlanan kuraklık dalgaları nedeniyle topraklarını terk eden binlerce çiftçi, kentlerde alternatif geçim kaynakları bulmayı başarmıştır.",
       "Tekrarlanan kuraklık dalgaları, binlerce çiftçiyi alternatif geçim kaynakları aramak amacıyla topraklarını terk edip kentlere göç etmeye itmiştir.",
       "Tekrarlanan kuraklık dalgaları, binlerce çiftçiyi topraklarını satarak kentlerde yeni iş yerleri kurmaya zorlamıştır.",
       "Kentlerde alternatif geçim kaynakları bulma umudu, binlerce çiftçiyi kuraklık dönemlerinde bile topraklarını terk etmeye itmiştir.",
       "Tekrarlanan kuraklık dalgaları, binlerce çiftçiyi kentlere göç etmek yerine kendi topraklarında alternatif geçim kaynakları aramaya itmiştir."], ans="B",
 harakat="دَفَعَتْ مَوْجَاتُ الْجَفَافِ الْمُتَكَرِّرَةُ آلَافَ الْمُزَارِعِينَ إِلَى هِجْرَةِ أَرَاضِيهِمْ وَالنُّزُوحِ نَحْوَ الْمُدُنِ بَحْثًا عَنْ مَصَادِرِ رِزْقٍ بَدِيلَةٍ.",
 keys=[("دَفَعَ ... إِلَى", "...i ...e itmek, sevk etmek"),
       ("هِجْرَةُ أَرَاضِيهِمْ", "topraklarını terk etme"),
       ("النُّزُوحُ نَحْوَ الْمُدُنِ", "kentlere göç"),
       ("بَحْثًا عَنْ", "...i aramak amacıyla (mef‘ûlün leh)")],
 a2=["Fiil دَفَعَتْ, fâil مَوْجَاتُ الْجَفَافِ, mef‘ûl آلَافَ الْمُزَارِعِينَ'dir. دَفَعَ ... إِلَى kalıbı “birini bir şeye itmek” anlamındadır. بَحْثًا عَنْ ... mef‘ûlün leh olarak göçün amacını bildirir; amaçlanan şeyin bulunup bulunmadığı söylenmez.",
     "B şıkkı özne, yüklem ve amaç ilişkisini eksiksiz karşılar. A: “aramak” amacını “bulmayı başarmıştır” sonucuna çevirir; en güçlü çeldirici budur. C: “Topraklarını satmak” ve “iş yeri kurmak” cümlede yoktur. D: Sebebi kuraklıktan “kentte iş bulma umudu”na kaydırır. E: “kentlere göç etmek yerine” diyerek göçü olumsuzlar.",
     "Doğru cevabımız B."]),
]

SECTIONS.append(dict(
    rng=(70, 75),
    title="TÜRKÇEDEN ARAPÇAYA ÇEVİRİ",
    instr="70.-75. sorularda, verilen Türkçe cümleye anlamca en yakın Arapça cümleyi bulunuz.",
    skill="Bu bölüm; Türkçe cümlenin anlamını, zamanını ve mantıksal ilişkilerini Arapçada doğru sözdizimi, uygun fiil kalıpları ve edatlarla karşılayan cümleyi tanıyabilme becerisini ölçer.",
    strategy="Türkçe cümlede özne, yüklem ve temel ilişkiyi (amaç, sebep, “yalnızca ... değil”, “... sayesinde”) belirleyin; sonra Arapça şıklarda bu ilişkiyi kuran edatı arayın (مِنْ أَجْلِ، بِفَضْلِ، لَا ... فَحَسْبُ بَلْ ...). Niceleyici (بَعْضُ / جَمِيعُ) ve kiplik (يُمْكِنُ / يَجِبُ) farklarına dikkat edin.",
))

Q += [
dict(n=70,
 stem="Uzmanlar, dengeli beslenmenin bağışıklık sistemini güçlendirerek birçok hastalığa karşı koruma sağladığını vurgulamaktadır.",
 opts=["يؤكد الخبراء أن التغذية المتوازنة تقوي جهاز المناعة، لكنها لا توفر الحماية من أمراض كثيرة.",
       "يؤكد الخبراء أن تقوية جهاز المناعة من خلال الأدوية توفر الحماية من أمراض كثيرة.",
       "يؤكد الخبراء أن التغذية المتوازنة توفر الحماية من أمراض كثيرة من خلال تقوية جهاز المناعة.",
       "يرى بعض الخبراء أن التغذية المتوازنة قد تسهم في الحماية من بعض الأمراض بتقوية المناعة.",
       "يؤكد الخبراء أن جهاز المناعة القوي يغني عن التغذية المتوازنة في الحماية من الأمراض."], ans="C",
 keys=[("vurgulamaktadır", "يُؤَكِّدُ"),
       ("dengeli beslenme", "التَّغْذِيَةُ الْمُتَوَازِنَةُ"),
       ("bağışıklık sistemini güçlendirerek", "مِنْ خِلَالِ تَقْوِيَةِ جَهَازِ الْمَنَاعَةِ"),
       ("birçok hastalığa karşı koruma sağlar", "تُوَفِّرُ الْحِمَايَةَ مِنْ أَمْرَاضٍ كَثِيرَةٍ")],
 a2=["Türkçe cümlenin iskeleti: Uzmanlar (genel olarak, “bazı” değil) vurguluyor → dengeli beslenme → bağışıklığı güçlendirerek (yol / araç) → birçok hastalığa karşı koruma sağlar (sonuç). “-erek” zarf-fiili Arapçada مِنْ خِلَالِ ile araç anlamında karşılanır.",
     "C şıkkı: يُؤَكِّدُ الْخُبَرَاءُ أَنَّ التَّغْذِيَةَ الْمُتَوَازِنَةَ تُوَفِّرُ الْحِمَايَةَ مِنْ أَمْرَاضٍ كَثِيرَةٍ مِنْ خِلَالِ تَقْوِيَةِ جَهَازِ الْمَنَاعَةِ. أَنَّ'nin ismi التَّغْذِيَةَ, haberi تُوَفِّرُ cümlesidir.",
     "A: İlk yargıyı korur, ama لَكِنَّهَا لَا تُوَفِّرُ ile koruma sonucunu olumsuzlar. B: Aracı “dengeli beslenme”den “ilaçlar”a çevirir. D: Anlamı en çok koruyan çeldiricidir; ama özneyi بَعْضُ الْخُبَرَاءِ “bazı uzmanlar”a, “birçok hastalık”ı بَعْضُ الْأَمْرَاضِ “bazı hastalıklar”a çevirir ve قَدْ ile kesinliği azaltır. E: Beslenmeyi gereksiz gösterir; ilişkiyi tersine çevirir.",
     "Doğru cevabımız C."]),

dict(n=71,
 stem="Şehirlerdeki hava kirliliğini azaltmak için toplu taşıma araçlarının kullanımının teşvik edilmesi gerekmektedir.",
 opts=["ينبغي تشجيع استخدام وسائل النقل العام من أجل الحد من تلوث الهواء في المدن.",
       "أسهم تشجيع استخدام وسائل النقل العام في الحد من تلوث الهواء في المدن.",
       "ينبغي الحد من استخدام وسائل النقل العام من أجل تقليل تلوث الهواء في المدن.",
       "ينبغي تشجيع استخدام وسائل النقل العام حتى لو أدى ذلك إلى زيادة تلوث الهواء في المدن.",
       "يرى الخبراء أن تلوث الهواء في المدن يدفع الناس إلى تشجيع استخدام وسائل النقل العام."], ans="A",
 keys=[("gerekmektedir", "يَنْبَغِي"),
       ("teşvik edilmesi", "تَشْجِيعُ"),
       ("toplu taşıma araçları", "وَسَائِلُ النَّقْلِ الْعَامِّ"),
       ("hava kirliliğini azaltmak için", "مِنْ أَجْلِ الْحَدِّ مِنْ تَلَوُّثِ الْهَوَاءِ")],
 a2=["Türkçe cümle bir gereklilik (gerekmektedir) ve bir amaç (azaltmak için) bildiriyor. Arapçada gereklilik يَنْبَغِي ile, amaç مِنْ أَجْلِ / لِـ ile karşılanır. يَنْبَغِي'nin fâili تَشْجِيعُ mastarıdır.",
     "A şıkkı bütün unsurları karşılar: الْحَدُّ مِنْ “azaltmak, sınırlamak” demektir. B: Aynı unsurları kullanır, ama gerekliliği geçmişte gerçekleşmiş bir sonuca (أَسْهَمَ) çevirir; en güçlü çeldirici budur. C: “Teşvik etmek” yerine toplu taşımanın kullanımını “sınırlamak”tan söz eder. D: Amacı “kirlilik artsa bile” diyerek tersine çevirir. E: Gereklilik yerine bir sebep-sonuç tespiti yapar ve “uzmanlar” öznesini ekler.",
     "Doğru cevabımız A."]),

dict(n=72,
 stem="Tarihî yapıların korunması, yalnızca geçmişe duyulan saygının değil, aynı zamanda gelecek nesillere karşı sorumluluğun da bir göstergesidir.",
 opts=["يعد الحفاظ على المباني التاريخية دليلا على احترام الماضي أكثر من كونه دليلا على المسؤولية تجاه الأجيال القادمة.",
       "لا يعد الحفاظ على المباني التاريخية دليلا على احترام الماضي، بل على المسؤولية تجاه الأجيال القادمة فقط.",
       "تتحمل الأجيال القادمة مسؤولية الحفاظ على المباني التاريخية احتراما للماضي وحفاظا على هويتها.",
       "لا يعد ترميم المباني التاريخية واجبا تجاه الماضي فحسب، بل استثمارا اقتصاديا للأجيال القادمة أيضا.",
       "لا يعد الحفاظ على المباني التاريخية دليلا على احترام الماضي فحسب، بل على المسؤولية تجاه الأجيال القادمة أيضا."], ans="E",
 keys=[("yalnızca ... değil, aynı zamanda ... da", "لَا ... فَحَسْبُ، بَلْ ... أَيْضًا"),
       ("göstergesidir", "يُعَدُّ دَلِيلًا عَلَى"),
       ("gelecek nesillere karşı sorumluluk", "الْمَسْؤُولِيَّةُ تُجَاهَ الْأَجْيَالِ الْقَادِمَةِ")],
 a2=["Türkçe cümle “yalnızca ... değil, aynı zamanda ... da” yapısıyla iki unsuru eşit derecede ekliyor. Arapçadaki karşılığı لَا ... فَحَسْبُ، بَلْ ... أَيْضًا yapısıdır.",
     "E şıkkı bu yapıyı birebir kurar. دَلِيلًا, يُعَدُّ fiilinin ikinci mef‘ûlü olarak mansuptur; بَلْ عَلَى الْمَسْؤُولِيَّةِ ifadesi عَلَى احْتِرَامِ ifadesine atfedilmiştir.",
     "A: İki unsuru eşitlemek yerine birini üstün tutar (أَكْثَرَ مِنْ كَوْنِهِ). B: فَحَسْبُ'ün yerine فَقَطْ koyarak “geçmişe saygı”yı dışlar; kelimeler neredeyse aynı olduğu için en güçlü çeldirici budur. C: Sorumluluğu gelecek nesillere yükler; özne değişmiştir. D: Aynı kalıbı kullanır, ama “koruma” yerine “restorasyon”, “sorumluluk” yerine “ekonomik yatırım” der.",
     "Doğru cevabımız E."]),

dict(n=73,
 stem="Yapılan araştırmalar, çocukların erken yaşta kitapla tanışmasının dil gelişimlerini olumlu yönde etkilediğini ortaya koymuştur.",
 opts=["كشفت الأبحاث التي أجريت أن النمو اللغوي المبكر لدى الأطفال يدفعهم إلى التعرف على الكتاب.",
       "كشفت الأبحاث التي أجريت أن تعرف الأطفال على الكتاب في سن مبكرة قد لا يؤثر في نموهم اللغوي.",
       "كشفت الأبحاث التي أجريت أن قراءة الآباء للأطفال يوميا تؤثر إيجابا في نموهم اللغوي والعقلي.",
       "كشفت الأبحاث التي أجريت أن تعرف الأطفال على الكتاب في سن مبكرة يؤثر إيجابا في نموهم اللغوي.",
       "تشير بعض الأبحاث إلى أن الأطفال الذين يتعرفون على الكتاب مبكرا يتفوقون دراسيا في جميع المواد."], ans="D",
 keys=[("yapılan araştırmalar", "الْأَبْحَاثُ الَّتِي أُجْرِيَتْ"),
       ("ortaya koymuştur", "كَشَفَتْ"),
       ("kitapla erken yaşta tanışma", "تَعَرُّفُ الْأَطْفَالِ عَلَى الْكِتَابِ فِي سِنٍّ مُبَكِّرَةٍ"),
       ("olumlu yönde etkiler", "يُؤَثِّرُ إِيجَابًا فِي")],
 a2=["Cümlenin iskeleti: araştırmalar ortaya koydu → erken yaşta kitapla tanışma (sebep) → dil gelişimini olumlu etkiler (sonuç). الْأَبْحَاثُ الَّتِي أُجْرِيَتْ “yapılan araştırmalar” ifadesinde أُجْرِيَتْ meçhul fiildir.",
     "D şıkkı bütün unsurları eksiksiz karşılar: تَعَرُّفُ ... عَلَى الْكِتَابِ “kitapla tanışma”, إِيجَابًا “olumlu yönde”, يُؤَثِّرُ فِي “...i etkiler”.",
     "A: Sebep-sonucu ters çevirir. B: Aynı kelimeleri kullanır, ama قَدْ لَا يُؤَثِّرُ “etkilemeyebilir” diyerek hükmü olumsuza çevirir. C: Sebebi “kitapla tanışma”dan “ebeveynlerin her gün kitap okuması”na çevirir ve “zihinsel gelişim”i ekler. E: “Bazı araştırmalar” ve “bütün derslerde başarı” diyerek hem özneyi hem de sonucu değiştirir.",
     "Doğru cevabımız D."]),

dict(n=74,
 stem="Dijital dönüşüm, şirketlerin iş yapma biçimlerini köklü bir şekilde değiştirmiş ve onları yeni beceriler kazanmaya zorlamıştır.",
 opts=["غير التحول الرقمي أساليب عمل الشركات تغييرا جذريا دون أن يضطرها إلى اكتساب مهارات جديدة.",
       "غير التحول الرقمي أساليب عمل الشركات تغييرا جذريا واضطرها إلى اكتساب مهارات جديدة.",
       "اضطرت الشركات إلى اكتساب مهارات جديدة كي تتمكن من تغيير أساليب عملها قبل التحول الرقمي.",
       "أحدث التحول الرقمي تغييرا محدودا في أساليب عمل الشركات، لكنه اضطرها إلى اكتساب مهارات جديدة.",
       "غيرت الشركات أساليب عملها تغييرا جذريا واكتسبت مهارات جديدة لتقود التحول الرقمي."], ans="B",
 keys=[("köklü bir şekilde değiştirmiş", "غَيَّرَ ... تَغْيِيرًا جَذْرِيًّا"),
       ("yeni beceriler kazanmaya zorlamıştır", "اضْطَرَّهَا إِلَى اكْتِسَابِ مَهَارَاتٍ جَدِيدَةٍ"),
       ("iş yapma biçimleri", "أَسَالِيبُ الْعَمَلِ")],
 a2=["Türkçe cümlede özne “dijital dönüşüm”dür ve iki yüklemi vardır: “köklü şekilde değiştirmiş” ve “zorlamıştır”. Arapçada “köklü şekilde” anlamı mef‘ûl-i mutlak + sıfat (تَغْيِيرًا جَذْرِيًّا) ile verilir. “Zorlamak” anlamı اضْطَرَّ ... إِلَى kalıbıyla karşılanır.",
     "B şıkkı özneyi, iki yüklemi ve dereceyi korur. اضْطَرَّهَا'daki هَا zamiri الشَّرِكَاتِ kelimesine döner (akıl sahibi olmayan çoğul, müfred müennes zamirle karşılanır).",
     "A: İlk yüklemi korur, ama دُونَ أَنْ يَضْطَرَّهَا ile ikinci yüklemi olumsuzlar. C: Özneyi şirketlere çevirir ve olayları dijital dönüşümden önceye taşır. D: İkinci yüklemi korur, ama “köklü” yerine “sınırlı” (مَحْدُودًا) der. E: Özneyi şirketlere çevirir ve dönüşümü şirketlerin amacı hâline getirir.",
     "Doğru cevabımız B."]),

dict(n=75,
 stem="Gönüllülük faaliyetleri, bireylerin toplumsal aidiyet duygusunu pekiştirirken aynı zamanda onların kişisel gelişimine de katkı sağlar.",
 opts=["تعزز الأنشطة التطوعية شعور الأفراد بالانتماء الاجتماعي، لكنها تكون أحيانا على حساب تنميتهم الشخصية.",
       "تسهم الأنشطة التطوعية في تنمية الأفراد الشخصية أكثر مما تعزز شعورهم بالانتماء الاجتماعي.",
       "تعزز الأنشطة التطوعية شعور الأفراد بالانتماء الاجتماعي، وتسهم في الوقت نفسه في تنميتهم الشخصية.",
       "يقتصر أثر الأنشطة التطوعية على تعزيز شعور الأفراد بالانتماء الاجتماعي دون تنميتهم الشخصية.",
       "يدفع الشعور بالانتماء الاجتماعي الأفراد إلى المشاركة في الأنشطة التطوعية وتنمية مهاراتهم الشخصية."], ans="C",
 keys=[("pekiştirir", "تُعَزِّزُ"),
       ("toplumsal aidiyet duygusu", "الشُّعُورُ بِالِانْتِمَاءِ الِاجْتِمَاعِيِّ"),
       ("aynı zamanda", "فِي الْوَقْتِ نَفْسِهِ"),
       ("katkı sağlar", "تُسْهِمُ فِي")],
 a2=["Türkçe cümlede “-irken aynı zamanda ... de” yapısı iki olumlu sonucun birlikte ve eşit derecede gerçekleştiğini bildirir. Arapçada bu, iki fiilin وَ ile bağlanması ve فِي الْوَقْتِ نَفْسِهِ (aynı zamanda) ifadesiyle karşılanır.",
     "C şıkkı her iki sonucu ve eşzamanlılığı korur. فِي الْوَقْتِ نَفْسِهِ ifadesinde نَفْسِهِ tekid bildirir.",
     "A: İlk sonucu korur, ama عَلَى حِسَابِ (...pahasına) ile ikinci sonucu olumsuza çevirir. B: İki sonucu eşitlemek yerine birini üstün tutar (أَكْثَرَ مِمَّا). D: يَقْتَصِرُ عَلَى ile etkiyi aidiyet duygusuna indirger ve kişisel gelişimi dışlar. E: Aidiyeti gönüllülüğün sebebi yapar; ilişki ters çevrilmiştir.",
     "Doğru cevabımız C."]),
]

SECTIONS.append(dict(
    rng=(76, 80),
    title="ANLAM BÜTÜNLÜĞÜNÜ BOZAN CÜMLE",
    instr="76.-80. sorularda, cümleler sırasıyla okunduğunda anlam bütünlüğünü bozan cümleyi bulunuz.",
    skill="Bu bölüm; paragrafın ana konusunu ve düşünce akışını izleyerek, konuyla ilgili görünse bile akışın dışına çıkan cümleyi tespit edebilme becerisini ölçer.",
    strategy="Önce ilk cümleden paragrafın konusunu ve yönünü belirleyin; sonra her cümlenin bir öncekine bağlaç, zamir veya işaret ismi (هَذِهِ، ذَلِكَ، ـهُ) ile nasıl bağlandığını izleyin. Şüpheli cümleyi çıkarıp paragrafı yeniden okuyun: akış kesintisiz sürüyorsa doğru cevabı bulmuşsunuzdur. Aynı kavramı içeren ama farklı bir yöne sapan cümlelere dikkat edin.",
))

Q += [
dict(n=76,
 sents=["يعد الملح من أقدم المواد التي استخدمها الإنسان في حفظ الأطعمة.",
        "فهو يسحب الماء من خلايا الطعام، مما يحد من نمو البكتيريا المسببة للتلف.",
        "ويحتوي ماء البحر على نسبة من الأملاح تختلف من بحر إلى آخر.",
        "وقد مكنت هذه الطريقة الشعوب القديمة من تخزين اللحوم والأسماك مدة طويلة.",
        "ولذلك احتل الملح مكانة اقتصادية مهمة حتى إنه استخدم أحيانا وسيلة للمقايضة."], ans="C",
 tr=["Tuz, insanın yiyecekleri korumada kullandığı en eski maddelerden biri sayılır.",
     "Çünkü tuz, yiyeceğin hücrelerindeki suyu çeker ve bu da bozulmaya neden olan bakterilerin üremesini sınırlar.",
     "Deniz suyu, denizden denize değişen oranda tuz içerir.",
     "Bu yöntem, eski toplumların eti ve balığı uzun süre saklamasını mümkün kılmıştır.",
     "Bu nedenle tuz önemli bir ekonomik konum kazanmış, hatta zaman zaman takas aracı olarak kullanılmıştır."],
 a2=["Paragrafın konusu ilk cümlede veriliyor: tuzun yiyecekleri korumada kullanılması.",
     "II. cümle فَهُوَ ile başlıyor; هُوَ zamiri الْمِلْحُ kelimesine dönüyor ve tuzun koruma işlevini nasıl yerine getirdiğini açıklıyor.",
     "III. cümle tuzla ilgili bir bilgi verse de konuyu “yiyecek koruma”dan “deniz suyundaki tuz oranı”na kaydırıyor. Ayrıca IV. cümlenin başındaki هَذِهِ الطَّرِيقَةُ (bu yöntem) ifadesi, III. cümlede hiçbir yönteme işaret edilmediği için bağlantısız kalıyor.",
     "III. cümle çıkarıldığında IV. cümledeki هَذِهِ الطَّرِيقَةُ ifadesi II. cümlede anlatılan tuzlama yöntemine döner; V. cümle ise وَلِذَلِكَ ile tuzun ekonomik önemini bu yönteme bağlar. Akış kesintisiz hâle gelir.",
     "Doğru cevabımız C (III)."]),

dict(n=77,
 sents=["تعد الهجرة الموسمية من أعجب الظواهر في عالم الطيور.",
        "إذ تقطع بعض الأنواع آلاف الكيلومترات سنويا بين مناطق التكاثر ومناطق قضاء الشتاء.",
        "ويعتقد العلماء أن الطيور تستعين في رحلاتها بموقع الشمس والنجوم والمجال المغناطيسي للأرض.",
        "كما تعتمد بعض الأنواع على المعالم الطبيعية كالأنهار وسلاسل الجبال في تحديد مساراتها.",
        "وتتميز ذكور بعض الطيور المهاجرة بألوان زاهية تساعدها على جذب الإناث في موسم التكاثر."], ans="E",
 tr=["Mevsimsel göç, kuşlar dünyasının en şaşırtıcı olgularından biri sayılır.",
     "Zira bazı türler, üreme bölgeleri ile kışlama bölgeleri arasında her yıl binlerce kilometre kat eder.",
     "Bilim insanları, kuşların yolculuklarında güneşin ve yıldızların konumundan ve Dünya'nın manyetik alanından yararlandığına inanıyor.",
     "Ayrıca bazı türler, rotalarını belirlemede nehirler ve sıradağlar gibi doğal işaretlere dayanır.",
     "Bazı göçmen kuşların erkekleri, üreme mevsiminde dişileri cezbetmelerine yardımcı olan parlak renklere sahiptir."],
 a2=["Paragrafın konusu kuşların mevsimsel göçüdür. II. cümle إِذْ ile göçün neden şaşırtıcı olduğunu (binlerce kilometre) açıklıyor.",
     "III. ve IV. cümleler göç sırasında kuşların yön bulma yöntemlerini anlatıyor; IV. cümlenin başındaki كَمَا ekleme bildirerek III. cümleye bağlanıyor. Paragrafın akışı “göç → yön bulma” şeklinde ilerliyor.",
     "V. cümle yine göçmen kuşlardan söz ediyor ve “üreme mevsimi” ifadesini içeriyor; bu yüzden ilk bakışta paragrafa uyuyor gibi görünür. Ancak konuyu yön bulmadan erkek kuşların renkleri ve eş seçimine kaydırıyor. Bu cümle akışı bozan cümledir.",
     "Doğru cevabımız E (V)."]),

dict(n=78,
 sents=["شهدت العقود الأخيرة تزايدا ملحوظا في الإقبال على العمل الحر عبر الإنترنت.",
        "ويشترط كثير من أصحاب العمل حضور الموظفين إلى مقار الشركات يوميا.",
        "ويرجع ذلك إلى ما يوفره هذا النمط من مرونة في تحديد أوقات العمل ومكانه.",
        "غير أن العاملين فيه يواجهون تحديات، أبرزها عدم استقرار الدخل وغياب التأمينات الاجتماعية.",
        "ولذلك يطالب بعضهم بتشريعات تضمن لهم حقوقا مماثلة لحقوق الموظفين التقليديين."], ans="B",
 tr=["Son on yıllarda internet üzerinden serbest çalışmaya ilgide belirgin bir artış yaşanmıştır.",
     "Pek çok işveren, çalışanların her gün şirket merkezlerine gelmesini şart koşar.",
     "Bu, söz konusu çalışma biçiminin iş saatlerini ve mekânını belirlemede sağladığı esneklikten kaynaklanmaktadır.",
     "Ancak bu alanda çalışanlar, başlıcaları gelir istikrarsızlığı ve sosyal güvence yokluğu olan birtakım zorluklarla karşılaşmaktadır.",
     "Bu nedenle bazıları, kendilerine geleneksel çalışanların haklarına benzer haklar güvence altına alan yasal düzenlemeler talep etmektedir."],
 a2=["Paragrafın konusu internet üzerinden serbest çalışmadır (الْعَمَلُ الْحُرُّ عَبْرَ الْإِنْتَرْنِتِ).",
     "III. cümledeki ذَلِكَ işaret ismi, I. cümlede anlatılan “ilgideki artışa” döner; هَذَا النَّمَطُ (bu çalışma biçimi) de serbest çalışmayı gösterir. Yani III. cümle doğrudan I. cümleye bağlanır.",
     "II. cümle ise işyerine gelme zorunluluğu olan geleneksel çalışma düzeninden söz ediyor. Hem konuyu değiştiriyor hem de araya girerek III. cümledeki ذَلِكَ ve هَذَا النَّمَطُ göndermelerini yanlış yere yöneltiyor (“işverenlerin şartı esneklikten kaynaklanır” gibi anlamsız bir ilişki doğar).",
     "II. cümle çıkarıldığında akış: artış → sebebi (esneklik) → zorluklar (غَيْرَ أَنَّ) → talepler (وَلِذَلِكَ) şeklinde kesintisiz ilerler.",
     "Doğru cevabımız B (II)."]),

dict(n=79,
 sents=["يعد زيت الزيتون من الركائز الأساسية للنظام الغذائي في حوض البحر الأبيض المتوسط.",
        "وتشير دراسات عديدة إلى أن تناوله باعتدال يسهم في خفض خطر الإصابة بأمراض القلب.",
        "ويعزى ذلك إلى احتوائه على الأحماض الدهنية غير المشبعة ومضادات الأكسدة.",
        "ويستخدم زيت الزيتون منذ القدم في صناعة الصابون ومستحضرات التجميل.",
        "ولهذا ينصح خبراء التغذية باستخدامه بديلا عن الدهون الحيوانية في الطهي."], ans="D",
 tr=["Zeytinyağı, Akdeniz havzasındaki beslenme düzeninin temel dayanaklarından biri sayılır.",
     "Pek çok çalışma, ölçülü tüketilmesinin kalp hastalıkları riskini azaltmaya katkıda bulunduğuna işaret etmektedir.",
     "Bu durum, onun doymamış yağ asitleri ve antioksidanlar içermesine bağlanmaktadır.",
     "Zeytinyağı eski çağlardan beri sabun ve kozmetik ürünlerinin yapımında kullanılmaktadır.",
     "Bu nedenle beslenme uzmanları yemeklerde hayvansal yağlar yerine onun kullanılmasını tavsiye etmektedir."],
 a2=["Paragrafın konusu zeytinyağının beslenmedeki yeri ve sağlığa faydalarıdır.",
     "II. cümle sağlık faydasını, III. cümle ise ذَلِكَ işaret ismiyle bu faydanın sebebini veriyor. يُعْزَى ذَلِكَ إِلَى “bu, ...e bağlanır” demektir.",
     "IV. cümle de zeytinyağından söz ettiği için ilk bakışta paragrafa uygun görünür; fakat konuyu beslenme ve sağlıktan sabun ve kozmetik sanayisine kaydırır.",
     "V. cümledeki وَلِهَذَا (bu nedenle), beslenme uzmanlarının tavsiyesini II. ve III. cümlelerdeki sağlık faydalarına bağlar. IV. cümle araya girdiğinde bu bağ kopar: “sabun yapımında kullanıldığı için beslenme uzmanları onu tavsiye eder” gibi mantıksız bir ilişki doğar.",
     "Doğru cevabımız D (IV)."]),

dict(n=80,
 sents=["يؤثر الضوء الأزرق المنبعث من شاشات الهواتف والحواسيب في جودة النوم.",
        "إذ يثبط إفراز هرمون الميلاتونين الذي يساعد الجسم على الاستعداد للنوم.",
        "وتتميز الشاشات الحديثة بدقة عرض عالية بفضل تقنيات الإضاءة المتطورة.",
        "ونتيجة لذلك يجد كثير من مستخدمي هذه الأجهزة ليلا صعوبة في الخلود إلى النوم.",
        "لذلك ينصح الأطباء بالتوقف عن استخدام الشاشات قبل موعد النوم بساعة على الأقل."], ans="C",
 tr=["Telefon ve bilgisayar ekranlarından yayılan mavi ışık uyku kalitesini etkiler.",
     "Zira bu ışık, vücudun uykuya hazırlanmasına yardımcı olan melatonin hormonunun salgılanmasını baskılar.",
     "Modern ekranlar, gelişmiş aydınlatma teknolojileri sayesinde yüksek bir görüntü çözünürlüğüne sahiptir.",
     "Bunun sonucunda bu cihazları gece kullananların çoğu uykuya dalmakta zorlanır.",
     "Bu nedenle doktorlar, yatmadan en az bir saat önce ekran kullanımının bırakılmasını tavsiye eder."],
 a2=["Paragrafın konusu I. cümlede veriliyor: ekranlardan yayılan mavi ışığın uyku kalitesine etkisi. II. cümle إِذْ ile bu etkinin sebebini (melatonin salgısının baskılanması) açıklıyor.",
     "III. cümle de ekranlardan ve ışıktan (الْإِضَاءَة) söz ettiği için ilk bakışta paragrafa uyuyor gibi görünür; ancak konuyu “uyku”dan ekranların görüntü kalitesine kaydırır.",
     "Asıl ipucu IV. cümlenin başındaki وَنَتِيجَةً لِذَلِكَ (bunun sonucunda) ifadesidir. III. cümle araya girdiğinde ذَلِكَ işaret ismi “yüksek çözünürlüğe” döner ve “ekranlar yüksek çözünürlüklü olduğu için insanlar uyuyamıyor” gibi mantıksız bir ilişki doğar. III. cümle çıkarıldığında ذَلِكَ, II. cümledeki melatonin baskılanmasına döner; V. cümle de لِذَلِكَ ile doktorların tavsiyesini bu sonuca bağlar.",
     "Doğru cevabımız C (III)."]),
]
