# -*- coding: utf-8 -*-
# Sorular 44-63

SECTIONS = []
Q = []

SECTIONS.append(dict(
    rng=(44, 48),
    title="DİYALOG TAMAMLAMA",
    instr="44.-48. sorularda, karşılıklı konuşmanın boş bırakılan kısmını tamamlayabilecek ifadeyi bulunuz.",
    skill="Bu bölüm; günlük ve kurumsal iletişimde konuşmanın akışını, soru-cevap ilişkisini ve konuşmacının niyetini bağlam içinde kavrayabilme becerisini ölçer.",
    strategy="Boşluğun yalnızca öncesine değil mutlaka sonrasına da bakın; çoğu zaman çözümü veren ipucu, boşluktan sonraki repliktedir. Şıkları boşluğa yerleştirdiğinizde hem önceki soruya cevap vermesi hem de sonraki repliği doğal olarak tetiklemesi gerekir.",
))

Q += [
dict(n=44,
 dialog=[("أحمد", "سمعت أنك انتقلت إلى شقة جديدة قريبة من مكان عملك."),
         ("خالد", "----"),
         ("أحمد", "هذا رائع، فقد كنت تشكو دائما من زحمة الطريق والوقت الذي تضيعه في التنقل."),
         ("خالد", "صدقت، أصبح لدي الآن وقت أطول لممارسة هواياتي.")],
 opts=["لا، ما زلت أبحث عن شقة مناسبة بسعر معقول.",
       "نعم، لكنني أفكر في العودة إلى شقتي القديمة.",
       "نعم، وأصبحت أصل إلى عملي سيرا على الأقدام في عشر دقائق.",
       "انتقلت إليها مؤقتا حتى تنتهي أعمال الصيانة في منزلي.",
       "الشقة الجديدة أوسع من القديمة، لكنها أبعد عن العمل."], ans="C",
 tr=["Ahmed: İş yerine yakın yeni bir daireye taşındığını duydum.",
     "Hâlid: ----",
     "Ahmed: Bu harika; çünkü sürekli yol trafiğinden ve yolda harcadığın zamandan şikâyet ediyordun.",
     "Hâlid: Doğru söyledin; artık hobilerime ayıracak daha çok vaktim var."],
 a2=["Ahmed'in ikinci repliğindeki هَذَا رَائِعٌ (bu harika) ifadesi, boşlukta olumlu bir haber verildiğini gösteriyor. Ardından gelen زَحْمَةُ الطَّرِيقِ وَالْوَقْتُ الَّذِي تُضَيِّعُهُ فِي التَّنَقُّلِ (yol trafiği ve yolda kaybedilen zaman) ifadesi de haberin ulaşım süresiyle ilgili olduğunu söylüyor. Son replikte Hâlid'in artık daha çok vakti olması bunu doğruluyor.",
     "C şıkkı “Evet, artık işe yürüyerek on dakikada ulaşıyorum.” diyerek hem taşındığını onaylar hem de yol sorununun çözüldüğünü bildirir. سَيْرًا عَلَى الْأَقْدَامِ “yürüyerek” anlamında hâl olarak mansuptur.",
     "A: Taşınmadığını söylediği için “Bu harika” cevabıyla çelişir. B: Eski daireye dönmeyi düşünmek, olumlu tepkiyle ve “artık daha çok vaktim var” cümlesiyle uyuşmaz. D: Geçici taşınma ve bakım işleri, yol sorununun çözüldüğü fikrini tetiklemez. E: Yeni dairenin işe daha uzak olduğu bilgisi, Ahmed'in ilk repliğindeki “iş yerine yakın” ifadesiyle ve sonraki olumlu tepkiyle çelişir.",
     "Doğru cevabımız C."]),

dict(n=45,
 dialog=[("الصحفي", "ما الذي دفعك إلى تأسيس هذه الجمعية الخيرية؟"),
         ("السيدة سعاد", "----"),
         ("الصحفي", "إذن كانت تجربتك الشخصية هي الدافع الحقيقي وراء هذا المشروع."),
         ("السيدة سعاد", "بالضبط، فمن ذاق مرارة الحاجة يدرك قيمة العون.")],
 opts=["تلقت الجمعية في عامها الأول تبرعات كثيرة فاقت كل توقعاتنا.",
       "نشأت في أسرة فقيرة، فعرفت منذ صغري معنى الحاجة إلى العون.",
       "أسسناها قبل خمس سنوات بمشاركة عدد من المتطوعين.",
       "نسعى إلى توسيع نشاط الجمعية ليشمل مدنا أخرى.",
       "اقترح علي أحد الأصدقاء الفكرة قبل سنوات، فوافقت عليها دون تردد."], ans="B",
 tr=["Gazeteci: Sizi bu hayır derneğini kurmaya ne sevk etti?",
     "Suâd Hanım: ----",
     "Gazeteci: Demek ki bu projenin arkasındaki asıl itici güç kişisel tecrübenizmiş.",
     "Suâd Hanım: Aynen öyle; ihtiyacın acısını tadan kişi yardımın değerini bilir."],
 a2=["Gazetecinin sorusu مَا الَّذِي دَفَعَكِ إِلَى ...؟ bir motivasyon / sebep soruyor. Boşluktan sonraki replikte ise إِذَنْ (demek ki) ile bir sonuç çıkarılıyor: تَجْرِبَتُكِ الشَّخْصِيَّةُ (kişisel tecrübeniz). Son replikteki مَنْ ذَاقَ مَرَارَةَ الْحَاجَةِ (ihtiyacın acısını tadan) ifadesi de bu tecrübenin yoksulluk olduğunu gösteriyor.",
     "B şıkkı “Yoksul bir ailede büyüdüm; bu yüzden küçüklüğümden beri yardıma muhtaç olmanın ne demek olduğunu bildim.” diyerek hem sebebi hem de kişisel tecrübeyi verir.",
     "E şıkkı bir sebep bildirir, ancak bu bir arkadaşın önerisidir, kişisel tecrübe değildir; bu yüzden إِذَنْ ile çıkarılan sonuçla uyuşmaz. Bu şık en güçlü çeldiricidir. A (bağışlar), C (kuruluş tarihi) ve D (gelecek planları) soruya cevap vermez.",
     "Doğru cevabımız B."]),

dict(n=46,
 dialog=[("المريض", "يا دكتور، أشعر بصداع مستمر منذ أسبوع، خاصة عندما أعمل أمام الحاسوب."),
         ("الطبيب", "----"),
         ("المريض", "نعم، أقضي أكثر من عشر ساعات يوميا أمام الشاشة دون استراحة تقريبا."),
         ("الطبيب", "هذا هو السبب على الأرجح، فعليك أن تأخذ استراحة قصيرة كل ساعة وأن تفحص نظرك.")],
 opts=["هل تعاني من حساسية تجاه بعض الأدوية؟",
       "متى أجريت آخر تحليل للدم؟",
       "عليك أن تتناول هذا الدواء ثلاث مرات يوميا.",
       "هل يعاني أحد من أفراد أسرتك من الصداع؟",
       "هل تقضي ساعات طويلة في العمل أمام الشاشة؟"], ans="E",
 tr=["Hasta: Doktor bey, bir haftadır, özellikle bilgisayar başında çalışırken sürekli bir baş ağrısı hissediyorum.",
     "Doktor: ----",
     "Hasta: Evet, günde on saatten fazla, neredeyse hiç ara vermeden ekran başında kalıyorum.",
     "Doktor: Büyük ihtimalle sebep bu; her saat kısa bir mola vermeli ve gözlerini muayene ettirmelisin."],
 a2=["Boşluktan sonraki replik نَعَمْ ile başlıyor; demek ki boşlukta evet / hayır cevabı alınabilecek bir soru var. Hastanın cevabı ekran başında geçirilen süreyi anlatıyor: أَقْضِي أَكْثَرَ مِنْ عَشْرِ سَاعَاتٍ يَوْمِيًّا أَمَامَ الشَّاشَةِ.",
     "E şıkkı “Ekran başında uzun saatler çalışıyor musun?” sorusuyla bu cevabı doğrudan tetikler. Doktorun son repliğindeki هَذَا هُوَ السَّبَبُ (sebep bu) ifadesi de ekran süresine işaret eder.",
     "A, B ve D şıkları da evet / hayır ile cevaplanabilecek sorulardır; ancak hastanın “evet, günde on saatten fazla ekran başındayım” cevabıyla ilgisizdir. C şıkkı soru değil bir talimattır; ardından نَعَمْ ile başlayan bir açıklama gelmez.",
     "Doğru cevabımız E."]),

dict(n=47,
 dialog=[("ريم", "لماذا تبدين قلقة يا منى؟"),
         ("منى", "----"),
         ("ريم", "لا تقلقي، فأنت مستعدة جيدا، وقد تدربت على العرض أمامنا أكثر من مرة."),
         ("منى", "أتمنى أن يكون الأمر كما تقولين.")],
 opts=["سأقدم غدا عرضا عن مشروع تخرجي أمام لجنة من الأساتذة.",
       "نسيت أن أحضر حاسوبي المحمول إلى الجامعة اليوم.",
       "لم أتمكن من النوم أمس بسبب الضوضاء في الشارع.",
       "انتهيت من تقديم عرضي، وأنتظر النتيجة الآن.",
       "أخشى أن يتأخر القطار غدا كما حدث معي الأسبوع الماضي."], ans="A",
 tr=["Rîm: Neden endişeli görünüyorsun Münâ?",
     "Münâ: ----",
     "Rîm: Endişelenme; iyi hazırlandın ve sunumu önümüzde birçok kez prova ettin.",
     "Münâ: Umarım dediğin gibi olur."],
 a2=["Rîm'in ikinci repliği çözümün anahtarıdır: فَأَنْتِ مُسْتَعِدَّةٌ جَيِّدًا، وَقَدْ تَدَرَّبْتِ عَلَى الْعَرْضِ (iyi hazırlandın, sunumu prova ettin). Demek ki Münâ'nın endişesi henüz yapılmamış bir sunumla ilgilidir.",
     "A şıkkı “Yarın hocalardan oluşan bir jüri önünde bitirme projem hakkında bir sunum yapacağım.” diyerek endişenin sebebini verir ve sonraki repliği doğal olarak tetikler.",
     "D şıkkı da sunumdan söz eder, fakat sunumun bittiğini söyler; “iyi hazırlandın, prova ettin” teselli cümlesi geleceğe yönelik olduğundan bu şık zaman bakımından uyuşmaz. Bu şık en güçlü çeldiricidir. B (bilgisayarı unutmak), C (uykusuzluk) ve E (trenin gecikmesi) endişe sebebi olabilir, ama “hazırlık ve prova” teselli cümlesiyle ilgisizdir.",
     "Doğru cevabımız A."]),

dict(n=48,
 dialog=[("الموظف", "أود أن أحصل على إجازة لمدة أسبوعين في الشهر المقبل."),
         ("المديرة", "----"),
         ("الموظف", "أتفهم ذلك، ويمكنني تأجيل إجازتي إلى ما بعد تسليم المشروع."),
         ("المديرة", "شكرا لتفهمك، سأوافق عليها فور الانتهاء منه.")],
 opts=["بالطبع، يمكنك أن تبدأ إجازتك من الغد إن شئت.",
       "لماذا لم تطلب إجازة أطول من ذلك لتستريح جيدا؟",
       "هل ستسافر إلى الخارج خلال الإجازة؟",
       "الشهر المقبل موعد تسليم المشروع الكبير، ونحتاج فيه إلى الجميع.",
       "لقد استنفدت جميع أيام إجازتك السنوية لهذا العام، ولا يمكنني منحك المزيد."], ans="D",
 tr=["Çalışan: Önümüzdeki ay iki haftalık izin almak istiyorum.",
     "Müdire: ----",
     "Çalışan: Anlıyorum; iznimi projenin tesliminden sonrasına erteleyebilirim.",
     "Müdire: Anlayışın için teşekkürler; proje biter bitmez iznini onaylayacağım."],
 a2=["Çalışanın ikinci repliği iki ipucu içeriyor: أَتَفَهَّمُ ذَلِكَ (bunu anlıyorum) ifadesi, müdirenin bir engel ya da gerekçe sunduğunu; تَسْلِيمِ الْمَشْرُوعِ (projenin teslimi) ifadesi de bu gerekçenin bir projeyle ilgili olduğunu gösteriyor. Son replikteki الِانْتِهَاءِ مِنْهُ ifadesindeki zamir de الْمَشْرُوع kelimesine döner.",
     "D şıkkı “Önümüzdeki ay büyük projenin teslim tarihi ve o ay herkese ihtiyacımız var.” diyerek hem engeli hem de projeyi ilk kez gündeme getirir.",
     "E şıkkı da bir engel bildirir; ancak izin günleri tükenmişse ertelemek sorunu çözmez ve projeden söz edilmediği için sonraki repliklerdeki “proje” göndermesi karşılıksız kalır. A şıkkı izni hemen onaylar; “anlıyorum, erteleyebilirim” cevabıyla çelişir. B ve C şıkları engel bildirmez.",
     "Doğru cevabımız D."]),
]

SECTIONS.append(dict(
    rng=(49, 53),
    title="ANLAMCA EN YAKIN CÜMLE (Restatement)",
    instr="49.-53. sorularda, verilen cümleye anlamca en yakın cümleyi bulunuz.",
    skill="Bu bölüm; bir cümlenin anlamını farklı kelime ve yapılarla ifade edilmiş hâliyle eşleştirebilme, özellikle sebep-sonuç, şart, olumsuzluk ve sınırlama ilişkilerini koruyabilme becerisini ölçer.",
    strategy="Verilen cümlenin iskeletini (kim, ne yapıyor, hangi şartla, hangi sonuçla) çıkarın. Şıklarda sebep-sonucun ters çevrilmesine, olumluluğun olumsuza dönüştürülmesine, “bazı / bütün”, “olabilir / kesin” gibi derece farklarına ve cümlede olmayan yeni bilgilere dikkat edin.",
))

Q += [
dict(n=49,
 stem="لا يمكن تحقيق التنمية المستدامة دون مشاركة فاعلة من المجتمع المدني.",
 opts=["تكفي المشاركة الفاعلة للمجتمع المدني وحدها لتحقيق التنمية المستدامة.",
       "تسهم مشاركة المجتمع المدني أحيانا في تحقيق التنمية المستدامة، لكنها ليست ضرورية.",
       "لا يمكن للمجتمع المدني أن يشارك مشاركة فاعلة ما لم تتحقق التنمية المستدامة.",
       "تؤدي التنمية المستدامة إلى تعزيز مشاركة المجتمع المدني في الحياة العامة.",
       "تعد المشاركة الفاعلة للمجتمع المدني شرطا أساسيا لتحقيق التنمية المستدامة."], ans="E",
 a1=[("لَا يُمْكِنُ تَحْقِيقُ التَّنْمِيَةِ الْمُسْتَدَامَةِ", "Sürdürülebilir kalkınmanın gerçekleştirilmesi mümkün değildir"),
     ("دُونَ مُشَارَكَةٍ فَاعِلَةٍ مِنَ الْمُجْتَمَعِ الْمَدَنِيِّ", "sivil toplumun etkin katılımı olmadan.")],
 a2=["Cümle bir zorunluluk / şart bildiriyor: لَا يُمْكِنُ ... دُونَ ... “... olmadan ... mümkün değildir”. Yani sivil toplumun katılımı olmazsa olmaz (gerekli) bir şarttır. Burada تَحْقِيقُ, يُمْكِنُ fiilinin fâilidir. Dikkat: cümle katılımın gerekli olduğunu söyler, tek başına yeterli olduğunu söylemez.",
     "E şıkkı aynı anlamı olumlu bir yapıyla verir: “Sivil toplumun etkin katılımı, sürdürülebilir kalkınmanın gerçekleşmesi için temel bir şart sayılır.” شَرْطًا أَسَاسِيًّا, تُعَدُّ fiilinin ikinci mef‘ûlü olarak mansuptur.",
     "A: وَحْدَهَا (tek başına) ve تَكْفِي (yeterlidir) ile “gerekli şart”ı “yeterli şart”a çevirir; en güçlü çeldirici budur. B: “Bazen katkı sağlar ama gerekli değildir” diyerek zorunluluğu ortadan kaldırır. C: Şart ile sonucun yerini değiştirir; aynı kelimeler kullanıldığı için dikkatli okunmalıdır. D: Sebep-sonucu ters çevirir ve “kamusal hayat” gibi yeni bir bilgi ekler.",
     "Doğru cevabımız E."]),

dict(n=50,
 stem="ما لبث المستثمرون أن تدفقوا على المنطقة من كل حدب وصوب بعد انتشار خبر اكتشاف النفط فيها.",
 opts=["أقبل المستثمرون على المنطقة من كل مكان بعد سنوات من انتشار خبر اكتشاف النفط فيها.",
       "انتشر خبر اكتشاف النفط في المنطقة بعد أن تدفق إليها المستثمرون من كل مكان.",
       "أقبل المستثمرون من كل مكان على المنطقة فور انتشار خبر اكتشاف النفط فيها.",
       "أقبل المستثمرون المحليون وحدهم على المنطقة فور انتشار خبر اكتشاف النفط فيها.",
       "كان من المتوقع أن يتدفق المستثمرون على المنطقة فور اكتشاف النفط فيها، لكنهم ترددوا."], ans="C",
 a1=[("مَا لَبِثَ الْمُسْتَثْمِرُونَ أَنْ تَدَفَّقُوا عَلَى الْمِنْطَقَةِ", "Çok geçmeden yatırımcılar bölgeye akın etti"),
     ("مِنْ كُلِّ حَدَبٍ وَصَوْبٍ", "dört bir yandan"),
     ("بَعْدَ انْتِشَارِ خَبَرِ اكْتِشَافِ النِّفْطِ فِيهَا", "bölgede petrol bulunduğu haberinin yayılmasından sonra.")],
 a2=["مَا لَبِثَ ... أَنْ ... yapısı “çok geçmeden / hemen ... yaptı” anlamındadır: bir olayın öncekinin hemen ardından gerçekleştiğini bildirir. مِنْ كُلِّ حَدَبٍ وَصَوْبٍ ise “her yerden, dört bir yandan” anlamında kalıplaşmış bir deyimdir. تَدَفَّقَ (aktı, akın etti) mecaz olarak kalabalığın hızla gelmesini anlatır.",
     "C şıkkı: فَوْرَ (hemen) = مَا لَبِثَ ... أَنْ; مِنْ كُلِّ مَكَانٍ = مِنْ كُلِّ حَدَبٍ وَصَوْبٍ; أَقْبَلَ عَلَى = تَدَفَّقَ عَلَى. Üç unsurun tamamı korunmuştur.",
     "A: Diğer bütün unsurları korur, ama “yıllar sonra” ifadesi مَا لَبِثَ'nin bildirdiği “hemen” anlamıyla çelişir. B: Olayların sırasını ters çevirir. D: “Yalnızca yerli yatırımcılar” diyerek “dört bir yandan” anlamını daraltır. E: Yatırımcıların tereddüt ettiğini söyler; asıl cümlenin tersidir.",
     "Doğru cevabımız C."]),

dict(n=51,
 stem="كان من الممكن تفادي الكارثة لو أن السلطات استجابت للتحذيرات في الوقت المناسب.",
 opts=["أدى تأخر السلطات في الاستجابة للتحذيرات إلى وقوع كارثة كان يمكن تجنبها.",
       "استجابت السلطات للتحذيرات في الوقت المناسب، ومع ذلك لم تتمكن من تفادي الكارثة.",
       "لم تكن الكارثة لتقع لو أن السلطات أطلقت التحذيرات في الوقت المناسب.",
       "ربما كان من الممكن تخفيف آثار الكارثة لو استجابت السلطات للتحذيرات بسرعة أكبر.",
       "لم تكن السلطات لتستجيب للتحذيرات حتى لو صدرت في الوقت المناسب."], ans="A",
 a1=[("كَانَ مِنَ الْمُمْكِنِ تَفَادِي الْكَارِثَةِ", "Felaketi önlemek mümkündü"),
     ("لَوْ أَنَّ السُّلُطَاتِ اسْتَجَابَتْ لِلتَّحْذِيرَاتِ فِي الْوَقْتِ الْمُنَاسِبِ", "eğer yetkililer uyarılara zamanında karşılık verseydi.")],
 a2=["لَوْ imtina bildirir: şart gerçekleşmediği için cevap da gerçekleşmemiştir. Yani uyarılar yapılmış, fakat yetkililer onlara zamanında karşılık vermemiş ve felaket önlenememiştir. Cümlede تَفَادِي, كَانَ'nin muahhar ismidir; مِنَ الْمُمْكِنِ ise mukaddem haberidir.",
     "A şıkkı bu örtük anlamı açık hâle getirir: “Yetkililerin uyarılara karşılık vermekte gecikmesi, önlenebilecek bir felaketin yaşanmasına yol açtı.” كَانَ يُمْكِنُ تَجَنُّبُهَا = كَانَ مِنَ الْمُمْكِنِ تَفَادِيهَا.",
     "B: Şartı gerçekleşmiş gibi gösterir. C: Yapıyı korur, ama işi değiştirir: asıl cümlede yetkililer uyarıları yayımlayan değil, uyarılara karşılık vermesi gereken taraftır. D: “Önlemek” yerine “etkilerini hafifletmek” der ve رُبَّمَا ile kesinliği azaltır. E: Yetkililerin hiçbir durumda karşılık vermeyeceğini söyleyerek yeni bir yargı ekler.",
     "Doğru cevabımız A."]),

dict(n=52,
 stem="لم يكن نجاح الفريق وليد الصدفة، بل ثمرة سنوات من العمل الدؤوب والتخطيط المحكم.",
 opts=["أسهمت الصدفة إلى جانب سنوات من العمل الدؤوب والتخطيط المحكم في نجاح الفريق.",
       "لم يحقق الفريق النجاح الذي خطط له رغم سنوات من العمل الدؤوب والتخطيط المحكم.",
       "كان نجاح الفريق ثمرة التخطيط المحكم أكثر منه ثمرة العمل الدؤوب طوال سنوات.",
       "لم يأت نجاح الفريق مصادفة، وإنما نتج عن سنوات من الجهد والتخطيط الدقيق.",
       "لم يكن الفريق يتوقع النجاح، لكنه جاء ثمرة لسنوات من العمل الدؤوب والتخطيط."], ans="D",
 a1=[("لَمْ يَكُنْ نَجَاحُ الْفَرِيقِ وَلِيدَ الصُّدْفَةِ", "Takımın başarısı tesadüfün ürünü değildi"),
     ("بَلْ ثَمَرَةَ سَنَوَاتٍ مِنَ الْعَمَلِ الدَّؤُوبِ وَالتَّخْطِيطِ الْمُحْكَمِ", "bilakis yıllarca süren azimli çalışmanın ve sağlam planlamanın meyvesiydi.")],
 a2=["لَمْ يَكُنْ ... بَلْ ... yapısında ilk kısım olumsuzlanıyor, ikinci kısım olumlanıyor. وَلِيدَ, يَكُنْ'nin haberi olarak mansuptur; ثَمَرَةَ ise بَلْ ile ona atfedilmiştir ve o da mansuptur. وَلِيدُ الصُّدْفَةِ “tesadüfün ürünü”, الْعَمَلُ الدَّؤُوبُ “yılmadan / azimle çalışma” demektir. Cümle iki unsuru (çalışma ve planlama) eşit olarak sayar ve tesadüfü tamamen dışlar.",
     "D şıkkı aynı olumsuz + olumlu yapıyı لَمْ يَأْتِ ... وَإِنَّمَا ... ile kurar: مُصَادَفَةً = وَلِيدَ الصُّدْفَةِ, الْجُهْدُ = الْعَمَلُ الدَّؤُوبُ, التَّخْطِيطُ الدَّقِيقُ = التَّخْطِيطُ الْمُحْكَمُ.",
     "A: Asıl cümlenin kelimelerini korur, ama tesadüfe de pay verir; oysa asıl cümle tesadüfü tamamen dışlar. B: Başarının gerçekleşmediğini söyler. C: İki unsuru eşit saymak yerine planlamayı çalışmaktan üstün tutar (أَكْثَرَ مِنْهُ). E: Takımın başarıyı beklemediği bilgisini ekler; bu bilgi asıl cümlede yoktur.",
     "Doğru cevabımız D."]),

dict(n=53,
 stem="قلما يعترف المرء بأخطائه حين يكون في موقع السلطة.",
 opts=["لا يعترف صاحب السلطة بأخطائه أبدا مهما كانت الظروف.",
       "نادرا ما يقر الإنسان بأخطائه عندما يكون صاحب سلطة.",
       "كثيرا ما يعترف المرء بأخطائه بعد أن يفقد موقعه في السلطة.",
       "يقل ارتكاب المرء للأخطاء حين يكون في موقع السلطة.",
       "نادرا ما يعترف المرء بأخطاء من هم في موقع السلطة."], ans="B",
 a1=[("قَلَّمَا يَعْتَرِفُ الْمَرْءُ بِأَخْطَائِهِ", "İnsan hatalarını nadiren itiraf eder"),
     ("حِينَ يَكُونُ فِي مَوْقِعِ السُّلْطَةِ", "iktidar / yetki konumundayken.")],
 a2=["قَلَّمَا, قَلَّ fiiline كَافَّة olan مَا eklenerek oluşmuş bir kalıptır ve “nadiren, pek az” anlamı verir; ardından fiil cümlesi gelir. “Nadiren” ile “hiçbir zaman” arasındaki derece farkı bu sorunun kilit noktasıdır.",
     "B şıkkı: نَادِرًا مَا = قَلَّمَا; يُقِرُّ بِـ = يَعْتَرِفُ بِـ; صَاحِبُ سُلْطَةٍ = فِي مَوْقِعِ السُّلْطَةِ. Anlam birebir korunmuştur.",
     "A: “Nadiren”i “asla” (أَبَدًا) hâline getirerek dereceyi değiştirir. C: “Yetkiyi kaybettikten sonra sıkça itiraf eder” diyerek asıl cümlede olmayan yeni bir bilgi ekler. D: “İtiraf etmek” yerine “hata yapmak”tan söz eder. E: نَادِرًا مَا yapısını korur, ama itiraf edilen hataları başkalarına (yetki sahiplerine) ait kılar; nesne değişmiştir.",
     "Doğru cevabımız B."]),
]

SECTIONS.append(dict(
    rng=(54, 58),
    title="DURUMA UYGUN İFADE (Situational Expressions)",
    instr="54.-58. sorularda, verilen durumda söylenmiş olabilecek sözü bulunuz.",
    skill="Bu bölüm; bir iletişim durumunda konuşmacının amacına (özür dileme, uyarma, reddetme, teşekkür, eleştiri) ve üslup şartına (nazik, kararlı, cesaretlendirici) uygun ifadeyi seçebilme becerisini ölçer.",
    strategy="Durum metnindeki fiil ve hâl ifadelerini (مُعْتَذِرًا، بِلُطْفٍ، بِحَزْمٍ، دُونَ أَنْ ...) mutlaka işaretleyin; bunlar cevabın tüm şartlarını verir. Doğru şık, durumun istediği bütün unsurları (ör. hem teşekkür hem özür hem öneri) aynı anda karşılayan şıktır.",
))

Q += [
dict(n=54,
 stem="قدم زميلك في العمل عرضا متميزا أمام الإدارة، لكنه نسي الإشارة إلى مساهمة أحد أعضاء الفريق. تريد أن تنبهه إلى ذلك بلطف دون أن تقلل من شأن عرضه، فتقول:",
 opts=["عرضك كان رائعا، لكن من الإنصاف أن نذكر في المرة القادمة جهد سامي في إعداد البيانات.",
       "كان عرضك رائعا، لكنك تجاهلت جهود سامي عمدا لتنسب النجاح كله إلى نفسك أمام الإدارة.",
       "لقد نسيت أن تشير إلى جهد سامي في إعداد البيانات، ولذلك لم يكن عرضك مقنعا على الإطلاق.",
       "كان عرضك رائعا حقا، وقد أعجب الإدارة كثيرا، فأرجو أن تقدم العرض القادم أيضا.",
       "أظن أن سامي منزعج منك كثيرا، فمن الأفضل أن تعتذر إليه قبل أن يشكوك إلى الإدارة."], ans="A",
 a1=[("تُرِيدُ أَنْ تُنَبِّهَهُ إِلَى ذَلِكَ بِلُطْفٍ", "Onu bu konuda nazikçe uyarmak istiyorsun"),
     ("دُونَ أَنْ تُقَلِّلَ مِنْ شَأْنِ عَرْضِهِ", "sunumunun değerini küçümsemeden.")],
 a2=["Durumun istediği üç şart var: (1) arkadaşı bir eksiklik konusunda uyarmak (تُنَبِّهَهُ), (2) bunu nazikçe yapmak (بِلُطْفٍ), (3) sunumunu küçümsememek (دُونَ أَنْ تُقَلِّلَ مِنْ شَأْنِ عَرْضِهِ). Bu tür sorularda şıkların çoğu şartlardan bir kısmını karşılar; doğru şık hepsini birlikte karşılayandır.",
     "A şıkkı önce sunumu över (عَرْضُكَ كَانَ رَائِعًا), sonra مِنَ الْإِنْصَافِ (adil olur) gibi yumuşak bir ifadeyle ekip arkadaşının katkısını hatırlatır. Üç şartın hepsi karşılanmıştır.",
     "B: Sunumu över ve uyarır, ama arkadaşını kasıtlı davranmakla suçladığı için nezaket şartını ihlal eder. C: Uyarır, ama sunumu küçümser. D: Sunumu över ve nazik bir dil kullanır, ancak eksiklik konusunda hiçbir uyarı içermez. E: Övgü içermez ve tehdit havası taşır.",
     "Doğru cevabımız A."]),

dict(n=55,
 stem="أنت مدير مدرسة، ولاحظت أن أحد المعلمين المتميزين يبدو مرهقا في الآونة الأخيرة وقد تراجع أداؤه. تريد أن تستفسر عن حاله وتعرض عليه المساعدة، فتقول:",
 opts=["لاحظت أن أداءك تراجع مؤخرا، وإذا استمر ذلك فسأضطر إلى رفع تقرير إلى الوزارة.",
       "أنت من أفضل معلمينا، لذا أرجو أن تبذل جهدا أكبر في إعداد دروسك كما كنت تفعل.",
       "هل أنت مريض؟ إن كان الأمر كذلك فيمكنك أن تبحث عن عمل أخف من التدريس في مدرسة أخرى.",
       "تبدو مرهقا في الأيام الأخيرة، فهل هناك ما يشغلك؟ إن احتجت إلى أي مساعدة فأنا هنا.",
       "لاحظت أنك تبدو مرهقا، ولا شك أن المعلمين جميعا يمرون بمثل هذه الفترات، فلا تقلق."], ans="D",
 a1=[("تُرِيدُ أَنْ تَسْتَفْسِرَ عَنْ حَالِهِ", "Onun hâlini sormak istiyorsun"),
     ("وَتَعْرِضَ عَلَيْهِ الْمُسَاعَدَةَ", "ve ona yardım teklif etmek.")],
 a2=["Durum iki işlev istiyor: hâl hatır sormak (تَسْتَفْسِرَ عَنْ حَالِهِ) ve yardım teklif etmek (تَعْرِضَ عَلَيْهِ الْمُسَاعَدَةَ). Ayrıca öğretmenin “seçkin” (مُتَمَيِّز) olduğu belirtilerek destekleyici bir tutum beklendiği sezdiriliyor.",
     "D şıkkı hem soru sorar (فَهَلْ هُنَاكَ مَا يَشْغَلُكَ؟) hem de yardım teklif eder (إِنِ احْتَجْتَ إِلَى أَيِّ مُسَاعَدَةٍ فَأَنَا هُنَا). فَأَنَا'daki فَـ, şartın cevabı isim cümlesi olduğu için gelmiştir.",
     "A: Hâl sormaz ve tehdit içerir. B: Öğretmeni över, ama hâlini sormaz ve yardım teklif etmez; yalnızca daha çok çalışmasını ister. C: Bir soru sorar, ama yardım teklif etmek yerine öğretmeni okuldan uzaklaştırmaya yöneliktir. E: Yorgunluğu fark ettiğini söyler ve teselli eder, ama ne hâlini sorar ne de yardım teklif eder; en güçlü çeldirici budur.",
     "Doğru cevabımız D."]),

dict(n=56,
 stem="دعاك جارك الجديد إلى تناول العشاء في منزله، لكنك مرتبط بموعد سابق في المساء نفسه. تريد أن تشكره وتعتذر، وتقترح موعدا آخر، فتقول:",
 opts=["شكرا جزيلا على دعوتك الكريمة، لكنني لا أحب تناول العشاء خارج منزلي في العادة.",
       "أعتذر لأن لدي موعدا سابقا هذا المساء، لكنني سأحاول الحضور إن انتهيت منه مبكرا.",
       "أشكرك على دعوتك الكريمة، لكن لدي موعد سابق هذا المساء، فهل يناسبك أن نلتقي يوما آخر؟",
       "أشكرك على الدعوة، وسأحضر بكل سرور، فأنا أحب التعرف إلى جيراني الجدد.",
       "لدي موعد سابق هذا المساء، فلماذا لا تدعوني في يوم آخر يناسبني أكثر؟"], ans="C",
 a1=[("تُرِيدُ أَنْ تَشْكُرَهُ وَتَعْتَذِرَ", "Ona teşekkür edip özür dilemek"),
     ("وَتَقْتَرِحَ مَوْعِدًا آخَرَ", "ve başka bir zaman önermek istiyorsun.")],
 a2=["Durum üç unsur istiyor: teşekkür, özür (gerekçesiyle) ve başka bir zaman önerisi. Bu tür sorularda doğru şık, istenen unsurların tamamını içeren şıktır.",
     "C şıkkı: أَشْكُرُكَ عَلَى دَعْوَتِكَ الْكَرِيمَةِ (teşekkür), لَكِنْ لَدَيَّ مَوْعِدٌ سَابِقٌ (gerekçeli özür), فَهَلْ يُنَاسِبُكَ أَنْ نَلْتَقِيَ يَوْمًا آخَرَ (yeni zaman önerisi). Üç unsurun hepsi vardır.",
     "A: Teşekkür eder, ama gerçek sebebi (önceki randevu) söylemez, kırıcı bir gerekçe sunar ve yeni zaman önermez. B: Gerekçeli bir özür diler, ama teşekkür etmez ve yeni zaman yerine belirsiz bir “gelmeye çalışırım” der. D: Daveti kabul eder; önceki randevuyla çelişir. E: Başka bir gün önerir, ama teşekkür etmez ve kaba bir üslupla daveti karşı tarafa yükler.",
     "Doğru cevabımız C."]),

dict(n=57,
 stem="تعمل مرشدا سياحيا، وقد طلب منك أحد السياح الدخول إلى منطقة أثرية محظورة لالتقاط بعض الصور. تريد أن ترفض طلبه بأدب وتوضح له السبب، فتقول:",
 opts=["يمكنك الدخول بسرعة لالتقاط بعض الصور ما دام الحراس غير موجودين في هذه اللحظة.",
       "لا أعرف إن كان الدخول إلى هذه المنطقة مسموحا أم لا، فافعل ما تراه مناسبا يا سيدي.",
       "عذرا يا سيدي، لا أستطيع السماح لك بالدخول، فهذه هي التعليمات، ولا أعرف سببها.",
       "إذا دخلت هذه المنطقة فلن أكون مسؤولا عنك بعد الآن، ولن أسمح لك بالعودة إلى المجموعة.",
       "أعتذر يا سيدي، فالدخول إلى هنا ممنوع حفاظا على الآثار، لكن يمكنك التصوير من المنصة القريبة."], ans="E",
 a1=[("تُرِيدُ أَنْ تَرْفُضَ طَلَبَهُ بِأَدَبٍ", "Onun isteğini kibarca reddetmek"),
     ("وَتُوَضِّحَ لَهُ السَّبَبَ", "ve ona sebebini açıklamak istiyorsun.")],
 a2=["Durumun şartları: isteği reddetmek, bunu kibarca (بِأَدَبٍ) yapmak ve sebebini açıklamak (تُوَضِّحَ لَهُ السَّبَبَ).",
     "E şıkkı nazik bir girişle (أَعْتَذِرُ يَا سَيِّدِي) reddi bildirir, sebebi açıklar (حِفَاظًا عَلَى الْآثَارِ; burada حِفَاظًا mef‘ûlün lehtir) ve üstelik bir alternatif sunar. Bu şık, rehberlik mesleğinin gerektirdiği üsluba da uygundur.",
     "A: Yasağı çiğnemeye teşvik eder; reddetmez. B: Sorumluluktan kaçar ve reddetmez. C: Kibarca reddeder, ama sebebi açıklamaz (وَلَا أَعْرِفُ سَبَبَهَا); en güçlü çeldirici budur. D: Tehdit içeren, kaba bir ifadedir ve gerçek sebebi söylemez.",
     "Doğru cevabımız E."]),

dict(n=58,
 stem="طلب منك صديقك أن تقرأ مقالا كتبه قبل نشره، فوجدت فيه أفكارا جيدة، لكن بعض فقراته تحتاج إلى تنظيم. تريد أن تبدي رأيك بصراحة ولكن بطريقة مشجعة، فتقول:",
 opts=["المقال ممتاز، وأفكاره قيمة جدا، ولا يحتاج إلى أي تعديل، فيمكنك نشره فورا.",
       "أفكار مقالك قيمة، ولو أعدت ترتيب بعض الفقرات لأصبح أكثر ترابطا ووضوحا.",
       "بصراحة، فقرات المقال غير منظمة، ومن الأفضل ألا تنشره قبل أن تعيد كتابته كاملا.",
       "لا أملك الوقت الكافي لقراءة المقال الآن، فأرجو أن ترسله إلى صديق آخر يقرؤه.",
       "أرى أن موضوع المقال لا يناسب القراء، فالأفضل أن تكتب في موضوع مختلف تماما."], ans="B",
 a1=[("تُرِيدُ أَنْ تُبْدِيَ رَأْيَكَ بِصَرَاحَةٍ", "Görüşünü açıkça bildirmek istiyorsun"),
     ("وَلَكِنْ بِطَرِيقَةٍ مُشَجِّعَةٍ", "ama cesaretlendirici bir şekilde.")],
 a2=["İki şart bir arada isteniyor: dürüstlük / açıklık (بِصَرَاحَةٍ) ve cesaretlendirme (بِطَرِيقَةٍ مُشَجِّعَةٍ). Durum metni ayrıca yazının iyi yanını (fikirler) ve eksik yanını (paragrafların düzeni) açıkça veriyor.",
     "B şıkkı önce fikirleri takdir eder, sonra eksikliği bir öneri olarak sunar: لَوْ أَعَدْتَ تَرْتِيبَ بَعْضِ الْفِقْرَاتِ لَأَصْبَحَ أَكْثَرَ تَرَابُطًا. Burada لَوْ şart, لَأَصْبَحَ ise لَامُ الْجَوَابِ ile gelen cevaptır.",
     "A: Cesaretlendiricidir, ama eksikliği gizlediği için açıklık şartını ihlal eder. C: Açık sözlüdür (بِصَرَاحَةٍ ile başlar), ama cesaret kırıcıdır ve fikirlerin iyi olduğunu hiç söylemez. D: Görüş bildirmez. E: Yazıyı tümden reddeder; üstelik durumda sorun konunun kendisi değil, paragrafların düzenidir.",
     "Doğru cevabımız B."]),
]

SECTIONS.append(dict(
    rng=(59, 63),
    title="PARAGRAF TAMAMLAMA",
    instr="59.-63. sorularda, boş bırakılan yere, parçada anlam bütünlüğünü sağlamak için getirilebilecek cümleyi bulunuz.",
    skill="Bu bölüm; paragrafın düşünce akışını, cümleler arasındaki geçişleri (ekleme, zıtlık, sebep-sonuç, örnekleme) ve zamir / işaret ismi göndermelerini takip edebilme becerisini ölçer.",
    strategy="Boşluktan önceki cümlenin söylediğini ve boşluktan sonraki cümlenin neyle başladığını (وَلِذَلِكَ، فَعِنْدَمَا، ثُمَّ، وَبِذَلِكَ gibi) birlikte düşünün; doğru cümle ikisi arasında köprü kurmalıdır. Kendi başına doğru bilgi veren ama sonraki cümleyi hazırlamayan şıkları eleyin.",
))

Q += [
dict(n=59,
 stem="يعد التسويف من أكثر العادات انتشارا بين الطلاب والموظفين على حد سواء. ويخلط كثيرون بينه وبين الكسل، مع أن بينهما فرقا واضحا. ----. ولذلك ينصح المختصون بتقسيم المهام الكبيرة إلى خطوات صغيرة ومحددة، مما يخفف الشعور بالرهبة منها ويشجع على البدء فيها.",
 opts=["فالكسل يصيب الإنسان في جميع جوانب حياته، أما التسويف فيقتصر على المهام الدراسية.",
       "ويرى بعض الباحثين أن التسويف لا يؤثر في مستوى الأداء على الإطلاق.",
       "ولا يعاني الموظفون عادة من التسويف بقدر ما يعاني منه الطلاب.",
       "فالمسوف يرغب في إنجاز عمله، لكنه يؤجله هربا من القلق أو الخوف من الفشل.",
       "ومن ثم فإن التسويف عادة يصعب التغلب عليها مهما بذل المرء من جهد في مقاومتها."], ans="D",
 a1=[("وَيَخْلِطُ كَثِيرُونَ بَيْنَهُ وَبَيْنَ الْكَسَلِ، مَعَ أَنَّ بَيْنَهُمَا فَرْقًا وَاضِحًا", "Pek çok kişi onu tembellikle karıştırır, oysa aralarında açık bir fark vardır."),
     ("وَلِذَلِكَ يَنْصَحُ الْمُخْتَصُّونَ بِتَقْسِيمِ الْمَهَامِّ الْكَبِيرَةِ", "Bu nedenle uzmanlar büyük görevleri bölmeyi tavsiye eder"),
     ("مِمَّا يُخَفِّفُ الشُّعُورَ بِالرَّهْبَةِ مِنْهَا", "bu da onlara karşı duyulan korku hissini azaltır.")],
 a2=["Boşluktan önceki cümle erteleme (التَّسْوِيف) ile tembellik arasında “açık bir fark” olduğunu söylüyor; boşluğa gelecek cümlenin bu farkı açıklaması beklenir. Boşluktan sonraki cümle ise وَلِذَلِكَ ile başlıyor ve çözümün “korku hissini azaltmak” olduğunu söylüyor; demek ki boşluktaki cümle ertelemenin sebebini kaygı / korkuya bağlamalıdır.",
     "D şıkkı her iki bağlantıyı da kurar: erteleyen kişi işi yapmak ister (tembelden farkı budur), fakat kaygıdan ve başarısızlık korkusundan kaçmak için erteler. Başındaki فَـ açıklama bildirir. هَرَبًا مِنْ mef‘ûlün lehtir.",
     "A: Tembellik ile erteleme arasında bir fark ortaya koyar, bu yüzden ilk bakışta boşluğa uyuyor gibi görünür; ama ertelemeyi yalnızca ders görevleriyle sınırlar ve bu, ilk cümledeki “öğrenciler ve çalışanlar arasında” ifadesiyle çelişir. Ayrıca korkudan söz etmediği için sonraki cümledeki “korku hissini azaltmak” önerisini hazırlamaz; en güçlü çeldirici budur. B: Ertelemenin performansı etkilemediğini söylemek hem konuyla hem de sonraki öneriyle çelişir. C: Öğrenci-çalışan karşılaştırması, “fark” vurgusunu ve sonraki çözümü desteklemez. E: “Üstesinden gelmek zor, ne kadar çaba harcansa da” ifadesi, uzmanların pratik bir çözüm önermesiyle çelişir.",
     "Doğru cevabımız D."]),

dict(n=60,
 stem="تعد الشعاب المرجانية من أغنى النظم البيئية البحرية بالتنوع الحيوي، إذ تأوي ما يقارب ربع الأنواع البحرية المعروفة رغم أنها لا تغطي سوى جزء ضئيل من قاع المحيطات. ----. فعندما ترتفع حرارة المياه، تطرد المرجانيات الطحالب التي تعيش في أنسجتها وتمدها بالغذاء، فتفقد ألوانها وتصبح عرضة للموت، وهي الظاهرة المعروفة بابيضاض المرجان.",
 opts=["غير أن هذه الشعاب باتت مهددة على نحو متزايد بفعل ارتفاع درجات حرارة المحيطات.",
       "وتتميز الشعاب المرجانية بقدرتها الفائقة على التكيف مع أي ارتفاع في درجات حرارة المياه.",
       "ويستفيد الصيادون من الشعاب المرجانية في توفير مصدر رزق دائم لهم.",
       "وتنتشر الشعاب المرجانية في المياه الباردة والعميقة أكثر من المياه الدافئة.",
       "ولذلك تعد الطحالب البحرية أخطر الكائنات على حياة المرجانيات."], ans="A",
 a1=[("تَأْوِي مَا يُقَارِبُ رُبْعَ الْأَنْوَاعِ الْبَحْرِيَّةِ الْمَعْرُوفَةِ", "Bilinen deniz türlerinin yaklaşık dörtte birine ev sahipliği yapar"),
     ("فَعِنْدَمَا تَرْتَفِعُ حَرَارَةُ الْمِيَاهِ، تَطْرُدُ الْمَرْجَانِيَّاتُ الطَّحَالِبَ", "Suyun sıcaklığı yükseldiğinde mercanlar yosunları dışarı atar"),
     ("وَهِيَ الظَّاهِرَةُ الْمَعْرُوفَةُ بِابْيِضَاضِ الْمَرْجَانِ", "ki bu, mercan beyazlaması olarak bilinen olgudur.")],
 a2=["Boşluktan önce mercan resiflerinin biyolojik çeşitlilik bakımından zenginliği anlatılıyor (olumlu). Boşluktan sonra فَعِنْدَمَا ile sıcaklık artışının mercanları nasıl öldürdüğü açıklanıyor (olumsuz). Demek ki boşlukta hem yön değiştiren (zıtlık) hem de “sıcaklık tehdidini” ilk kez gündeme getiren bir cümle olmalıdır; sonraki cümle onu açıklayacaktır.",
     "A şıkkı غَيْرَ أَنَّ ile yönü değiştirir ve “okyanus sıcaklıklarının artması nedeniyle giderek artan tehdit” bilgisini verir. Sonraki cümlenin başındaki فَـ, bu tehdidin nasıl işlediğini açıklar. بَاتَتْ, كَانَ'nin kardeşlerindendir ve “...hâle geldi” anlamındadır.",
     "B: Sıcaklığa uyum sağlayabildikleri iddiası, sonraki cümlede anlatılan ölümle çelişir. C: Balıkçılar konusu akışı keser. D: Soğuk sular bilgisi sonraki cümleyi hazırlamaz. E: Metne göre yosunlar mercanları besler; onları en tehlikeli canlı olarak göstermek yanlıştır.",
     "Doğru cevabımız A."]),

dict(n=61,
 stem="شهدت صناعة الساعات تحولات كبيرة عبر التاريخ. فقد اعتمد الإنسان في البداية على الساعات الشمسية التي تحدد الوقت بحسب موقع الظل. ----. ثم جاءت الساعات الميكانيكية في أوروبا في العصور الوسطى لتمثل نقلة نوعية في دقة قياس الوقت.",
 opts=["وتعد الساعات الذكية اليوم من أكثر الأجهزة الإلكترونية مبيعا.",
       "ولذلك ظلت الساعات الشمسية الوسيلة الوحيدة لقياس الوقت في جميع الحضارات حتى العصر الحديث.",
       "لكنها لم تكن تجدي ليلا أو في الأيام الغائمة، فظهرت الساعات المائية لتجاوز ذلك.",
       "وقد صنعت الساعات الشمسية الأولى من المعادن الثمينة كالذهب والفضة.",
       "وكان الناس يعتمدون على الساعات المائية قبل اختراع الساعات الشمسية."], ans="C",
 a1=[("فَقَدِ اعْتَمَدَ الْإِنْسَانُ فِي الْبِدَايَةِ عَلَى السَّاعَاتِ الشَّمْسِيَّةِ", "İnsan başlangıçta güneş saatlerine dayandı"),
     ("ثُمَّ جَاءَتِ السَّاعَاتُ الْمِيكَانِيكِيَّةُ", "sonra mekanik saatler geldi.")],
 a2=["Paragraf kronolojik bir sıra izliyor: فِي الْبِدَايَةِ (başlangıçta) → boşluk → ثُمَّ (sonra). Demek ki boşlukta güneş saatinden sonra, mekanik saatten önce gelen bir aşama bulunmalıdır.",
     "C şıkkı, güneş saatlerinin eksikliğini (gece ve bulutlu günlerde işe yaramamaları) belirterek bir sonraki aşamayı (su saatleri) gerekçesiyle tanıtır. Böylece ثُمَّ ile gelen mekanik saatler doğal olarak üçüncü aşama olur. لِتَجَاوُزِ ... “aşmak için” amaç bildirir.",
     "A: Akıllı saatler kronolojik sırayı bozar. B: “Modern çağa kadar tek araç” ifadesi, mekanik saatlerin Orta Çağ'da geldiği bilgisiyle çelişir. D: Bir ayrıntı verir ama akışı ilerletmez. E: Su saatlerini güneş saatlerinden önceye koyarak فِي الْبِدَايَةِ ifadesiyle çelişir.",
     "Doğru cevabımız C."]),

dict(n=62,
 stem="يميل كثير من الناس إلى الاعتقاد بأن الذاكرة البشرية تعمل مثل آلة تصوير تسجل الأحداث كما وقعت تماما. لكن أبحاث علم النفس تبين أن الأمر على خلاف ذلك. ----. ولهذا السبب قد يروي شاهدان الحادثة نفسها بطريقتين مختلفتين، وكلاهما مقتنع تماما بصحة روايته.",
 opts=["فالذاكرة تحتفظ بجميع التفاصيل بدقة مهما طال الزمن.",
       "ويستطيع الإنسان أن يتذكر أحداث طفولته المبكرة بوضوح تام.",
       "وتقل قدرة الإنسان على التذكر كلما تقدم في السن.",
       "ولذلك يعتمد القضاة في المحاكم على شهادة الشهود بوصفها دليلا قاطعا لا يقبل الشك.",
       "إذ إن الدماغ يعيد بناء الذكرى كلما استدعيناها، متأثرا بمعارفنا وتوقعاتنا."], ans="E",
 a1=[("لَكِنَّ أَبْحَاثَ عِلْمِ النَّفْسِ تُبَيِّنُ أَنَّ الْأَمْرَ عَلَى خِلَافِ ذَلِكَ", "Ancak psikoloji araştırmaları durumun bunun tersi olduğunu gösteriyor."),
     ("وَلِهَذَا السَّبَبِ قَدْ يَرْوِي شَاهِدَانِ الْحَادِثَةَ نَفْسَهَا بِطَرِيقَتَيْنِ مُخْتَلِفَتَيْنِ", "Bu nedenle iki tanık aynı olayı iki farklı şekilde anlatabilir.")],
 a2=["Boşluktan önce “belleğin fotoğraf makinesi gibi çalıştığı” görüşünün yanlış olduğu söyleniyor; boşluktaki cümle bunun gerekçesini vermelidir. Boşluktan sonra ise وَلِهَذَا السَّبَبِ ile bir sonuç geliyor: iki tanık aynı olayı farklı anlatabilir. Demek ki boşlukta, anıların değişebildiğini gösteren bir sebep bulunmalıdır.",
     "E şıkkı إِذْ إِنَّ (çünkü) ile gerekçe verir: beyin, anıyı her hatırlayışta bilgilerimizden ve beklentilerimizden etkilenerek yeniden inşa eder. مُتَأَثِّرًا hâl olarak mansuptur. Bu açıklama tanıkların farklı anlatımlarını doğrudan açıklar.",
     "A: Belleğin her ayrıntıyı koruduğunu söyleyerek “fotoğraf makinesi” görüşünü destekler; önceki cümleyle çelişir. B: Aynı şekilde kusursuz bellek fikrini destekler. C: Yaşla ilgili bilgi, iki tanığın farklı anlatımını açıklamaz. D: Hâkimlerin tanıklığı kesin delil sayması, belleğin yeniden inşa edildiği fikriyle çelişir ve وَلِهَذَا السَّبَبِ ile gelen sonucu hazırlamaz.",
     "Doğru cevabımız E."]),

dict(n=63,
 stem="تعد الترجمة جسرا تعبر عليه المعارف والثقافات من أمة إلى أخرى. وقد شهدت بغداد في العصر العباسي حركة ترجمة واسعة، نقلت خلالها أمهات الكتب اليونانية والفارسية والهندية إلى العربية. ----. وبذلك أسهمت هذه الحركة في نشوء نهضة علمية واسعة شملت الطب والفلك والرياضيات والفلسفة.",
 opts=["وقد توقفت حركة الترجمة فجأة بعد ذلك بسبب قلة اهتمام الخلفاء العباسيين بها وبالعلوم.",
       "ولم يكتف العلماء العرب بنقل هذه المؤلفات، بل شرحوها ونقدوها وأضافوا إليها الكثير.",
       "واقتصرت الترجمة في تلك المرحلة على الكتب الأدبية والشعرية دون الكتب العلمية والفلسفية.",
       "ويعد تعلم اللغات الأجنبية اليوم ضرورة لكل باحث.",
       "ولم تترك هذه الكتب المترجمة أي أثر في الحياة الفكرية آنذاك."], ans="B",
 a1=[("نُقِلَتْ خِلَالَهَا أُمَّهَاتُ الْكُتُبِ الْيُونَانِيَّةِ وَالْفَارِسِيَّةِ وَالْهِنْدِيَّةِ إِلَى الْعَرَبِيَّةِ", "bu süreçte Yunan, Fars ve Hint temel eserleri Arapçaya aktarıldı"),
     ("وَبِذَلِكَ أَسْهَمَتْ هَذِهِ الْحَرَكَةُ فِي نُشُوءِ نَهْضَةٍ عِلْمِيَّةٍ وَاسِعَةٍ", "Böylece bu hareket geniş bir bilimsel uyanışın doğmasına katkıda bulundu.")],
 a2=["Boşluktan sonraki cümle وَبِذَلِكَ (böylece) ile başlıyor ve çevirinin tıp, astronomi, matematik ve felsefeyi kapsayan geniş bir bilimsel uyanışa yol açtığını söylüyor. Boşluktaki cümlenin, çeviriyi salt aktarımdan öteye taşıyarak bu uyanışı açıklaması gerekir.",
     "B şıkkı لَمْ يَكْتَفِ ... بَلْ ... yapısıyla Arap bilginlerinin eserleri sadece aktarmakla yetinmeyip şerh ettiklerini, eleştirdiklerini ve onlara katkı yaptıklarını söyler. Bu da “geniş bilimsel uyanış” sonucunu doğrudan hazırlar. يَكْتَفِ, لَمْ ile meczum olduğu için sonundaki illet harfi düşmüştür.",
     "A: Hareketin aniden durması, “uyanışa katkıda bulundu” sonucuyla çelişir. C: Sadece edebî eserlerle sınırlı olması, tıp ve astronomi gibi alanlardaki uyanışı açıklamaz; ayrıca “Yunan, Fars, Hint temel eserleri” ifadesiyle de uyumsuzdur. D: Günümüze sıçrayarak akışı bozar. E: “Hiçbir etki bırakmadı” ifadesi sonuç cümlesiyle doğrudan çelişir.",
     "Doğru cevabımız B."]),
]
