# -*- coding: utf-8 -*-
# Sorular 29-43 (Okuma)

INTRO = dict(
    rng=(29, 43),
    title="OKUDUĞUNU ANLAMA (Paragraf Soruları)",
    instr="29.-43. sorular beş ayrı parçaya dayanmaktadır; her parçayı okuyup ilgili üç soruyu cevaplayınız.",
    skill="Bu bölüm; akademik bir metnin ana fikrini, açıkça verilen bilgileri, bir kavramın metindeki tanımını ve metinden çıkarılabilecek yargıları ayırt edebilme becerisini ölçer.",
    strategy="Metni ilk okumada tamamen çevirmeye çalışmayın; konu cümlesini, yön değiştiren bağlaçları (غَيْرَ أَنَّ، وَمَعَ ذَلِكَ، بَلْ) ve örnek / sonuç bildiren ifadeleri işaretleyin. وَفْقًا لِلنَّصِّ ile başlayan sorularda cevabı metindeki ilgili cümlede arayın; يُسْتَنْتَجُ / يُفْهَمُ ile başlayan çıkarım sorularında metnin söylediğini aşan (جَمِيعُ، دَائِمًا، وَحْدَهُ gibi) mutlak ifadeler içeren şıklara karşı dikkatli olun.",
)

PASSAGES = []

PASSAGES.append(dict(
 rng=(29, 31),
 text="تعرف ظاهرة الجزر الحرارية الحضرية بأنها ارتفاع درجات الحرارة في المدن الكبرى مقارنة بالمناطق الريفية المحيطة بها، وقد يصل الفرق بينهما في بعض الليالي إلى عدة درجات مئوية. ويرجع ذلك أساسا إلى أن الأسطح الإسمنتية والإسفلتية تمتص أشعة الشمس خلال النهار ثم تطلق حرارتها ببطء بعد الغروب، في حين تسهم النباتات في المناطق الريفية في تلطيف الجو من خلال عملية النتح والظل الذي توفره. ويزيد من حدة هذه الظاهرة تراكم الحرارة الناتجة عن المصانع والمركبات وأجهزة التكييف، فضلا عن تقارب المباني الشاهقة الذي يحد من حركة الرياح. ولا تقتصر آثار الجزر الحرارية على الشعور بعدم الارتياح، بل تمتد إلى زيادة استهلاك الطاقة وارتفاع معدلات الإصابة بالأمراض المرتبطة بالحر، ولا سيما لدى كبار السن. ولمواجهة ذلك، يقترح المخططون العمرانيون التوسع في المساحات الخضراء واستخدام مواد بناء فاتحة اللون تعكس جزءا أكبر من أشعة الشمس.",
 read=["Metnin ilk cümlesi konuyu tanımlıyor: الْجُزُرُ الْحَرَارِيَّةُ الْحَضَرِيَّةُ (kentsel ısı adaları), yani büyük şehirlerin çevrelerindeki kırsal alanlardan daha sıcak olması.",
       "وَيَرْجِعُ ذَلِكَ أَسَاسًا إِلَى ... ifadesiyle sebep bölümü başlıyor: beton ve asfalt yüzeyler gündüz güneşi emip ısıyı gün batımından sonra yavaşça bırakıyor. فِي حِينِ (oysa) ile kırsal alandaki bitkilerin serinletici etkisi karşılaştırılıyor.",
       "وَيَزِيدُ مِنْ حِدَّةِ ... ile ek sebepler (fabrikalar, araçlar, klimalar, rüzgârı engelleyen yüksek binalar), لَا تَقْتَصِرُ ... بَلْ تَمْتَدُّ ile sonuçlar (enerji tüketimi, sıcağa bağlı hastalıklar), وَلِمُوَاجَهَةِ ذَلِكَ ile de çözüm önerileri (yeşil alanlar, açık renkli malzemeler) veriliyor.",
       "Metnin yapısı: tanım → sebepler → sonuçlar → çözümler."],
))
PASSAGES.append(dict(
 rng=(32, 34),
 text="يعد الحسن بن الهيثم، الذي عاش بين القرنين العاشر والحادي عشر الميلاديين، من أبرز العلماء الذين أسهموا في تأسيس المنهج التجريبي. فقد رفض الاكتفاء بما ورثه من آراء العلماء السابقين في تفسير الرؤية، ولا سيما النظرية التي كانت تزعم أن العين تبعث أشعة نحو الأجسام فتدركها. وبدلا من ذلك، أجرى تجارب دقيقة على الضوء وانعكاسه وانكساره، وانتهى إلى أن الرؤية تحدث عندما ينعكس الضوء عن الأجسام ويدخل العين. وقد دون نتائجه في كتابه \"المناظر\" الذي ترجم إلى اللاتينية وظل مرجعا للعلماء الأوروبيين عدة قرون. ولم تكن قيمة إسهامه في النتائج التي توصل إليها فحسب، بل في إصراره على إخضاع كل فرضية للتجربة والملاحظة قبل التسليم بصحتها، وهو ما يعد اليوم من ركائز البحث العلمي الحديث.",
 read=["İlk cümle konuyu veriyor: İbnü’l-Heysem, deneysel yöntemin kurulmasına katkıda bulunan en önemli bilginlerden biridir.",
       "فَقَدْ رَفَضَ الِاكْتِفَاءَ بِمَا وَرِثَهُ ... cümlesi onun önceki görüşleri, özellikle “gözün cisimlere ışın gönderdiği” teorisini sorgusuz kabul etmediğini söylüyor. وَبَدَلًا مِنْ ذَلِكَ ile deneyleri ve vardığı sonuç (görmenin, cisimlerden yansıyan ışığın göze girmesiyle gerçekleştiği) anlatılıyor.",
       "Son cümle metnin ağırlık merkezidir: لَمْ تَكُنْ قِيمَةُ إِسْهَامِهِ فِي النَّتَائِجِ ... فَحَسْبُ، بَلْ فِي إِصْرَارِهِ عَلَى إِخْضَاعِ كُلِّ فَرَضِيَّةٍ لِلتَّجْرِبَةِ وَالْمُلَاحَظَةِ. Yani katkısının değeri sadece sonuçlarında değil, yöntemindedir."],
))
PASSAGES.append(dict(
 rng=(35, 37),
 text="يقوم النموذج الاقتصادي التقليدي على تسلسل خطي يبدأ باستخراج المواد الخام، ثم تصنيعها واستهلاكها، وينتهي بالتخلص منها بوصفها نفايات. وقد أدى هذا النموذج، مع تزايد عدد السكان وارتفاع معدلات الاستهلاك، إلى استنزاف الموارد الطبيعية وتراكم كميات هائلة من النفايات. ومن هنا برز مفهوم الاقتصاد الدائري، الذي يسعى إلى إبقاء المنتجات والمواد قيد الاستخدام أطول مدة ممكنة عبر إصلاحها وإعادة استخدامها وتدويرها. ولا يقتصر هذا المفهوم على معالجة النفايات بعد إنتاجها، بل يبدأ من مرحلة تصميم المنتج نفسه، بحيث يصنع بطريقة تسهل تفكيكه والاستفادة من مكوناته لاحقا. ويرى المؤيدون أن هذا التحول يمكن أن يوفر فرص عمل جديدة ويقلل اعتماد الدول على استيراد المواد الخام، غير أن تطبيقه على نطاق واسع يتطلب تغيير أنماط الاستهلاك وتحديث التشريعات، فضلا عن استثمارات كبيرة في البنية التحتية.",
 read=["Metin önce geleneksel (doğrusal) ekonomik modeli tanımlıyor: hammadde çıkarma → üretim → tüketim → atık.",
       "وَقَدْ أَدَّى هَذَا النَّمُوذَجُ ... إِلَى ile bu modelin olumsuz sonuçları (kaynakların tükenmesi, atık birikimi), وَمِنْ هُنَا بَرَزَ ile de alternatif olarak döngüsel ekonomi (الِاقْتِصَادُ الدَّائِرِيُّ) kavramı sunuluyor.",
       "لَا يَقْتَصِرُ ... عَلَى مُعَالَجَةِ النُّفَايَاتِ ... بَلْ يَبْدَأُ مِنْ مَرْحَلَةِ تَصْمِيمِ الْمُنْتَجِ cümlesi kavramın ayırt edici özelliğini veriyor. Son cümlede غَيْرَ أَنَّ ile yön değişiyor: faydalarına rağmen uygulanması tüketim alışkanlıklarının değişmesini, mevzuat güncellemesini ve büyük altyapı yatırımlarını gerektiriyor."],
))
PASSAGES.append(dict(
 rng=(38, 40),
 text="أثارت ثنائية اللغة اهتمام الباحثين في علم النفس المعرفي منذ عقود. فقد كان يعتقد في منتصف القرن الماضي أن تعلم الطفل لغتين في آن واحد يربك تفكيره ويؤخر نموه اللغوي. غير أن الدراسات اللاحقة كشفت أن الأطفال الذين ينشؤون على لغتين قد يتأخرون قليلا في اكتساب بعض المفردات في كل لغة على حدة، لكن مجموع ما يعرفونه من مفردات في اللغتين معا يعادل ما يعرفه أقرانهم الذين يتحدثون لغة واحدة أو يفوقه. وتشير أبحاث أخرى إلى أن التنقل المستمر بين لغتين يمرن الدماغ على ضبط الانتباه وتجاهل المعلومات غير المهمة، وهي مهارات تعرف بالوظائف التنفيذية. ومع ذلك، يحذر بعض الباحثين من المبالغة في تعميم هذه النتائج، إذ إن بعض الدراسات لم تتوصل إلى فروق واضحة بين الفئتين، مما يدل على أن عوامل أخرى، كالمستوى التعليمي والظروف الاجتماعية، قد تؤدي دورا في هذه النتائج.",
 read=["Metnin konusu ثُنَائِيَّةُ اللُّغَةِ (iki dillilik) ve beyin / dil gelişimi üzerindeki etkisidir.",
       "فَقَدْ كَانَ يُعْتَقَدُ فِي مُنْتَصَفِ الْقَرْنِ الْمَاضِي ... ile eski görüş (iki dilin çocuğun düşüncesini karıştırıp dil gelişimini geciktirdiği), غَيْرَ أَنَّ الدِّرَاسَاتِ اللَّاحِقَةَ ... ile bu görüşü düzelten yeni bulgular veriliyor: tek tek dillerde hafif gecikme olabilir, ama iki dildeki toplam kelime bilgisi tek dilli akranlara eşit ya da onlardan fazladır.",
       "وَهِيَ مَهَارَاتٌ تُعْرَفُ بِالْوَظَائِفِ التَّنْفِيذِيَّةِ ifadesi bir kavram tanımıdır. Son bölümde وَمَعَ ذَلِكَ ile temkin bildiriliyor: bazı çalışmalar belirgin fark bulamamıştır; eğitim düzeyi ve sosyal koşullar gibi başka etkenler de rol oynayabilir."],
))
PASSAGES.append(dict(
 rng=(41, 43),
 text="لم يكن طريق الحرير طريقا واحدا كما قد يوحي اسمه، بل كان شبكة واسعة من المسالك البرية والبحرية التي ربطت الصين بآسيا الوسطى والشرق الأوسط وأوروبا قرونا عديدة. وقد اكتسب هذا الاسم في القرن التاسع عشر على يد جغرافي ألماني، نسبة إلى الحرير الصيني الذي كان من أثمن السلع المتداولة عبره. غير أن أهمية هذه الشبكة لم تنحصر في تبادل السلع كالتوابل والخزف والمنسوجات، بل تجاوزتها إلى نقل الأفكار والمعتقدات والفنون والتقنيات بين الحضارات. فقد انتقلت عبرها تقنيات زراعية وصناعية عديدة، كما أسهمت في انتشار بعض الديانات والمذاهب الفكرية في مناطق بعيدة عن مواطنها الأصلية. وقد أدت المدن الواقعة على هذه الطرق، مثل سمرقند وبخارى، دورا بارزا بوصفها مراكز للتجارة والعلم، يلتقي فيها التجار والعلماء من ثقافات متعددة.",
 read=["İlk cümle yaygın bir yanlış algıyı düzeltiyor: İpek Yolu tek bir yol değil, Çin'i Orta Asya, Orta Doğu ve Avrupa'ya bağlayan geniş bir kara ve deniz yolları ağıdır (لَمْ يَكُنْ ... بَلْ كَانَ).",
       "İkinci cümle adın kökenini veriyor: 19. yüzyılda bir Alman coğrafyacı tarafından, bu yol üzerinden ticareti yapılan en değerli mallardan biri olan Çin ipeğine nispetle (نِسْبَةً إِلَى) verilmiştir.",
       "غَيْرَ أَنَّ ... لَمْ تَنْحَصِرْ ... بَلْ تَجَاوَزَتْهَا cümlesi metnin ana fikrini veriyor: ağın önemi mal alışverişiyle sınırlı kalmamış, fikirlerin, inançların, sanatların ve tekniklerin aktarımına uzanmıştır. Son cümlede Semerkant ve Buhara gibi şehirlerin ticaret ve ilim merkezi olarak farklı kültürleri buluşturduğu belirtiliyor."],
))

Q = [
dict(n=29, stem="ما الموضوع الرئيس الذي يتناوله النص؟",
 opts=["دور أجهزة التكييف في تلطيف الجو داخل المباني الشاهقة.",
       "أسباب ارتفاع درجات الحرارة في المدن مقارنة بالأرياف وآثاره وسبل الحد منه.",
       "الفروق المناخية بين المناطق الريفية والمناطق الصحراوية.",
       "أثر التغير المناخي العالمي في الإنتاج الزراعي وفي حياة السكان بالمناطق الريفية.",
       "تاريخ التخطيط العمراني في المدن الكبرى."], ans="B",
 a2=["Soru: مَا الْمَوْضُوعُ الرَّئِيسُ الَّذِي يَتَنَاوَلُهُ النَّصُّ؟ “Metnin ele aldığı ana konu nedir?” Ana fikir sorularında metnin bütününü kapsayan, ne çok dar ne çok geniş olan şık aranır.",
     "Metin tanım, sebepler, sonuçlar ve çözümler şeklinde ilerliyor. B şıkkı bu dört bölümün tamamını kapsıyor: “şehirlerde sıcaklığın kırsala göre yükselmesinin sebepleri, etkileri ve azaltma yolları”.",
     "A şıkkı metinde sadece ısı kaynaklarından biri olarak geçen klimaları ana konu yapıyor ve metne ters olarak onlara serinletici rol veriyor. C şıkkında çöl bölgeleri metinde hiç geçmiyor. D, küresel iklim değişikliği ve tarımsal üretimden söz eder; metnin konusu değildir. E, şehir planlamacılarının yalnızca son cümlede geçen önerisini metnin tarihine dönüştürüyor; metinde tarihsel bir anlatım yoktur.",
     "Doğru cevabımız B."]),
dict(n=30, stem="وفقا للنص، لماذا تظل درجات الحرارة مرتفعة في المدن بعد غروب الشمس؟",
 opts=["لأن الرياح تنقل الحرارة من الأرياف إلى المدن ليلا.",
       "لأن النباتات في المدن تطلق ليلا الحرارة التي خزنتها في أوراقها خلال النهار.",
       "لأن المصانع تضاعف إنتاجها في ساعات الليل.",
       "لأن المباني الشاهقة تعكس أشعة الشمس نحو الشوارع.",
       "لأن الأسطح الإسمنتية والإسفلتية تطلق ببطء ما امتصته من حرارة نهارا."], ans="E",
 a2=["Soru: وَفْقًا لِلنَّصِّ، لِمَاذَا تَظَلُّ دَرَجَاتُ الْحَرَارَةِ مُرْتَفِعَةً فِي الْمُدُنِ بَعْدَ غُرُوبِ الشَّمْسِ؟ “Metne göre güneş battıktan sonra şehirlerde sıcaklık neden yüksek kalır?” تَظَلُّ, كَانَ'nin kardeşlerindendir; مُرْتَفِعَةً onun haberidir.",
     "Metinde bakmamız gereken yer ikinci cümledir: ... إِلَى أَنَّ الْأَسْطُحَ الْإِسْمَنْتِيَّةَ وَالْإِسْفَلْتِيَّةَ تَمْتَصُّ أَشِعَّةَ الشَّمْسِ خِلَالَ النَّهَارِ ثُمَّ تُطْلِقُ حَرَارَتَهَا بِبُطْءٍ بَعْدَ الْغُرُوبِ. E şıkkı bu cümlenin başka kelimelerle ifadesidir (خِلَالَ النَّهَارِ → نَهَارًا; تَمْتَصُّ ... ثُمَّ تُطْلِقُ حَرَارَتَهَا → تُطْلِقُ مَا امْتَصَّتْهُ مِنْ حَرَارَةٍ).",
     "A: Rüzgârın ısıyı kırsaldan şehre taşıdığı söylenmiyor; aksine yüksek binaların rüzgârı engellediği belirtiliyor. B: Metinde bitkiler ısı yayan değil, havayı serinleten unsur olarak geçiyor; üstelik bu bilgi şehirlerle değil kırsal alanlarla ilgilidir. C: Fabrikaların gece üretimi artırdığına dair bir bilgi yok. D: Metin, yüksek binaların güneşi yansıttığını değil, rüzgâr hareketini sınırladığını söylüyor; yansıtma özelliği açık renkli malzemelere aittir.",
     "Doğru cevabımız E."]),
dict(n=31, stem="يفهم من النص أن ----.",
 opts=["الفرق الحراري بين المدن والأرياف ثابت طوال ساعات اليوم",
       "كبار السن أقل تأثرا من غيرهم بارتفاع درجات الحرارة في المدن",
       "طبيعة التخطيط العمراني ومواد البناء قد تسهم في التخفيف من حدة الظاهرة",
       "زيادة المباني الشاهقة وتقاربها تساعد على تحسين حركة الرياح وتلطيف الجو في المدن",
       "استهلاك الطاقة في المدن ينخفض مع ارتفاع درجات الحرارة"], ans="C",
 a2=["Soru: يُفْهَمُ مِنَ النَّصِّ أَنَّ ---- “Metinden ... anlaşılmaktadır.” Çıkarım sorularında cevap metinde birebir yazmaz, ama metindeki bilgilerle kesin olarak desteklenir.",
     "Son cümlede şehir planlamacılarının yeşil alanları genişletmeyi ve güneşi daha çok yansıtan açık renkli yapı malzemeleri kullanmayı önerdiği söyleniyor. Ayrıca binaların sıklığının rüzgârı engellediği belirtiliyor. Buradan, kentsel planlama biçiminin ve yapı malzemelerinin sorunu hafifletebileceği sonucu çıkar: C şıkkı.",
     "A: Metin farkın “bazı gecelerde” birkaç dereceye ulaşabildiğini söylüyor (فِي بَعْضِ اللَّيَالِي); bu, farkın sabit olmadığını gösterir. B: Metin, yaşlıların özellikle etkilendiğini söylüyor (وَلَا سِيَّمَا لَدَى كِبَارِ السِّنِّ); şık tam tersini iddia ediyor. D: Yüksek binaların rüzgârı sınırladığı söyleniyor. E: Metin, enerji tüketiminin arttığını belirtiyor.",
     "Doğru cevabımız C."]),
dict(n=32, stem="ما الفكرة الرئيسة للنص؟",
 opts=["إسهام ابن الهيثم في علم البصريات وفي ترسيخ المنهج التجريبي.",
       "انتقال العلوم العربية إلى أوروبا عبر حركة الترجمة.",
       "الخلاف بين ابن الهيثم ومعاصريه حول سرعة الضوء.",
       "تاريخ نظريات الرؤية منذ العصور القديمة حتى العصر الحديث.",
       "أثر كتاب المناظر في تطور الطب الأوروبي."], ans="A",
 a2=["Metin, ilk cümlesinden son cümlesine kadar İbnü’l-Heysem'in iki yönlü katkısını anlatıyor: görme ve ışık konusundaki bulguları (optik / الْبَصَرِيَّات) ve her hipotezi deney ve gözleme tabi tutan yöntemi. A şıkkı bu iki unsuru birlikte içeriyor.",
     "B: Kitabın Latinceye çevrilmesi metinde tek bir ayrıntıdır; genel olarak Arap ilimlerinin Avrupa'ya aktarımı metnin konusu değildir. C: Metinde çağdaşlarıyla bir tartışmadan ve ışığın hızından söz edilmiyor; eleştirilen görüş, önceki bilginlere aittir (الْعُلَمَاءِ السَّابِقِينَ). D: Metin görme teorilerinin tarihini anlatmıyor, sadece bir teorinin reddedilmesine değiniyor. E: Kitabın tıbba etkisinden söz edilmiyor.",
     "Doğru cevabımız A."]),
dict(n=33, stem="وفقا للنص، ما الذي رفضه ابن الهيثم؟",
 opts=["إجراء التجارب الدقيقة على الضوء وانعكاسه وانكساره.",
       "ترجمة مؤلفاته العلمية إلى اللغة اللاتينية.",
       "الاعتماد على الملاحظة في دراسة الظواهر الطبيعية.",
       "التسليم بالنظرية القائلة بأن العين تبعث أشعة نحو الأجسام.",
       "تدوين نتائج أبحاثه في كتاب مستقل."], ans="D",
 a2=["Soru: مَا الَّذِي رَفَضَهُ ابْنُ الْهَيْثَمِ؟ “İbnü’l-Heysem neyi reddetti?” Metindeki ilgili cümle: فَقَدْ رَفَضَ الِاكْتِفَاءَ بِمَا وَرِثَهُ مِنْ آرَاءِ الْعُلَمَاءِ السَّابِقِينَ فِي تَفْسِيرِ الرُّؤْيَةِ، وَلَا سِيَّمَا النَّظَرِيَّةَ الَّتِي كَانَتْ تَزْعُمُ أَنَّ الْعَيْنَ تَبْعَثُ أَشِعَّةً نَحْوَ الْأَجْسَامِ.",
     "D şıkkı bu cümlenin anlamca karşılığıdır: “gözün cisimlere ışın gönderdiğini söyleyen teoriyi kabullenmek”. التَّسْلِيمُ بِـ “...i kabullenmek, teslim olmak” demektir. Metindeki كَانَتْ تَزْعُمُ fiili (iddia ediyordu), yazarın bu teoriye mesafeli durduğunu da gösterir.",
     "A ve C: Deney yapmak ve gözleme dayanmak onun bizzat benimsediği yöntemdir. B: Kitabın çevrilmesi onun reddettiği bir şey değil, sonradan gerçekleşen bir olaydır. E: Sonuçlarını “el-Menâzır” kitabında kaydettiği açıkça söyleniyor.",
     "Doğru cevabımız D."]),
dict(n=34, stem="وفقا للنص، تكمن القيمة الكبرى لإسهام ابن الهيثم في ----.",
 opts=["كثرة المؤلفات التي كتبها في مختلف العلوم",
       "منهجه القائم على اختبار الفرضيات بالتجربة والملاحظة",
       "نقله آراء العلماء السابقين دون تعديل",
       "اختراعه أجهزة دقيقة لقياس سرعة الضوء",
       "اعتماد العلماء الأوروبيين على كتبه في تعلم اللغة العربية"], ans="B",
 a2=["Cevap metnin son cümlesindedir: وَلَمْ تَكُنْ قِيمَةُ إِسْهَامِهِ فِي النَّتَائِجِ الَّتِي تَوَصَّلَ إِلَيْهَا فَحَسْبُ، بَلْ فِي إِصْرَارِهِ عَلَى إِخْضَاعِ كُلِّ فَرَضِيَّةٍ لِلتَّجْرِبَةِ وَالْمُلَاحَظَةِ. لَمْ ... فَحَسْبُ، بَلْ ... yapısı vurguyu بَلْ'den sonraki kısma taşır; asıl değer yöntemdedir.",
     "B şıkkı bu ifadeyi başka kelimelerle verir: “hipotezleri deney ve gözlemle sınamaya dayanan yöntemi”. تَكْمُنُ فِي “...de yatmak / gizli olmak” anlamındadır.",
     "A: Metinde eserlerinin sayısından söz edilmiyor. C: Tam tersine, önceki görüşleri olduğu gibi kabul etmediği anlatılıyor. D: Işık hızını ölçen bir aletten söz edilmiyor. E: Avrupalıların kitabı bilim kaynağı olarak kullandığı belirtiliyor, Arapça öğrenmek için değil.",
     "Doğru cevabımız B."]),
dict(n=35, stem="العنوان الأنسب للنص هو ----.",
 opts=["مخاطر إعادة التدوير على الصناعات المحلية وفرص العمل",
       "أسباب ارتفاع أسعار المواد الخام عالميا",
       "الاقتصاد الدائري بديلا عن النموذج الاقتصادي الخطي",
       "دور التشريعات في زيادة معدلات الاستهلاك",
       "تاريخ الصناعة منذ الثورة الصناعية"], ans="C",
 a2=["Başlık sorularında metnin bütününü kapsayan en kısa ifade aranır. Metin doğrusal modeli ve sorunlarını tanıtıp alternatif olarak döngüsel ekonomiyi sunuyor, sonra faydalarını ve uygulama güçlüklerini tartışıyor. C şıkkı “doğrusal ekonomik modele alternatif olarak döngüsel ekonomi” bu yapının tamamını yansıtır. بَدِيلًا burada hâl olarak mansuptur.",
     "A: Metin geri dönüşümün yerel sanayi ve istihdam için riskinden söz etmiyor; aksine yeni iş imkânlarından bahsediyor. B: Hammadde fiyatlarının artışı metinde geçmiyor. D: Mevzuatın güncellenmesi bir uygulama şartı olarak geçiyor; tüketimi artırmakla ilgisi yok. E: Metinde tarihsel bir anlatım yoktur.",
     "Doğru cevabımız C."]),
dict(n=36, stem="وفقا للنص، ما الذي يميز الاقتصاد الدائري عن مجرد معالجة النفايات؟",
 opts=["أنه يعتمد على استيراد المواد الخام بكميات أكبر.",
       "أنه يركز على التخلص من النفايات بسرعة أكبر.",
       "أنه يقتصر على تدوير المنتجات وإعادة استخدامها بعد انتهاء صلاحيتها.",
       "أنه يهدف إلى زيادة معدلات الاستهلاك لدعم الاقتصاد.",
       "أنه يبدأ من تصميم المنتج بما يسهل تفكيكه لاحقا."], ans="E",
 a2=["İlgili cümle: وَلَا يَقْتَصِرُ هَذَا الْمَفْهُومُ عَلَى مُعَالَجَةِ النُّفَايَاتِ بَعْدَ إِنْتَاجِهَا، بَلْ يَبْدَأُ مِنْ مَرْحَلَةِ تَصْمِيمِ الْمُنْتَجِ نَفْسِهِ، بِحَيْثُ يُصْنَعُ بِطَرِيقَةٍ تُسَهِّلُ تَفْكِيكَهُ وَالِاسْتِفَادَةَ مِنْ مُكَوِّنَاتِهِ لَاحِقًا.",
     "E şıkkı bu cümlenin anlamca karşılığıdır. Sorudaki مُجَرَّدُ مُعَالَجَةِ النُّفَايَاتِ (sadece atıkları işlemek) ifadesi, metindeki لَا يَقْتَصِرُ عَلَى ifadesine denk gelir.",
     "A: Metin döngüsel ekonominin hammadde ithalatını azaltacağını söylüyor. B: Atıklardan hızla kurtulmak doğrusal modelin son aşamasıdır. C: يَقْتَصِرُ عَلَى ifadesi metnin söylediğinin tam tersidir; bu şık, metindeki ifadenin kelimelerini kullanarak kurulmuş güçlü bir çeldiricidir. D: Metin, tüketim alışkanlıklarının değişmesi gerektiğini söylüyor, tüketimin artırılmasını değil.",
     "Doğru cevabımız E."]),
dict(n=37, stem="يفهم من النص أن تطبيق الاقتصاد الدائري ----.",
 opts=["لا يتحقق بسهولة لما يتطلبه من تغييرات واستثمارات كبيرة",
       "قد يؤدي على المدى البعيد إلى زيادة اعتماد الدول على استيراد المواد الخام",
       "لا يحتاج إلى أي تعديل في البنية التحتية القائمة",
       "أدى بالفعل إلى القضاء على مشكلة النفايات في معظم الدول",
       "يلقى رفضا من جميع الاقتصاديين لأنه يقلل فرص العمل"], ans="A",
 a2=["Son cümlede غَيْرَ أَنَّ ile yön değişiyor: غَيْرَ أَنَّ تَطْبِيقَهُ عَلَى نِطَاقٍ وَاسِعٍ يَتَطَلَّبُ تَغْيِيرَ أَنْمَاطِ الِاسْتِهْلَاكِ وَتَحْدِيثَ التَّشْرِيعَاتِ، فَضْلًا عَنِ اسْتِثْمَارَاتٍ كَبِيرَةٍ فِي الْبِنْيَةِ التَّحْتِيَّةِ. Üç ayrı şartın sayılması, uygulamanın kolay olmadığı sonucunu doğurur: A şıkkı.",
     "B: Metin bağımlılığın azalacağını söylüyor. C: Altyapıya büyük yatırım gerektiği açıkça belirtiliyor. D: Metin döngüsel ekonomiyi bir öneri / dönüşüm olarak sunuyor; sorunun çoğu ülkede fiilen çözüldüğünü söylemiyor. E: Destekleyenlerin (الْمُؤَيِّدُونَ) varlığı ve yeni iş imkânı sağlayacağı görüşü bu şıkkı çürütür; ayrıca جَمِيعُ gibi mutlak ifadeler çıkarım sorularında genellikle yanlıştır.",
     "Doğru cevabımız A."]),
dict(n=38, stem="وفقا للنص، ما الرأي الذي كان سائدا في منتصف القرن الماضي بشأن ثنائية اللغة؟",
 opts=["أنها تحسن قدرة الطفل على ضبط الانتباه.",
       "أنها لا تؤثر في النمو اللغوي للطفل مطلقا.",
       "أنها تزيد عدد المفردات التي يكتسبها الطفل.",
       "أنها تربك تفكير الطفل وتؤخر نموه اللغوي.",
       "أنها ترتبط بالمستوى التعليمي للأسرة."], ans="D",
 a2=["İlgili cümle: فَقَدْ كَانَ يُعْتَقَدُ فِي مُنْتَصَفِ الْقَرْنِ الْمَاضِي أَنَّ تَعَلُّمَ الطِّفْلِ لُغَتَيْنِ فِي آنٍ وَاحِدٍ يُرْبِكُ تَفْكِيرَهُ وَيُؤَخِّرُ نُمُوَّهُ اللُّغَوِيَّ. كَانَ يُعْتَقَدُ (inanılıyordu) meçhul yapısı, geçmişte yaygın olan görüşü bildirir.",
     "D şıkkı bu görüşü birebir karşılar. A ve C şıkları, eski görüşü değil, غَيْرَ أَنَّ'den sonra gelen yeni araştırmaların bulgularını yansıtır; bu iki şık zaman bakımından çeldiricidir. B hem eski hem yeni görüşle çelişir. E'deki eğitim düzeyi, metnin sonunda sonuçları etkileyebilecek başka bir etken olarak geçer; eski görüşle ilgisi yoktur.",
     "Doğru cevabımız D."]),
dict(n=39, stem="ما المقصود بـ\"الوظائف التنفيذية\" في النص؟",
 opts=["القدرة على حفظ عدد كبير من المفردات في لغتين.",
       "مهارات ضبط الانتباه وتجاهل المعلومات غير المهمة.",
       "سرعة الترجمة من لغة إلى أخرى.",
       "القدرة على تعلم أكثر من لغتين في مرحلة الطفولة.",
       "المهارات الاجتماعية المكتسبة من البيئة المحيطة."], ans="B",
 a2=["Kavram sorularında cevap, kavramın metinde geçtiği cümlede aranır: يُمَرِّنُ الدِّمَاغَ عَلَى ضَبْطِ الِانْتِبَاهِ وَتَجَاهُلِ الْمَعْلُومَاتِ غَيْرِ الْمُهِمَّةِ، وَهِيَ مَهَارَاتٌ تُعْرَفُ بِالْوَظَائِفِ التَّنْفِيذِيَّةِ. Buradaki هِيَ zamiri, bir önceki ifadede sayılan becerilere döner.",
     "B şıkkı tanımı birebir verir. A (kelime bilgisi) ve C (çeviri hızı) metinde bu kavramla ilişkilendirilmez. D, iki dilden fazlasını öğrenmekten söz eder; metinde yok. E'deki sosyal koşullar metnin sonunda farklı bir bağlamda geçer.",
     "Doğru cevabımız B."]),
dict(n=40, stem="يمكن أن يستنتج من النص أن ----.",
 opts=["جميع الدراسات أثبتت تفوق ثنائيي اللغة في الوظائف التنفيذية",
       "الأطفال الذين ينشؤون على لغتين يعرفون مفردات أقل من أقرانهم في مجموع اللغتين",
       "نتائج الأبحاث حول أثر ثنائية اللغة في الدماغ ليست قاطعة تماما",
       "العوامل الاجتماعية لا علاقة لها بنتائج الدراسات اللغوية",
       "تعلم لغتين في آن واحد يضر بالنمو اللغوي للطفل"], ans="C",
 a2=["Son bölüm çıkarımın kaynağıdır: وَمَعَ ذَلِكَ، يُحَذِّرُ بَعْضُ الْبَاحِثِينَ مِنَ الْمُبَالَغَةِ فِي تَعْمِيمِ هَذِهِ النَّتَائِجِ، إِذْ إِنَّ بَعْضَ الدِّرَاسَاتِ لَمْ تَتَوَصَّلْ إِلَى فُرُوقٍ وَاضِحَةٍ. Bulguların genellenmesine karşı uyarı ve bazı çalışmaların fark bulamaması, sonuçların kesin olmadığını gösterir: C şıkkı.",
     "A: جَمِيعُ (bütün) ifadesi, fark bulamayan çalışmaların varlığıyla çelişir. B: Metin, toplam kelime bilgisinin eşit veya daha fazla olduğunu söylüyor. D: Metin sosyal koşulların sonuçlarda rol oynayabileceğini söylüyor. E: Bu, sonradan çürütülen eski görüştür.",
     "Doğru cevabımız C."]),
dict(n=41, stem="الغرض الأساسي من النص هو ----.",
 opts=["بيان الأسباب التي أدت إلى زوال طريق الحرير",
       "المقارنة بين الطرق البرية والطرق البحرية في العصور القديمة",
       "التعريف بالجغرافي الذي أطلق اسم طريق الحرير",
       "وصف السلع التي كانت الصين تستوردها من أوروبا",
       "توضيح طبيعة طريق الحرير ودوره الحضاري الذي تجاوز التجارة"], ans="E",
 a2=["Metnin iki temel iddiası var: (1) İpek Yolu tek bir yol değil, geniş bir ağdır; (2) önemi mal ticaretiyle sınırlı kalmamış, fikir ve kültür aktarımına uzanmıştır (لَمْ تَنْحَصِرْ ... بَلْ تَجَاوَزَتْهَا). E şıkkı bu iki unsuru birlikte ifade eder.",
     "A: Yolun yok oluşundan söz edilmiyor. B: Kara ve deniz yolları karşılaştırılmıyor, sadece ağın bileşenleri olarak anılıyor. C: Alman coğrafyacı sadece adın kökeni için anılan bir ayrıntıdır; adı bile verilmiyor. D: Metin, Çin'in ithal ettiği malları değil, yol üzerinden taşınan malları (baharat, porselen, dokuma) sayıyor.",
     "Doğru cevabımız E."]),
dict(n=42, stem="وفقا للنص، لماذا سمي طريق الحرير بهذا الاسم؟",
 opts=["لأن الحرير الصيني كان من أثمن السلع المتداولة عبره.",
       "لأن الحرير كان السلعة الوحيدة التي تنقل عبره.",
       "لأن التجار الصينيين هم الذين أطلقوا عليه هذا الاسم.",
       "لأن معظم المدن الواقعة عليه اشتهرت بصناعة الحرير.",
       "لأنه كان يربط بين مراكز إنتاج الحرير في آسيا الوسطى."], ans="A",
 a2=["İlgili cümle: وَقَدِ اكْتَسَبَ هَذَا الِاسْمَ ... نِسْبَةً إِلَى الْحَرِيرِ الصِّينِيِّ الَّذِي كَانَ مِنْ أَثْمَنِ السِّلَعِ الْمُتَدَاوَلَةِ عَبْرَهُ. نِسْبَةً إِلَى (...e nispetle) ifadesi adın gerekçesini verir; kalıplaşmış bu ifadede نِسْبَةً, hazfedilmiş bir fiilin (نُسِبَ) mef‘ûl-i mutlakı olarak mansuptur.",
     "A şıkkı bu gerekçeyi birebir verir. B: مِنْ أَثْمَنِ (en değerlilerinden biri) ifadesi ipeğin tek mal olmadığını gösterir; ayrıca metin baharat, porselen ve dokumalardan da söz ediyor. C: Adı bir Alman coğrafyacı vermiştir. D ve E: Şehirlerin ipek üretimiyle ünlü olduğuna ya da yolun ipek üretim merkezlerini bağladığına dair bilgi yoktur.",
     "Doğru cevabımız A."]),
dict(n=43, stem="يفهم من النص أن مدنا مثل سمرقند وبخارى ----.",
 opts=["كانت تمنع دخول العلماء القادمين من ثقافات أخرى",
       "فقدت أهميتها بعد تحول الطريق إلى شبكة بحرية",
       "اقتصر دورها على تخزين السلع المتجهة إلى أوروبا",
       "كانت ملتقى للتبادل التجاري والعلمي بين ثقافات مختلفة",
       "كانت مراكز لإنتاج الحرير وتصديره إلى الصين"], ans="D",
 a2=["Son cümle: أَدَّتِ الْمُدُنُ الْوَاقِعَةُ عَلَى هَذِهِ الطُّرُقِ، مِثْلَ سَمَرْقَنْدَ وَبُخَارَى، دَوْرًا بَارِزًا بِوَصْفِهَا مَرَاكِزَ لِلتِّجَارَةِ وَالْعِلْمِ، يَلْتَقِي فِيهَا التُّجَّارُ وَالْعُلَمَاءُ مِنْ ثَقَافَاتٍ مُتَعَدِّدَةٍ. بِوَصْفِهَا “...olarak” anlamında niteleme bildirir.",
     "D şıkkı bu cümlenin anlamını korur: şehirler, farklı kültürler arasında ticari ve ilmî alışverişin buluşma noktasıydı.",
     "A: Farklı kültürlerden âlimlerin buluştuğu söyleniyor; şık bunun tersini iddia ediyor. B: Yolun deniz ağına dönüştüğünden ve şehirlerin önem kaybından söz edilmiyor. C: اقْتَصَرَ (sınırlı kaldı) ifadesi, şehirlerin ilim merkezi olma rolünü dışladığı için yanlıştır. E: Metinde ipek Çin'e ait bir mal olarak geçer; bu şehirlerin ipek üretip Çin'e ihraç ettiğine dair bir bilgi yoktur.",
     "Doğru cevabımız D."]),
]
