# -*- coding: utf-8 -*-
# Sorular 1-28

SECTIONS = []
Q = []

SECTIONS.append(dict(
    rng=(1, 8),
    title="KELİME BİLGİSİ VE DİL BİLGİSİ (Cümlede Boşluk Doldurma)",
    instr="1.-8. sorularda, cümlede boş bırakılan yerlere uygun düşen sözcük veya ifadeyi bulunuz.",
    skill="Bu bölüm; adayın akademik ve güncel Arapçadaki sözcük dağarcığını, özellikle mastar ve fiillerin hangi isimlerle birlikte kullanıldığını (eşdizim / collocation) ve kelime + harf-i cer birlikteliğini ölçer.",
    strategy="Önce cümlenin genel yönünü (olumlu / olumsuz, sebep / sonuç) belirleyin; ardından boşluğun hemen öncesindeki ve sonrasındaki kelimeye bakarak hangi eşdizimin kurulacağını düşünün. Şıkları tek tek cümleye yerleştirip hem anlam hem de harf-i cer uyumunu kontrol edin; zıt anlamlı çeldiricileri bağlam ipucuyla eleyin.",
))

Q += [
dict(n=1,
 stem="تسعى الحكومات إلى ---- الفجوة الرقمية بين المناطق الحضرية والريفية من خلال توسيع شبكات الاتصال السريعة.",
 opts=["تعزيز", "ترسيخ", "تقليص", "تنشيط", "تحصين"], ans="C", key="تَقْلِيصِ",
 a1=[("تَسْعَى الْحُكُومَاتُ إِلَى ---- الْفَجْوَةِ الرَّقْمِيَّةِ", "Hükümetler dijital uçurumu ---- çalışmaktadır"),
     ("بَيْنَ الْمَنَاطِقِ الْحَضَرِيَّةِ وَالرِّيفِيَّةِ", "kentsel ve kırsal bölgeler arasındaki"),
     ("مِنْ خِلَالِ تَوْسِيعِ شَبَكَاتِ الاتِّصَالِ السَّرِيعَةِ", "hızlı iletişim ağlarını genişletmek suretiyle.")],
 a2=["Bu soruda boşluktan sonra gelen الْفَجْوَةِ الرَّقْمِيَّةِ (dijital uçurum) ifadesine ve cümlenin sonundaki مِنْ خِلَالِ تَوْسِيعِ شَبَكَاتِ الاتِّصَالِ (iletişim ağlarını genişleterek) ifadesine bakıyorum. Hükümetler ağları genişletiyorsa, amaç uçurumu kapatmak, yani daraltmak olmalıdır.",
     "Dil bilgisi: تَسْعَى ... إِلَى kalıbında إِلَى harf-i cerdir; boşluğa gelecek kelime mecrur bir mastardır (مَجْرُورٌ بِإِلَى) ve kendisinden sonraki الْفَجْوَةِ kelimesine muzâf olur (إِضَافَة).",
     "Şıklara bakalım: تَعْزِيزٌ güçlendirmek, تَرْسِيخٌ kökleştirmek / kalıcı kılmak, تَنْشِيطٌ canlandırmak, تَحْصِينٌ sağlamlaştırmak / korumak demektir. Bu kelimeler kulağa olumlu gelir; bu yüzden aday “olumlu kelime” arayarak eleme yapamaz. Ancak الْفَجْوَة ile birleştiklerinde تَعْزِيزُ الْفَجْوَةِ ve تَرْسِيخُ الْفَجْوَةِ “uçurumu güçlendirmek / kalıcı kılmak” anlamına gelir; bu da ağları genişletme çabasıyla çelişir. تَنْشِيطٌ ve تَحْصِينٌ ise الْفَجْوَة ile anlamlı bir eşdizim kurmaz.",
     "تَقْلِيصٌ ise “küçültmek, daraltmak” anlamındadır. تَقْلِيصُ الْفَجْوَةِ “uçurumu daraltmak” Arapçada yerleşik bir eşdizimdir.",
     "Kelime notu: الْفَجْوَةُ الرَّقْمِيَّةُ = dijital uçurum; تَقْلِيصُ الْفَجْوَةِ / سَدُّ الْفَجْوَةِ = uçurumu daraltmak / kapatmak."]),

dict(n=2,
 stem="يعد الحوار البناء بين الثقافات ---- لتحقيق التفاهم المتبادل ونبذ التعصب والانغلاق.",
 opts=["سبيلا", "حصيلة", "مرادفا", "مبررا", "عاقبة"], ans="A", key="سَبِيلًا",
 a1=[("يُعَدُّ الْحِوَارُ الْبَنَّاءُ بَيْنَ الثَّقَافَاتِ ----", "Kültürler arası yapıcı diyalog ---- sayılır"),
     ("لِتَحْقِيقِ التَّفَاهُمِ الْمُتَبَادَلِ", "karşılıklı anlayışı gerçekleştirmek için"),
     ("وَنَبْذِ التَّعَصُّبِ وَالانْغِلَاقِ", "ve bağnazlığı ve içe kapanmayı terk etmek için.")],
 a2=["يُعَدُّ fiili “sayılır, kabul edilir” anlamında meçhul bir fiildir ve iki mef‘ûl alan عَدَّ fiilinden gelir. Meçhul yapıldığında birinci mef‘ûl nâib-i fâil (الْحِوَارُ) olur, ikinci mef‘ûl mansup kalır. Boşluğa gelecek kelime bu nedenle mansuptur (سَبِيلًا).",
     "İpucu boşluktan sonraki لِـ harf-i ceridir: “... için bir yol / araç”. Cümlenin bağlamı tamamen olumludur: diyalog, anlayışı sağlar ve bağnazlığı ortadan kaldırır.",
     "حَصِيلَةٌ (sonuç, ürün) ve عَاقِبَةٌ (akıbet, varılan sonuç) sebep-sonuç ilişkisini tersine çevirir: diyalog anlayışın sonucu değil, ona götüren yoldur. Ayrıca لِتَحْقِيقِ (gerçekleştirmek için) amaç bildirdiği için “sonuç” anlamlı kelimelerle uyuşmaz. مُرَادِفٌ (eş anlamlı) anlamsız bir ilişki kurar. مُبَرِّرٌ (gerekçe, bahane) ise olumsuz bir çağrışım taşır ve “yapıcı diyalog” (الْحِوَارُ الْبَنَّاءُ) ifadesiyle bağdaşmaz.",
     "سَبِيلٌ ise “yol, vasıta” demektir: سَبِيلٌ لِتَحْقِيقِ ... “...yı gerçekleştirmenin yolu”."]),

dict(n=3,
 stem="أثارت نتائج الدراسة الأخيرة ---- واسعا في الأوساط العلمية، إذ جاءت مخالفة لما كان سائدا من نظريات.",
 opts=["إجماعا", "ارتياحا", "فتورا", "تأييدا", "جدلا"], ans="E", key="جَدَلًا",
 a1=[("أَثَارَتْ نَتَائِجُ الدِّرَاسَةِ الْأَخِيرَةِ ---- وَاسِعًا", "Son çalışmanın sonuçları geniş bir ---- uyandırdı"),
     ("فِي الْأَوْسَاطِ الْعِلْمِيَّةِ", "bilim çevrelerinde"),
     ("إِذْ جَاءَتْ مُخَالِفَةً لِمَا كَانَ سَائِدًا مِنْ نَظَرِيَّاتٍ", "çünkü (sonuçlar) yaygın olan teorilere aykırı çıktı.")],
 a2=["Bu soruda gerekçe bildiren إِذْ (çünkü) edatından sonraki bölüm çözümü veriyor: sonuçlar mevcut teorilere aykırı (مُخَالِفَةً). Yerleşik görüşlere ters düşen sonuçlar doğal olarak tartışma doğurur.",
     "Dil bilgisi: أَثَارَتْ fiilinin fâili نَتَائِجُ, mef‘ûlü ise boşluğa gelecek kelimedir; bu yüzden mansuptur. وَاسِعًا ise bu mef‘ûlün sıfatıdır (نَعْت). مُخَالِفَةً, جَاءَتْ fiilinin hâlidir.",
     "إِجْمَاعٌ (fikir birliği) ve تَأْيِيدٌ (destek), teorilere aykırılık gerekçesiyle çelişir. ارْتِيَاحٌ memnuniyet demektir; yerleşik teorilere aykırı sonuçların genel bir memnuniyet uyandırması إِذْ ile verilen gerekçeyle bağdaşmaz. فُتُورٌ ise ilgisizlik / soğukluk demektir; “geniş bir ilgisizlik uyandırdı” mantıksızdır.",
     "أَثَارَ جَدَلًا وَاسِعًا “geniş bir tartışma başlattı” kalıbı Arapçada son derece yaygın bir eşdizimdir. Ayrıca جَاءَتْ مُخَالِفَةً ifadesi tartışmanın nedenini açıkça verir."]),

dict(n=4,
 stem="ينبغي للباحث أن ---- الموضوعية في عرض النتائج، فلا يغفل البيانات التي تتعارض مع فرضياته.",
 opts=["يتجنب", "يتحرى", "يستبعد", "يهمل", "يقوض"], ans="B", key="يَتَحَرَّى",
 a1=[("يَنْبَغِي لِلْبَاحِثِ أَنْ ---- الْمَوْضُوعِيَّةَ", "Araştırmacının nesnelliği ---- gerekir"),
     ("فِي عَرْضِ النَّتَائِجِ", "sonuçları sunarken"),
     ("فَلَا يُغْفِلَ الْبَيَانَاتِ الَّتِي تَتَعَارَضُ مَعَ فَرَضِيَّاتِهِ", "böylece hipotezleriyle çelişen verileri göz ardı etmesin.")],
 a2=["أَنْ harfi masdariyye ve nasb edatıdır; ardından gelen muzari fiil mansuptur. Tüm şıklar tekil üçüncü şahıs muzari olduğundan dil bilgisi bakımından paraleldir; ayrım anlamdadır.",
     "İpucu فَلَا يُغْفِلَ (göz ardı etmesin) ifadesidir. Buradaki فَـ, önceki cümlenin açıklamasını getirir: nesnel olan araştırmacı aleyhindeki verileri de gizlemez. O hâlde boşluğa “nesnelliği gözetmek / aramak” anlamı gelmelidir.",
     "يَتَجَنَّبُ kaçınır, يَسْتَبْعِدُ dışlar, يُهْمِلُ ihmal eder, يُقَوِّضُ yıkar / temelini sarsar anlamındadır; hepsi nesnelliğe karşı olumsuz bir tutum bildirir ve cümlenin öğüt yönüyle çelişir.",
     "يَتَحَرَّى “titizlikle arar, gözetir” anlamındadır: تَحَرِّي الْمَوْضُوعِيَّةِ / تَحَرِّي الدِّقَّةِ yerleşik eşdizimlerdir. (Harekesiz yazımda يتحرى, أَنْ ile mansup okunur: أَنْ يَتَحَرَّى; kusurlu fiilde nasb takdirîdir.)"]),

dict(n=5,
 stem="لا يمكن للاقتصاد أن ينمو نموا مستداما ما لم تتوافر بيئة تشريعية ---- للاستثمار تحمي حقوق المستثمرين.",
 opts=["طاردة", "محايدة", "مستوردة", "جاذبة", "مكلفة"], ans="D", key="جَاذِبَةٌ",
 a1=[("لَا يُمْكِنُ لِلِاقْتِصَادِ أَنْ يَنْمُوَ نُمُوًّا مُسْتَدَامًا", "Ekonominin sürdürülebilir bir şekilde büyümesi mümkün değildir"),
     ("مَا لَمْ تَتَوَافَرْ بِيئَةٌ تَشْرِيعِيَّةٌ ---- لِلِاسْتِثْمَارِ", "yatırım için ---- bir yasal ortam bulunmadıkça"),
     ("تَحْمِي حُقُوقَ الْمُسْتَثْمِرِينَ", "(ki bu ortam) yatırımcıların haklarını korur.")],
 a2=["مَا لَمْ “...madıkça” anlamında şart bildiren bir yapıdır; ardından gelen fiil لَمْ ile meczumdur (تَتَوَافَرْ). Cümle, sürdürülebilir büyümenin şartını söylüyor; demek ki boşluğa olumlu bir nitelik gelmelidir.",
     "نُمُوًّا مُسْتَدَامًا ifadesinde نُمُوًّا, يَنْمُوَ fiilinin mef‘ûl-i mutlakıdır (مَفْعُولٌ مُطْلَقٌ مُبَيِّنٌ لِلنَّوْعِ), مُسْتَدَامًا da onun sıfatıdır.",
     "Boşluğa gelecek kelime بِيئَةٌ isminin sıfatıdır; bu nedenle müennes ve merfû olmalıdır. Bütün şıklar bu bakımdan uygundur; ayrım anlamdadır. طَارِدَةٌ (kaçıran, uzaklaştıran) tam zıt anlamlıdır. مُحَايِدَةٌ (tarafsız) yatırımı özendiren bir nitelik bildirmez ve لِلِاسْتِثْمَارِ ile eşdizim kurmaz. مُسْتَوْرَدَةٌ (ithal) bir yasal ortamı nitelemek için anlamsızdır. مُكْلِفَةٌ (masraflı) ise sürdürülebilir büyümenin şartı olamaz.",
     "بِيئَةٌ جَاذِبَةٌ لِلِاسْتِثْمَارِ “yatırım için cazip ortam” Arapçada çok yaygın bir eşdizimdir; ayrıca جَاذِبٌ لِـ şeklinde لِـ harf-i ceriyle kullanılır."]),

dict(n=6,
 stem="---- الأديب في روايته الأخيرة ببراعة وعمق حياة المهاجرين وما يعانونه من غربة وحنين إلى أوطانهم.",
 opts=["أغفل", "أنكر", "اختصر", "شوه", "صور"], ans="E", key="صَوَّرَ",
 a1=[("---- الْأَدِيبُ فِي رِوَايَتِهِ الْأَخِيرَةِ بِبَرَاعَةٍ وَعُمْقٍ", "Edip son romanında ustalık ve derinlikle ----"),
     ("حَيَاةَ الْمُهَاجِرِينَ", "göçmenlerin hayatını"),
     ("وَمَا يُعَانُونَهُ مِنْ غُرْبَةٍ وَحَنِينٍ إِلَى أَوْطَانِهِمْ", "ve yaşadıkları gurbet ile vatanlarına duydukları özlemi.")],
 a2=["Boşluğa gelecek fiilin mef‘ûlü حَيَاةَ الْمُهَاجِرِينَ ifadesidir; وَمَا يُعَانُونَهُ kısmındaki مَا ism-i mevsûldür ve حَيَاةَ kelimesine atfedilmiştir (mansup mahallinde).",
     "İpucu بِبَرَاعَةٍ وَعُمْقٍ (ustalıkla ve derinlikle) hâl anlamlı câr-mecrurudur. Bir yazar bir konuyu “ustalıkla ve derinlemesine” ancak betimleyebilir / işleyebilir.",
     "أَغْفَلَ göz ardı etti, أَنْكَرَ inkâr etti, شَوَّهَ çarpıttı anlamındadır; “ustalık ve derinlik” ile bağdaşmaz. اخْتَصَرَ (kısalttı, özetledi) ise “derinlikle” (بِعُمْقٍ) ifadesiyle çelişir.",
     "صَوَّرَ “tasvir etti, betimledi” anlamındadır; edebî eserlerde صَوَّرَ الْكَاتِبُ الْحَيَاةَ yerleşik bir kullanımdır."]),

dict(n=7,
 stem="أثبت الدواء الجديد ---- عالية في تخفيف أعراض المرض، مما شجع الهيئات الصحية على اعتماده في المستشفيات الحكومية.",
 opts=["تكلفة", "فعالية", "ندرة", "شعبية", "حساسية"], ans="B", key="فَعَّالِيَّةً",
 a1=[("أَثْبَتَ الدَّوَاءُ الْجَدِيدُ ---- عَالِيَةً", "Yeni ilaç yüksek bir ---- kanıtladı"),
     ("فِي تَخْفِيفِ أَعْرَاضِ الْمَرَضِ", "hastalığın belirtilerini hafifletmede"),
     ("مِمَّا شَجَّعَ الْهَيْئَاتِ الصِّحِّيَّةَ عَلَى اعْتِمَادِهِ", "bu da sağlık kurumlarını onu benimsemeye teşvik etti.")],
 a2=["Sonuç bildiren مِمَّا (bu da ...) yapısı çözümün anahtarıdır: Sağlık kurumları ilacı benimsemeye teşvik edildiyse ilaç olumlu bir özellik göstermiş olmalıdır.",
     "Dil bilgisi: Boşluktaki kelime أَثْبَتَ fiilinin mef‘ûlüdür ve عَالِيَةً ile nitelendiği için müennes olmalıdır. Bütün şıklar müennestir; dolayısıyla ayrım anlamdadır ve أَثْبَتَ ... فِي تَخْفِيفِ أَعْرَاضِ الْمَرَضِ (hastalığın belirtilerini hafifletmede ... kanıtladı) bağlamına bakmak gerekir.",
     "تَكْلِفَةٌ عَالِيَةٌ (yüksek maliyet) çok yaygın bir eşdizim olduğu için en güçlü çeldiricidir; ama bir ilacın “belirtileri hafifletmede yüksek maliyet kanıtlaması” anlamsızdır ve teşvik sonucunu açıklamaz. نُدْرَةٌ nadirlik, شَعْبِيَّةٌ popülerlik, حَسَاسِيَّةٌ duyarlılık / alerji demektir; hiçbiri فِي تَخْفِيفِ أَعْرَاضِ الْمَرَضِ ile anlamlı bir bütün oluşturmaz.",
     "فَعَّالِيَّةٌ عَالِيَةٌ “yüksek etkinlik” yerleşik bir eşdizimdir ve sonuç cümlesiyle tam uyumludur."]),

dict(n=8,
 stem="تمثل الصادرات النفطية ---- الأساسي للدخل القومي في كثير من دول الخليج العربي.",
 opts=["الرافد", "المستفيد", "الهامش", "المصب", "العبء"], ans="A", key="الرَّافِدَ",
 a1=[("تُمَثِّلُ الصَّادِرَاتُ النِّفْطِيَّةُ ---- الْأَسَاسِيَّ", "Petrol ihracatı temel ---- oluşturmaktadır"),
     ("لِلدَّخْلِ الْقَوْمِيِّ", "millî gelirin"),
     ("فِي كَثِيرٍ مِنْ دُوَلِ الْخَلِيجِ الْعَرَبِيِّ", "Arap Körfezi'ndeki pek çok ülkede.")],
 a2=["Boşluğa gelecek kelime تُمَثِّلُ fiilinin mef‘ûlüdür ve الْأَسَاسِيَّ ile nitelenmiştir; müzekker ve belirli olmalıdır. Bütün şıklar bu şartı taşır; ayrım anlamdadır.",
     "Cümlede petrol ihracatının millî gelirle ilişkisi anlatılıyor. Körfez ülkelerinde petrol gelirin ana kaynağıdır; dolayısıyla “kaynak, besleyen unsur” anlamında bir kelime aranmalıdır.",
     "الْمُسْتَفِيدُ (yararlanan) rolleri tersine çevirir: ihracat gelirden yararlanan değil, geliri sağlayan unsurdur. الْهَامِشُ (kenar, önemsiz kısım) ile الْأَسَاسِيُّ çelişkili bir ifade oluşturur. الْمَصَبُّ (nehrin döküldüğü yer), الرَّافِد ile aynı mecaz alanından gelen güçlü bir çeldiricidir; ancak “suyun aktığı son nokta” anlamı verir, oysa ihracat gelire akan kaynaktır. الْعِبْءُ (yük) ise geliri artıran bir unsurla bağdaşmaz.",
     "الرَّافِدُ asıl olarak “ana nehri besleyen kol” demektir; mecazen “bir şeyi besleyen kaynak” anlamında kullanılır: الرَّافِدُ الْأَسَاسِيُّ لِلدَّخْلِ “gelirin temel kaynağı”. Bu C1 düzeyinde bir mecaz kullanımdır."]),
]

SECTIONS.append(dict(
    rng=(9, 15),
    title="DİL BİLGİSİ, BAĞLAÇLAR VE YAPILAR",
    instr="9.-15. sorularda, cümlede boş bırakılan yerlere uygun düşen sözcük veya ifadeyi bulunuz.",
    skill="Bu bölüm; ism-i mevsûl, nasb ve cezm edatları, mukârabe fiilleri, sayılar, mef‘ûlün leh ve bağlaçlar gibi temel yapıların cümle içindeki işlevini ve i‘rab uyumunu ölçer.",
    strategy="Şıklar genellikle aynı kelimenin farklı çekimleri veya aynı işlevdeki bağlaçlardır; bu nedenle önce boşluğun cümledeki görevini (sıfat mı, fiil mi, bağlaç mı) tespit edin. Ardından sayı, cinsiyet ve i‘rab uyumunu kontrol edin; bağlaç sorularında cümlenin iki tarafı arasındaki mantıksal ilişkiyi (zıtlık, sebep, şart, orantı) adlandırın.",
))

Q += [
dict(n=9,
 stem="إن الباحثتين ---- شاركتا في المؤتمر الدولي قدمتا دراسة متميزة عن تأثير الملوحة في خصوبة التربة.",
 opts=["اللتان", "اللذين", "اللاتي", "اللتين", "الذين"], ans="D", key="اللَّتَيْنِ",
 a1=[("إِنَّ الْبَاحِثَتَيْنِ ----", "Şüphesiz ki ... iki (kadın) araştırmacı"),
     ("شَارَكَتَا فِي الْمُؤْتَمَرِ الدَّوْلِيِّ", "uluslararası konferansa katılan"),
     ("قَدَّمَتَا دِرَاسَةً مُتَمَيِّزَةً عَنْ تَأْثِيرِ الْمُلُوحَةِ فِي خُصُوبَةِ التُّرْبَةِ", "tuzluluğun toprak verimliliğine etkisi hakkında seçkin bir çalışma sundular.")],
 a2=["الْبَاحِثَتَيْنِ kelimesi إِنَّ edatının ismidir ve mansuptur; müennes tesniye olduğundan nasbı “ـَيْنِ” ile olur. شَارَكَتَا fiilindeki “ـتَا” eki de müennes tesniyeyi gösterir.",
     "İsm-i mevsûl, açıkladığı isme sayı, cinsiyet ve i‘rab bakımından uyar. Burada ism-i mevsûl الْبَاحِثَتَيْنِ kelimesinin sıfatıdır (نَعْت); dolayısıyla müennes tesniye ve mansup olmalıdır: اللَّتَيْنِ.",
     "اللَّتَانِ müennes tesniyedir ama merfûdur; إِنَّ'nin ismine sıfat olduğu için burada kullanılamaz. Bu şık en güçlü çeldiricidir. اللَّذَيْنِ müzekker tesniye (mansup), اللَّاتِي müennes çoğul, الَّذِينَ müzekker çoğuldur; cinsiyet veya sayı bakımından uyumsuzdur.",
     "Cümlenin haberi قَدَّمَتَا fiil cümlesidir (خَبَرُ إِنَّ جُمْلَةٌ فِعْلِيَّةٌ). Sıla cümlesi ise شَارَكَتَا ... cümlesidir ve i‘rabda mahalli yoktur."]),

dict(n=10,
 stem="---- اجتهد الطالب في دراسته، ازدادت فرص نجاحه في الامتحانات المصيرية.",
 opts=["لو أن", "كلما", "لئلا", "ريثما", "بينما"], ans="B", key="كُلَّمَا",
 a1=[("---- اجْتَهَدَ الطَّالِبُ فِي دِرَاسَتِهِ", "Öğrenci derslerinde ---- çalıştı"),
     ("ازْدَادَتْ فُرَصُ نَجَاحِهِ فِي الِامْتِحَانَاتِ الْمَصِيرِيَّةِ", "kader belirleyici sınavlarda başarı şansı arttı.")],
 a2=["Cümle iki fiil cümlesinden oluşuyor ve ikincisi birincinin sonucu gibi duruyor: “çalışma arttıkça başarı şansı artar”. Bu, orantı (tenâsüb) ilişkisidir.",
     "كُلَّمَا “...dıkça” anlamında zaman bildiren bir şart benzeri yapıdır; ardından mazi fiil gelir, cevabı da mazi fiildir ve başına فَـ almaz: كُلَّمَا اجْتَهَدَ ... ازْدَادَتْ ...",
     "لَوْ أَنَّ ardından isim cümlesi ister ve cevabı genellikle لَـ ile gelir; burada ardından mazi fiil (اجْتَهَدَ) geldiği için yapı bozuktur. لِئَلَّا “...mesin diye” amaç bildirir ve muzari ister. رَيْثَمَا “...ıncaya kadar” anlamındadır ve genellikle muzari ile kullanılır. بَيْنَمَا “...iken / oysa” anlamında karşılaştırma bildirir ve iki cümle arasında orantı kurmaz.",
     "Dolayısıyla hem yapı hem anlam bakımından tek uygun seçenek كُلَّمَا'dır."]),

dict(n=11,
 stem="إن الباحثين لن ---- من الوصول إلى نتائج دقيقة ما لم يعتمدوا منهجا علميا صارما في دراساتهم.",
 opts=["يتمكنون", "تتمكنوا", "يتمكنا", "تتمكنون", "يتمكنوا"], ans="E", key="يَتَمَكَّنُوا",
 a1=[("إِنَّ الْبَاحِثِينَ لَنْ ----", "Şüphesiz araştırmacılar ---- olmayacaklar"),
     ("مِنَ الْوُصُولِ إِلَى نَتَائِجَ دَقِيقَةٍ", "kesin sonuçlara ulaşmaya (muktedir)"),
     ("مَا لَمْ يَعْتَمِدُوا مَنْهَجًا عِلْمِيًّا صَارِمًا فِي دِرَاسَاتِهِمْ", "çalışmalarında sıkı bir bilimsel yöntemi benimsemedikçe.")],
 a2=["Özne (الْبَاحِثِينَ) fiilden önce geldiği için fiil, özneye sayı ve cinsiyet bakımından tam uyar: müzekker çoğul üçüncü şahıs (هُمْ).",
     "لَنْ muzari fiili nasb eden bir edattır ve geleceği olumsuzlar. Ef‘âl-i hamse (beş fiil) grubundaki يَتَمَكَّنُونَ nasb edildiğinde sonundaki نُون düşer: لَنْ يَتَمَكَّنُوا.",
     "يَتَمَكَّنُونَ merfûdur; لَنْ'den sonra nasbın gerektirdiği نُون düşmesi olmadığı için yanlıştır. تَتَمَكَّنُوا ve تَتَمَكَّنُونَ ikinci şahıs (أَنْتُمْ) çekimidir; يَتَمَكَّنَا ise tesniyedir; bunlar özneyle uyuşmaz.",
     "Ayrıca مَا لَمْ يَعْتَمِدُوا ifadesinde لَمْ cezm edatıdır ve يَعْتَمِدُوا da نُون düşmesiyle meczumdur; iki yapıyı birbirine karıştırmamak gerekir."]),

dict(n=12,
 stem="ارتدى المتسلقون ملابس سميكة ---- من البرد القارس في أعالي الجبال.",
 opts=["رغبة", "أملا", "حذرا", "حرصا", "شوقا"], ans="C", key="حَذَرًا",
 a1=[("ارْتَدَى الْمُتَسَلِّقُونَ مَلَابِسَ سَمِيكَةً", "Dağcılar kalın elbiseler giydiler"),
     ("---- مِنَ الْبَرْدِ الْقَارِسِ", "dondurucu soğuktan ----"),
     ("فِي أَعَالِي الْجِبَالِ", "dağların zirvelerindeki.")],
 a2=["Boşluktaki kelime, fiilin sebebini bildiren mef‘ûlün lehtir (مَفْعُولٌ لِأَجْلِهِ) ve mansuptur. Bütün şıklar mansup mastar olduğu için yapı bakımından paraleldir; ayrım, mastarın hangi harf-i cerle kullanıldığındadır.",
     "Boşluktan sonra مِنْ harf-i ceri geliyor. حَذَرٌ مِنْ “...den sakınmak” kalıbı hem anlam hem harf-i cer bakımından cümleye uyar: soğuktan korunmak için kalın giysiler giyildi.",
     "رَغْبَةً فِي (arzu ederek), أَمَلًا فِي (umarak), حِرْصًا عَلَى (özen göstererek), شَوْقًا إِلَى (özlemle) kalıplarıyla kullanılır. مِنْ ile uyumsuz oldukları gibi “soğuğu arzu ederek / özleyerek” gibi mantıksız anlamlar da doğururlar.",
     "Kelime notu: الْبَرْدُ الْقَارِسُ = dondurucu soğuk; أَعَالِي الْجِبَالِ = dağların yüksek kesimleri."]),

dict(n=13,
 stem="كادت الشركة ---- بعد الخسائر الفادحة التي منيت بها، لولا تدخل مستثمرين جدد في اللحظة الأخيرة.",
 opts=["تفلس", "أفلست", "إفلاسا", "مفلسة", "قد أفلست"], ans="A", key="تُفْلِسُ",
 a1=[("كَادَتِ الشَّرِكَةُ ----", "Şirket neredeyse ----"),
     ("بَعْدَ الْخَسَائِرِ الْفَادِحَةِ الَّتِي مُنِيَتْ بِهَا", "uğradığı ağır kayıplardan sonra"),
     ("لَوْلَا تَدَخُّلُ مُسْتَثْمِرِينَ جُدُدٍ فِي اللَّحْظَةِ الْأَخِيرَةِ", "son anda yeni yatırımcıların müdahalesi olmasaydı.")],
 a2=["كَادَ, mukârabe (yaklaşma) fiillerindendir ve كَانَ gibi amel eder: ismi merfû (الشَّرِكَةُ), haberi ise muzari fiil cümlesi olur. Standart kullanımda كَادَ'nın haberi أَنْ almadan gelen muzari fiildir: كَادَتِ الشَّرِكَةُ تُفْلِسُ.",
     "أَفْلَسَتْ ve قَدْ أَفْلَسَتْ mazi fiildir; mukârabe fiillerinin haberi mazi olamaz. إِفْلَاسًا mastar, مُفْلِسَةً ism-i fâildir; كَادَ'nın haberi müfred isim olarak gelmez.",
     "Anlam: “neredeyse iflas edecekti, ama olmadı”. لَوْلَا “...olmasaydı” anlamında imtina bildirir; ardından gelen isim (تَدَخُّلُ) mübtedâdır ve haberi hazfedilmiştir. Bu yapı, iflasın gerçekleşmediğini doğrular.",
     "Kelime notu: مُنِيَ بِـ = ...e uğramak (kayıp, yenilgi); خَسَائِرُ فَادِحَةٌ = ağır kayıplar."]),

dict(n=14,
 stem="يحرص الأطباء على سلامة المرضى جميعا، ---- كبار السن الذين يعانون من أمراض مزمنة.",
 opts=["لكن", "بل", "أي", "لا سيما", "إلا أن"], ans="D", key="لَا سِيَّمَا",
 a1=[("يَحْرِصُ الْأَطِبَّاءُ عَلَى سَلَامَةِ الْمَرْضَى جَمِيعًا", "Doktorlar tüm hastaların sağlığına özen gösterir"),
     ("---- كِبَارِ السِّنِّ", "---- yaşlılara"),
     ("الَّذِينَ يُعَانُونَ مِنْ أَمْرَاضٍ مُزْمِنَةٍ", "kronik hastalıklardan muzdarip olan.")],
 a2=["Cümlenin ilk kısmı genel bir hüküm veriyor: “bütün hastalar”. İkinci kısım ise bu genel grubun içinden özel bir grubu (yaşlılar) öne çıkarıyor. Bu ilişki “özellikle” anlamıyla kurulur.",
     "لَا سِيَّمَا “özellikle, bilhassa” demektir ve kendisinden sonraki ismi önceki hükümde öncelikli kılar. Ardından gelen isim çoğunlukla mecrur okunur (لَا سِيَّمَا كِبَارِ السِّنِّ); buradaki مَا zâidedir ve isim سِيِّ'ye muzâfun ileyh olur.",
     "لَكِنْ ve إِلَّا أَنَّ zıtlık bildirir; oysa yaşlılara gösterilen özen, genel hükümle çelişmez. بَلْ “bilakis” anlamında önceki hükmü düzeltir; “bütün hastalar” hükmünü iptal etmek anlamsızdır. أَيْ “yani” açıklama edatıdır; “bütün hastalar, yani yaşlılar” denirse hüküm yaşlılarla sınırlanır ve جَمِيعًا ile çelişir.",
     "Not: إِلَّا أَنَّ'den sonra bir cümle gelmesi gerekir; burada ise yalnızca bir isim tamlaması vardır. Bu, şıkkı yapı bakımından da geçersiz kılar."]),

dict(n=15,
 stem="استغرق بناء الجسر ---- سنة بسبب صعوبة التضاريس ووعورة المنطقة.",
 opts=["اثني عشر", "اثنا عشرة", "اثنتي عشرة", "اثنتا عشر", "اثنتا عشرة"], ans="C", key="اثْنَتَيْ عَشْرَةَ",
 a1=[("اسْتَغْرَقَ بِنَاءُ الْجِسْرِ ---- سَنَةً", "Köprünün yapımı ---- yıl sürdü"),
     ("بِسَبَبِ صُعُوبَةِ التَّضَارِيسِ وَوُعُورَةِ الْمِنْطَقَةِ", "arazi şeklinin zorluğu ve bölgenin sarplığı nedeniyle.")],
 a2=["اسْتَغْرَقَ fiilinin fâili بِنَاءُ, mef‘ûlü ise boşluğa gelecek sayıdır; dolayısıyla sayı mansup olmalıdır.",
     "Temyiz (sayılan) سَنَةً kelimesidir ve müennestir. 12 sayısında her iki parça da temyize cinsiyet bakımından uyar: müennes için اثْنَتَا عَشْرَةَ (merfû), اثْنَتَيْ عَشْرَةَ (mansup / mecrur). 11-19 arası sayılarda temyiz mansup ve tekil gelir: سَنَةً.",
     "اثْنَتَا عَشْرَةَ doğru cinsiyettedir ama merfûdur; mef‘ûl konumunda olduğu için yanlıştır (en güçlü çeldirici). اثْنَيْ عَشَرَ müzekkerdir. اثْنَا عَشْرَةَ ve اثْنَتَا عَشَرَ ise iki parçanın cinsiyetinin birbirine uymadığı bozuk yapılardır.",
     "Hatırlatma: 12 sayısının ilk parçası (اثْنَا / اثْنَتَا) müsenna gibi i‘rab edilir; ikinci parça (عَشَرَ / عَشْرَةَ) fetha üzere mebnidir."]),
]

SECTIONS.append(dict(
    rng=(16, 20),
    title="PARAGRAFTA BOŞLUK DOLDURMA (Cloze Test)",
    instr="16.-20. sorularda, aşağıdaki parçada numaralanmış yerlere uygun düşen sözcük veya ifadeyi bulunuz.",
    skill="Bu bölüm; tek bir paragraf içinde bağlaç, harf-i cer, fiil ve mastar seçimini metnin bütünlüğü içinde yapabilme becerisini ölçer. Soru yalnızca cümleye değil, paragrafın düşünce akışına dayanır.",
    strategy="Önce paragrafın tamamını hızlıca okuyup konu ve yön değişimlerini belirleyin. Harf-i cer sorularında boşluktan önceki fiilin hangi harf-i cerle kullanıldığını, bağlaç sorularında ise boşluktan önceki ve sonraki cümlelerin mantıksal ilişkisini tespit edin.",
    passage="يؤدي النحل دورا محوريا في استمرار الحياة على كوكب الأرض، إذ يسهم في تلقيح نسبة كبيرة من المحاصيل الزراعية التي يعتمد عليها الإنسان في غذائه. (16) ---- هذه الأهمية البالغة، تشير الدراسات الحديثة إلى تراجع ملحوظ في أعداد النحل في مناطق كثيرة من العالم. ويعزو العلماء هذا التراجع (17) ---- عوامل متعددة، أبرزها الاستخدام المفرط للمبيدات الكيميائية وفقدان الموائل الطبيعية. ولا (18) ---- خطر هذه الظاهرة على الجانب البيئي، بل يمتد ليشمل الأمن الغذائي العالمي، (19) ---- إن انخفاض أعداد الملقحات قد يؤدي إلى تراجع إنتاج كثير من الفواكه والخضراوات. ولذلك تدعو المنظمات البيئية إلى (20) ---- إجراءات عاجلة لحماية النحل، مثل الحد من استخدام المبيدات وزراعة النباتات المزهرة على نطاق واسع.",
    passage_tr="Paragraf, arıların tarım ürünlerini tozlaştırarak yaşamın sürmesindeki merkezî rolünü, bu öneme rağmen sayılarının azaldığını, azalmanın sebeplerini (tarım ilaçları ve habitat kaybı), bu durumun yalnızca çevreyi değil küresel gıda güvenliğini de tehdit ettiğini ve alınması gereken acil önlemleri anlatıyor.",
))

Q += [
dict(n=16, stem="", opts=["بفضل", "رغم", "نظرا إلى", "بسبب", "بناء على"], ans="B", key="رَغْمَ",
 a1=[("(16) ---- هَذِهِ الْأَهَمِّيَّةِ الْبَالِغَةِ", "Bu büyük öneme ----"),
     ("تُشِيرُ الدِّرَاسَاتُ الْحَدِيثَةُ إِلَى تَرَاجُعٍ مَلْحُوظٍ فِي أَعْدَادِ النَّحْلِ", "son çalışmalar arı sayısında belirgin bir düşüşe işaret ediyor.")],
 a2=["Birinci cümle arıların büyük önemini anlatıyor; ikinci cümle ise sayılarının azaldığını söylüyor. “Önemli olmasına rağmen azalıyor” şeklinde bir zıtlık (istidrâk) ilişkisi var.",
     "رَغْمَ (عَلَى الرَّغْمِ مِنْ) “...e rağmen” anlamındadır; ardından gelen isim muzâfun ileyh olarak mecrurdur: رَغْمَ هَذِهِ الْأَهَمِّيَّةِ.",
     "بِفَضْلِ (sayesinde), بِسَبَبِ (yüzünden), نَظَرًا إِلَى (...den dolayı), بِنَاءً عَلَى (...e dayanarak) sebep bildirir. “Önemi sayesinde / yüzünden sayıları azalıyor” mantıksız bir sebep-sonuç ilişkisi kurar."]),
dict(n=17, stem="", opts=["على", "في", "عن", "من", "إلى"], ans="E", key="إِلَى",
 a1=[("وَيَعْزُو الْعُلَمَاءُ هَذَا التَّرَاجُعَ (17) ---- عَوَامِلَ مُتَعَدِّدَةٍ", "Bilim insanları bu düşüşü çeşitli etkenlere bağlıyor")],
 a2=["Bu soru bir fiil + harf-i cer eşdizimini ölçüyor. عَزَا – يَعْزُو fiili “bir şeyi bir sebebe bağlamak, ona nispet etmek” anlamındadır ve إِلَى ile kullanılır: عَزَا الْأَمْرَ إِلَى كَذَا.",
     "هَذَا التَّرَاجُعَ fiilin mef‘ûlüdür (mansup); عَوَامِلَ ise إِلَى ile mecrurdur, gayr-i munsarif olduğu için cerri fetha ile yapılır (عَوَامِلَ).",
     "عَلَى, فِي, عَنْ, مِنْ harfleri bu fiille “bağlamak / nispet etmek” anlamını vermez. Aynı anlamdaki diğer kalıplar: أَرْجَعَ ... إِلَى, رَدَّ ... إِلَى."]),
dict(n=18, stem="", opts=["يقتصر", "يعتمد", "يترتب", "يحرص", "يستند"], ans="A", key="يَقْتَصِرُ",
 a1=[("وَلَا (18) ---- خَطَرُ هَذِهِ الظَّاهِرَةِ عَلَى الْجَانِبِ الْبِيئِيِّ", "Bu olgunun tehlikesi çevresel boyutla ---- değildir"),
     ("بَلْ يَمْتَدُّ لِيَشْمَلَ الْأَمْنَ الْغِذَائِيَّ الْعَالَمِيَّ", "bilakis küresel gıda güvenliğini de kapsayacak şekilde genişler.")],
 a2=["Çözümün anahtarı لَا ... بَلْ yapısıdır: “yalnızca şununla sınırlı değil, bilakis şunu da kapsar”. Bu yapı Arapçada لَا يَقْتَصِرُ ... عَلَى ... بَلْ ... kalıbıyla kurulur.",
     "يَقْتَصِرُ عَلَى “...ile sınırlı kalmak” demektir; ardından gelen بَلْ يَمْتَدُّ (bilakis genişler) ifadesiyle tam bir anlam bütünlüğü oluşur.",
     "يَعْتَمِدُ عَلَى (dayanmak), يَسْتَنِدُ إِلَى (dayanmak), يَحْرِصُ عَلَى (özen göstermek), يَتَرَتَّبُ عَلَى (sonucu olmak) fiilleri “sınırlılık” anlamı taşımadığı için بَلْ يَمْتَدُّ ile anlamlı bir karşıtlık kurmaz. (يَسْتَنِدُ hem إِلَى hem عَلَى ile kullanılabilir; ancak her iki durumda da “dayanmak” anlamı verir.)"]),
dict(n=19, stem="", opts=["مع أن", "لكي", "لئلا", "إذ", "لو"], ans="D", key="إِذْ",
 a1=[("(19) ---- إِنَّ انْخِفَاضَ أَعْدَادِ الْمُلَقِّحَاتِ", "---- tozlayıcıların sayısındaki azalma"),
     ("قَدْ يُؤَدِّي إِلَى تَرَاجُعِ إِنْتَاجِ كَثِيرٍ مِنَ الْفَوَاكِهِ وَالْخَضْرَاوَاتِ", "pek çok meyve ve sebzenin üretiminde düşüşe yol açabilir.")],
 a2=["Boşluktan sonra gelen cümle, bir önceki iddianın (tehlikenin gıda güvenliğini de kapsadığı) gerekçesini veriyor. Gerekçe bildiren kalıp إِذْ إِنَّ “çünkü”dür. إِذْ'den sonra إِنَّ'nin hemzesi kesreli okunur.",
     "مَعَ أَنَّ “...e rağmen” zıtlık bildirir ve kendisinden sonra ayrıca إِنَّ gelmez. لِكَيْ ve لِئَلَّا amaç bildirir ve muzari fiil ister (ardından إِنَّ gelemez); لَوْ ise varsayım bildirir ve cevap ister. Bu şıklar hem anlam hem yapı bakımından uygun değildir."]),
dict(n=20, stem="", opts=["إرجاء", "تجميد", "اتخاذ", "إلغاء", "تعليق"], ans="C", key="اتِّخَاذِ",
 a1=[("وَلِذَلِكَ تَدْعُو الْمُنَظَّمَاتُ الْبِيئِيَّةُ إِلَى (20) ---- إِجْرَاءَاتٍ عَاجِلَةٍ", "Bu nedenle çevre örgütleri acil önlemler ---- çağırıyor"),
     ("لِحِمَايَةِ النَّحْلِ", "arıları korumak için.")],
 a2=["وَلِذَلِكَ (bu nedenle) ifadesi paragrafın sonuç bölümünü başlatıyor. Arılar tehlikedeyse çevre örgütleri önlem alınmasını ister.",
     "اتِّخَاذُ إِجْرَاءَاتٍ “önlem almak” Arapçada kalıplaşmış bir eşdizimdir (اتَّخَذَ قَرَارًا / إِجْرَاءً). Kelime إِلَى ile mecrurdur ve إِجْرَاءَاتٍ kelimesine muzâftır.",
     "إِرْجَاءٌ (ertelemek), تَجْمِيدٌ (dondurmak), إِلْغَاءٌ (iptal etmek), تَعْلِيقٌ (askıya almak) anlamındadır. “Arıları korumak için acil önlemleri ertelemeye çağırmak” paragrafın mantığıyla çelişir; üstelik عَاجِلَةٍ (acil) sıfatı da bu seçenekleri dışlar."]),
]

SECTIONS.append(dict(
    rng=(21, 28),
    title="CÜMLE TAMAMLAMA",
    instr="21.-28. sorularda, verilen cümleyi uygun şekilde tamamlayan ifadeyi bulunuz.",
    skill="Bu bölüm; cümlenin verilen kısmındaki bağlaç, şart edatı veya zaman yapısına göre anlamca ve yapıca uyumlu devamı bulabilme becerisini ölçer.",
    strategy="Önce verilen kısımdaki yön belirleyici unsuru (عَلَى الرَّغْمِ مِنْ, لَوْ, كُلَّمَا, مَا إِنْ, بَلْ, لِذَلِكَ gibi) tespit edin; bu unsur, devamında hangi mantıksal ilişkinin gelmesi gerektiğini söyler. Sonra zaman uyumu ve zamirlerin dönüş yerini kontrol ederek tek başına doğru görünen ama cümleye bağlanamayan şıkları eleyin.",
))

Q += [
dict(n=21,
 stem="لو أدركت المجتمعات القديمة أهمية الحفاظ على الغابات، ----.",
 opts=["فإنها تسعى اليوم إلى زراعة ملايين الأشجار سنويا",
       "إذ كانت تعتمد على الأخشاب في البناء والتدفئة",
       "كما أن الغابات تغطي مساحات واسعة من اليابسة",
       "لما تعرضت مساحات شاسعة منها للتصحر",
       "مع أن التصحر ظاهرة طبيعية في بعض المناطق"], ans="D", key="لَمَا تَعَرَّضَتْ مِسَاحَاتٌ شَاسِعَةٌ مِنْهَا لِلتَّصَحُّرِ",
 a1=[("لَوْ أَدْرَكَتِ الْمُجْتَمَعَاتُ الْقَدِيمَةُ أَهَمِّيَّةَ الْحِفَاظِ عَلَى الْغَابَاتِ", "Eski toplumlar ormanları korumanın önemini kavrasaydı ...")],
 a2=["لَوْ, gerçekleşmemiş bir durumu varsayan imtina edatıdır (حَرْفُ امْتِنَاعٍ لِامْتِنَاعٍ). Cevabı mazi fiille gelir; olumlu cevap لَـ, olumsuz cevap ise مَا ile (çoğunlukla لَمَا) kurulur.",
     "D şıkkında لَمَا تَعَرَّضَتْ “maruz kalmazdı” olumsuz cevap yapısı tam olarak bulunuyor: “Eski toplumlar ormanları korumanın önemini kavrasaydı, geniş alanlar çölleşmeye maruz kalmazdı.” مِنْهَا zamiri الْغَابَاتِ kelimesine döner.",
     "A şıkkı فَإِنَّهَا تَسْعَى ile şimdiki zamanda bir cümle kurar; لَوْ'nun cevabı فَإِنَّ ile gelmez. B (إِذْ) gerekçe, C (كَمَا) ekleme, E (مَعَ أَنَّ) zıtlık bildirir; hiçbiri لَوْ'nun istediği cevap cümlesini oluşturmaz.",
     "Ölçülen beceri: şart / imtina edatının cevap yapısını tanıma."]),

dict(n=22,
 stem="----، فإن تطبيقها على أرض الواقع يواجه عقبات إدارية ومالية كثيرة.",
 opts=["على الرغم من وضوح الأهداف التي تتضمنها خطط التنمية الحكومية",
       "بما أن الخطط الحكومية قد نفذت بنجاح تام في معظم القطاعات الخدمية والإنتاجية",
       "لأن المسؤولين يحرصون على متابعة المشروعات التنموية",
       "حتى تتمكن الحكومة من تحقيق أهدافها التنموية",
       "إذا توافر التمويل اللازم للمشروعات في الوقت المحدد"], ans="A", key="عَلَى الرَّغْمِ مِنْ وُضُوحِ الْأَهْدَافِ",
 a1=[("فَإِنَّ تَطْبِيقَهَا عَلَى أَرْضِ الْوَاقِعِ", "... onların uygulamaya konulması / sahada uygulanması"),
     ("يُوَاجِهُ عَقَبَاتٍ إِدَارِيَّةً وَمَالِيَّةً كَثِيرَةً", "pek çok idari ve mali engelle karşılaşmaktadır.")],
 a2=["Verilen kısım فَإِنَّ ile başlıyor. عَلَى الرَّغْمِ مِنْ ... فَإِنَّ ... “...e rağmen ... yine de ...” yapısı Arapçada çok yaygındır. Ayrıca تَطْبِيقَهَا'daki هَا zamiri müennes bir isme ya da akıl sahibi olmayan bir çoğula dönmelidir.",
     "A şıkkında خُطَطُ التَّنْمِيَةِ (kalkınma planları) zamirin döneceği ismi veriyor; “hedefleri açık olmasına rağmen planların uygulanması engellerle karşılaşıyor” anlamı hem mantıklı hem de yapı olarak tamdır.",
     "B şıkkı planların “başarıyla uygulandığını” söylediği için “uygulamada engellerle karşılaşıyor” ifadesiyle çelişir. C (لِأَنَّ) sebep bildirir, ama yetkililerin takibi engellerin nedeni olamaz. D (حَتَّى) amaç bildirir ve anlamsız bir ilişki kurar. E'de “finansman sağlanırsa uygulama engellerle karşılaşır” denir ki mantığa ters bir şart ilişkisidir."]),

dict(n=23,
 stem="لم تعد الأمية في العصر الحديث مقتصرة على عدم القدرة على القراءة والكتابة، ----.",
 opts=["لذلك ألغت الدول برامج محو الأمية التقليدية",
       "إذ تراجعت معدلاتها في معظم دول العالم",
       "لأن التعليم أصبح إلزاميا في معظم الدول",
       "ومع ذلك تبقى القراءة المهارة الوحيدة المطلوبة في سوق العمل",
       "بل أصبحت تشمل العجز عن التعامل مع التقنيات الرقمية الحديثة"], ans="E", key="بَلْ أَصْبَحَتْ تَشْمَلُ",
 a1=[("لَمْ تَعُدِ الْأُمِّيَّةُ فِي الْعَصْرِ الْحَدِيثِ مُقْتَصِرَةً", "Modern çağda okuryazarlık eksikliği artık ... ile sınırlı değildir"),
     ("عَلَى عَدَمِ الْقُدْرَةِ عَلَى الْقِرَاءَةِ وَالْكِتَابَةِ", "okuma yazma bilmemekle.")],
 a2=["لَمْ يَعُدْ, “artık ... değil” anlamında كَانَ gibi amel eden bir fiildir: ismi الْأُمِّيَّةُ (merfû), haberi مُقْتَصِرَةً (mansup). Cümle, olumsuz bir sınırlama ile kuruluyor: “yalnızca ...dan ibaret değil”.",
     "Bu tür olumsuzlamadan sonra doğal devam بَلْ (bilakis) ile gelir ve kapsamı genişletir: “bilakis dijital teknolojilerle başa çıkamamayı da kapsar hâle geldi”. E şıkkı bu yapıyı birebir sağlar.",
     "A ve C şıkları konuyu okuryazarlık programlarına ve zorunlu eğitime kaydırır; “kavramın genişlemesi” düşüncesini tamamlamaz. B, okuma-yazma bilmeme oranlarının düştüğünü söyler; bu, kavramın sınırlı olmadığı iddiasının gerekçesi olamaz. D ise “okumanın tek beceri olduğunu” söyleyerek cümlenin ana fikriyle çelişir."]),

dict(n=24,
 stem="ما دام الإنسان يمارس الرياضة بانتظام، ----.",
 opts=["فقد كان يعاني من أمراض كثيرة في شبابه قبل أن يبدأ ممارستها",
       "فإنه يحافظ على لياقته وصحته",
       "لم يكن بحاجة إلى متابعة حالته الصحية في شبابه",
       "لأن الرياضة تستهلك جزءا كبيرا من وقته اليومي",
       "إلا أن كثيرا من الناس يهملون ممارستها بسبب ضغوط العمل"], ans="B", key="فَإِنَّهُ يُحَافِظُ عَلَى لِيَاقَتِهِ وَصِحَّتِهِ",
 a1=[("مَا دَامَ الْإِنْسَانُ يُمَارِسُ الرِّيَاضَةَ بِانْتِظَامٍ", "İnsan düzenli olarak spor yaptığı sürece ...")],
 a2=["مَا دَامَ burada “...dığı sürece / ...dığına göre” anlamında şart bildiren bir yapıdır (zaman bildiren masdar مَا + دَامَ). Kendisinden sonraki durum devam ettikçe cevaptaki hükmün de geçerli olduğunu bildirir. Cevap إِنَّ ile başlayan bir isim cümlesi olduğunda başına فَـ alır: مَا دَامَ ... فَإِنَّهُ ...",
     "B şıkkı “formunu ve sağlığını korur” diyerek hem yapıyı (فَإِنَّهُ) hem de anlamı (düzenli spor → sağlığın korunması) tamamlar. هُ zamiri الْإِنْسَانُ kelimesine döner. Bu soruda doğru şık en kısa şıktır; uzun şıkkın doğru olacağı gibi bir kural yoktur.",
     "A şıkkı فَقَدْ كَانَ ile geçmişte kalmış bir durumu anlatır; مَا دَامَ'nın bildirdiği süregelen şartla zaman bakımından uyuşmaz. C (لَمْ يَكُنْ ... فِي شَبَابِهِ) da geçmişe gider ve şartla ilgisizdir. D (لِأَنَّ) cevap değil gerekçe bildirir ve anlamsız bir gerekçedir. E (إِلَّا أَنَّ) konuyu başka insanlara kaydırır ve şarta zıtlık kurar."]),

dict(n=25,
 stem="----، ولذلك يحرص المزارعون على تنويع محاصيلهم وعدم الاعتماد على نوع واحد.",
 opts=["تتميز التربة الزراعية في هذه المنطقة بخصوبتها العالية ووفرة مياهها الجوفية",
       "ارتفعت أسعار المحاصيل الزراعية في الأسواق المحلية",
       "تستنزف زراعة المحصول الواحد عناصر التربة وتزيد تعرضها للآفات",
       "يفضل المستهلكون المنتجات المحلية على المنتجات المستوردة",
       "تدعم الحكومة المزارعين بالقروض الميسرة والأسمدة والبذور المحسنة كل عام"], ans="C", key="تَسْتَنْزِفُ زِرَاعَةُ الْمَحْصُولِ الْوَاحِدِ",
 a1=[("وَلِذَلِكَ يَحْرِصُ الْمُزَارِعُونَ عَلَى تَنْوِيعِ مَحَاصِيلِهِمْ", "Bu nedenle çiftçiler ürünlerini çeşitlendirmeye özen gösterir"),
     ("وَعَدَمِ الِاعْتِمَادِ عَلَى نَوْعٍ وَاحِدٍ", "ve tek bir türe bağlı kalmamaya.")],
 a2=["وَلِذَلِكَ (bu nedenle), boşluktaki cümlenin sonucun sebebi olması gerektiğini gösterir. Sonuç: çiftçiler ürün çeşitlendirmeye önem veriyor. O hâlde sebep, tek ürüne bağlı kalmanın zararıyla ilgili olmalıdır.",
     "C şıkkı “tek bir ürünün ekilmesi toprağın besin öğelerini tüketir ve onu zararlılara karşı daha savunmasız hâle getirir” diyerek sonucu doğrudan açıklar. Burada زِرَاعَةُ, تَسْتَنْزِفُ fiilinin fâilidir; تَزِيدُ fiili de aynı fâile atfedilmiştir.",
     "A (toprağın verimli olması), B (fiyatların artması), D (tüketici tercihi), E (devlet desteği) doğru olabilecek bilgiler olsa da hiçbiri “tek ürüne bağlı kalmama” kararının gerekçesi değildir. Bu soruda doğru bilgi ile doğru sebep arasındaki farkı görmek önemlidir."]),

dict(n=26,
 stem="يعد الإيثار من أسمى القيم الإنسانية، ----.",
 opts=["إذ يقدم فيه المرء مصلحة غيره على مصلحته الشخصية",
       "لأنه يدفع الإنسان إلى تفضيل منفعته على منافع الآخرين",
       "ولذلك نادرا ما تحث عليه الأديان والفلسفات الأخلاقية",
       "مع أنه يقوم على مساعدة الآخرين دون انتظار مقابل",
       "حتى إن المجتمعات الحديثة لم تعد تقدره"], ans="A", key="إِذْ يُقَدِّمُ فِيهِ الْمَرْءُ",
 a1=[("يُعَدُّ الْإِيثَارُ مِنْ أَسْمَى الْقِيَمِ الْإِنْسَانِيَّةِ", "Îsâr (fedakârlık / başkasını kendine tercih etme) en yüce insani değerlerden biri sayılır ...")],
 a2=["Verilen cümle bir değer yargısı bildiriyor: îsâr en yüce değerlerdendir. Doğal devam, bu yargının gerekçesini açıklayan bir ifadedir. Gerekçe bildiren إِذْ bu işlevi görür.",
     "A şıkkı îsârın tanımını vererek yüceliğini açıklar: “insanın başkasının çıkarını kendi çıkarından önde tutması”. فِيهِ zamiri الْإِيثَارُ kelimesine döner.",
     "B şıkkı îsârın tam tersini (bencilliği) anlatır. C (“dinler ve ahlak felsefeleri onu nadiren teşvik eder”) değer yargısıyla çelişir. D'deki مَعَ أَنَّ zıtlık bildirir; oysa “karşılık beklemeden yardım etmek” îsârın yüceliğiyle zıt değil, onun gerekçesidir. E ise “modern toplumlar artık ona değer vermiyor” diyerek anlam bütünlüğünü bozar.",
     "Kelime notu: أَسْمَى (en yüce) ism-i tafdildir; مِنْ أَسْمَى “en yücelerinden” yapısında tafdil, muzâf olarak kullanılmıştır."]),

dict(n=27,
 stem="ما إن أعلن الحكم نهاية المباراة ----.",
 opts=["حتى يغادر اللاعبون الملعب بهدوء بعد ساعات من انتهائها",
       "فإن الجمهور سيحتفل بالفوز طويلا",
       "لكن اللاعبين واصلوا اللعب بحماس",
       "لذلك تأجلت المباراة إلى الأسبوع المقبل",
       "حتى انطلقت الجماهير في الاحتفال بفوز فريقها"], ans="E", key="حَتَّى انْطَلَقَتِ الْجَمَاهِيرُ",
 a1=[("مَا إِنْ أَعْلَنَ الْحَكَمُ نِهَايَةَ الْمُبَارَاةِ", "Hakem maçın bittiğini ilan eder etmez ...")],
 a2=["مَا إِنْ ... حَتَّى ... “...er ...mez” anlamında, iki olayın art arda ve hemen gerçekleştiğini bildiren kalıplaşmış bir yapıdır. Birinci kısımda mazi fiil geldiği için ikinci kısım da حَتَّى + mazi fiil ile gelir.",
     "E şıkkı bu kalıbı tam olarak tamamlar: “Hakem maçın bittiğini ilan eder etmez taraftarlar takımlarının galibiyetini kutlamaya koyuldu.” انْطَلَقَ فِي “...e koyulmak, başlamak” anlamındadır.",
     "A şıkkında حَتَّى var, ancak muzari fiil ve بَعْدَ سَاعَاتٍ (saatler sonra) ifadesi “hemen ardından” anlamıyla çelişir; bu şık en güçlü çeldiricidir. B (فَإِنَّ + gelecek zaman), C (لَكِنْ), D (لِذَلِكَ) ise kalıbın gerektirdiği حَتَّى'yı içermez ve anlamca da uyumsuzdur (maç bittikten sonra oynamaya devam etmek ya da maçın ertelenmesi)."]),

dict(n=28,
 stem="تشير الإحصاءات إلى أن معدلات القراءة بين الشباب قد انخفضت في العقد الأخير، ----.",
 opts=["مما يدل على ازدياد اهتمامهم بالكتب الورقية",
       "لذلك ارتفعت مبيعات الكتب ارتفاعا كبيرا",
       "رغم انشغالهم الشديد بالأجهزة الرقمية ووسائل الترفيه الحديثة المختلفة",
       "ويعزو الباحثون ذلك إلى انشغالهم المتزايد بالأجهزة الرقمية",
       "لأن المكتبات العامة وفرت لهم كتبا مجانية"], ans="D", key="وَيَعْزُو الْبَاحِثُونَ ذَلِكَ",
 a1=[("تُشِيرُ الْإِحْصَاءَاتُ إِلَى أَنَّ مُعَدَّلَاتِ الْقِرَاءَةِ بَيْنَ الشَّبَابِ", "İstatistikler gençler arasındaki okuma oranlarının"),
     ("قَدِ انْخَفَضَتْ فِي الْعَقْدِ الْأَخِيرِ", "son on yılda düştüğüne işaret ediyor ...")],
 a2=["Cümlenin ilk kısmı olumsuz bir durumu (okuma oranlarının düşmesi) bildiriyor. Doğal devam ya bu düşüşün sebebi ya da sonucudur.",
     "D şıkkı düşüşün sebebini verir: “Araştırmacılar bunu gençlerin dijital cihazlarla giderek artan meşguliyetine bağlıyor.” ذَلِكَ işaret ismi okuma oranlarındaki düşüşe döner; يَعْزُو ... إِلَى kalıbı sebep bildirir.",
     "C şıkkı aynı bilgiyi içerse de رَغْمَ (rağmen) ile zıtlık kurar; oysa dijital meşguliyet düşüşün zıttı değil, sebebidir. Bu şık en güçlü çeldiricidir. A ve B, düşüşün tersini (ilginin / satışların artmasını) sonuç olarak gösterir. E, ücretsiz kitap sağlanmasını düşüşün sebebi olarak sunar ki mantıksızdır."]),
]
