import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('database enforces ownership, approval, admin access and paid request reservations',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to anon,authenticated,service_role;
 grant execute on function auth.uid() to authenticated,service_role;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant select,insert,delete on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
 await db.exec(readFileSync(new URL('../supabase/migrations/20260921_membership.sql',import.meta.url),'utf8'));
 const admin='00000000-0000-4000-8000-000000000001',a='00000000-0000-4000-8000-000000000002',b='00000000-0000-4000-8000-000000000003';
 await db.query(`insert into auth.users values ($1,'yunusemreyilmaz93@gmail.com',now(),'{}'),($2,'a@example.test',now(),'{"role":"admin","status":"approved"}'),($3,'b@example.test',now(),'{}')`,[admin,a,b]);
 const as=async(id:string)=>{await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`);};
 await as(a);
 assert.equal((await db.query<any>('select role,status from public.profiles')).rows[0].role,'teacher');
 await assert.rejects(db.exec(`insert into public.projects(id,data)values('a','{}')`));
 await assert.rejects(db.exec(`update public.profiles set role='admin'`));
 await assert.rejects(db.exec(`select public.admin_overview()`));
 await assert.rejects(db.query('select public.set_member_status($1,$2)',[a,'approved']));
 await as(admin);await db.query('select public.set_member_status($1,$2)',[a,'approved']);await db.query('select public.set_member_status($1,$2)',[b,'approved']);
 await as(a);await db.exec(`insert into public.projects(id,data)values('a','{"title":"Teacher A"}')`);
 await db.query(`insert into storage.objects(bucket_id,name)values('project-assets',$1)`,[a+'/a/sound']);
 await as(b);assert.equal((await db.exec(`select * from public.projects`))[0].rows.length,0);
 assert.equal((await db.exec(`select * from storage.objects`))[0].rows.length,0);
 assert.equal((await db.exec(`update public.projects set data='{}' where id='a' returning id`))[0].rows.length,0);
 await assert.rejects(db.query(`insert into public.projects(id,owner_id,data)values('spoof',$1,'{}')`,[a]));
 await assert.rejects(db.query(`insert into storage.objects(bucket_id,name)values('project-assets',$1)`,[a+'/a/spoof']));
 await assert.rejects(db.exec(`select public.record_video_export('a')`));
 await assert.rejects(db.query(`select public.reserve_voice($1,'a',100)`,[a]));
 await as(a);await db.exec(`select public.record_video_export('a')`);
 await as(admin);const overview=(await db.query<any>('select public.admin_overview() result')).rows[0].result;
 assert.equal(overview.members.find((m:any)=>m.id===a).questions,1);assert.equal(overview.members.find((m:any)=>m.id===a).exports,1);
 await db.exec('reset role;set role service_role');
 await db.query(`select public.reserve_voice($1,'a',100)`,[a]);
 await assert.rejects(db.query(`select public.reserve_voice($1,'a',100)`,[a]));
 await assert.rejects(db.query(`select public.reserve_voice($1,'a',100)`,[b]));
 await as(admin);await db.query('select public.set_member_status($1,$2)',[a,'blocked']);
 await as(a);assert.equal((await db.exec(`select * from public.projects`))[0].rows.length,0);
 await assert.rejects(db.exec(`select public.record_video_export('a')`));
 await db.exec('reset role;set role service_role');await assert.rejects(db.query(`select public.reserve_voice($1,'a',100)`,[a]));
 await db.close();
});
