import {readProjectForOverview} from '../features/projects/cloudProjectRepository';
import {ProjectViewer} from '../features/projects/ProjectViewer';
import type {QuestionProject} from '../types';
import {projectRepository} from '../features/projects/projectRepository';
import {useProjects} from '../features/projects/ProjectContext';
import React,{useCallback,useEffect,useState} from 'react';
import {database} from '../services/supabase';
import {getCategoryLabel} from '../config/categories';
interface Member {id:string;email:string;name:string;role:string;status:string;questions:number;mock_questions:number;mock_exams:number;voice_attempts:number;voices:number;characters:number;exports:number;}
interface Overview {members:Member[];projects:Array<{id:string;owner_id:string;title:string;category:string;status:string;updated_at:string}>;activity:Array<{id:string;owner_id:string;kind:string;state:string;characters:number;created_at:string}>;}
const statuses:Record<string,string>={pending:'Onay bekliyor',approved:'Onaylı',blocked:'Durduruldu',draft:'Taslak',audio_generated:'Ses hazır',audio_approved:'Ses seçildi',video_ready:'Video hazır'};
export const AdminPage:React.FC=()=>{
 const {loadProjects}=useProjects();
 const [viewing,setViewing]=useState<QuestionProject|null>(null);
 const open=async(id:string)=>{setBusy(true);try{const p=await readProjectForOverview(id);if(!p)throw new Error('Proje bulunamadı.');setViewing(p);}catch(e){setError(e instanceof Error?e.message:'Proje açılamadı.');}finally{setBusy(false);}};
 const [importMessage,setImportMessage]=useState('');
 const importLegacy=async()=>{setBusy(true);try{const {data:{user}}=await database().auth.getUser();if(!user)throw new Error('Yeniden giriş yapın.');const raw=localStorage.getItem('arabic_ydt_teacher_projects_v2')||localStorage.getItem('arabic_ydt_teacher_projects_v1')||'[]';const projects=JSON.parse(raw);if(!Array.isArray(projects))throw new Error('Eski kayıt okunamadı.');let count=0;for(const p of projects){if(!p.id||!p.videoConfig||typeof p.solutionText!=='string')continue;const id=`legacy_${user.id}_${p.id}`;if(await projectRepository.getById(id))continue;await projectRepository.save({...p,id});count++;setImportMessage(`${count} proje aktarıldı…`);}setImportMessage(`${count} eski proje hesabınıza aktarıldı. Tarayıcıdaki kopyalar korundu.`);await loadProjects();await load();}catch(e){setError(e instanceof Error?e.message:'Aktarım tamamlanamadı.');}finally{setBusy(false);}};
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('');
 const load=useCallback(async()=>{setBusy(true);try{const {data,error}=await database().rpc('admin_overview');if(error)throw error;setData(data);setError('');}catch(e){setError(e instanceof Error?e.message:'Yönetim bilgileri alınamadı.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const change=async(id:string,status:string)=>{setBusy(true);setMessage('');try{const {error}=await database().rpc('set_member_status',{member_id:id,new_status:status});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Değişiklik kaydedilemedi.');}finally{setBusy(false);}};
 const promote=async(member:Member)=>{
  if(!window.confirm(`${member.name || member.email} kullanıcısına tam yönetici yetkisi verilsin mi? Yönetici tüm öğretmenleri ve projeleri görüntüleyebilir, üyelik erişimini yönetebilir.`))return;
  setBusy(true);setMessage('');
  try{
   const {error}=await database().rpc('set_member_role',{member_id:member.id,new_role:'admin'});
   if(error)throw error;
   setMessage(`${member.name || member.email} artık yönetici.`);
   await load();
  }catch(e){setError(e instanceof Error?e.message:'Yönetici yetkisi verilemedi.');}
  finally{setBusy(false);}
 };
 const who=(id:string)=>data?.members.find(m=>m.id===id)?.name||'Öğretmen';
 return <section className="p-6 space-y-6 max-w-7xl mx-auto">
  {viewing&&<ProjectViewer project={viewing} onClose={()=>setViewing(null)}/>}
  <div className="flex justify-between items-start"><div><h2 className="text-2xl font-bold">Stüdyo yönetimi</h2><p className="text-stone-500 text-sm mt-1">Üyelik erişimini yönetin, öğretmenlerin üretimlerini görüntüleyin. İçerikler için yönetici onayı gerekmez.</p></div><button disabled={busy} onClick={()=>void load()} className="border rounded px-4 py-2">{busy?'Yükleniyor…':'Yenile'}</button></div>
  {error&&<p role="alert" className="bg-red-50 text-red-800 p-3 rounded">{error}</p>}
  {message&&<p role="status" className="bg-green-50 text-green-800 p-3 rounded">{message}</p>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Öğretmen',data?.members.filter(m=>m.role==='teacher').length||0],['Onay bekleyen',data?.members.filter(m=>m.status==='pending').length||0],['Soru',data?.members.reduce((s,m)=>s+m.questions,0)||0],['Üretilen ses',data?.members.reduce((s,m)=>s+m.voices,0)||0]].map(([label,value])=><div key={label} className="bg-white border rounded-xl p-5"><p className="text-sm text-stone-500">{label}</p><strong className="text-3xl">{value}</strong></div>)}</div>
  <details className="bg-white border rounded-xl p-4 text-sm"><summary>Eski tarayıcı kayıtlarım</summary><p className="my-3">Önceki sürümde bu tarayıcıya kaydettiğiniz projeleri kendi yönetici hesabınıza aktarın. Daha önce aktarılanlar tekrar eklenmez.</p><button disabled={busy} className="border rounded p-2" onClick={()=>void importLegacy()}>Eski projelerimi aktar</button>{importMessage&&<p role="status" className="mt-2">{importMessage}</p>}</details>
  <section className="bg-white border rounded-xl overflow-hidden"><div className="p-4 flex flex-wrap justify-between gap-3"><h3 className="font-semibold">Üyeler ve üretim</h3><input aria-label="Öğretmen ara" placeholder="Ad veya e-posta ara" value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded p-2 text-sm"/></div>
   <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-stone-50"><tr>{['Öğretmen','Rol','Durum','Sorular','Deneme / soru','Ses / deneme','İstenen karakter','Video dışa aktarım','Erişim'].map(t=><th key={t} className="p-3 whitespace-nowrap">{t}</th>)}</tr></thead><tbody>{data?.members.filter(m=>(m.name+' '+m.email).toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr'))).map(m=><tr key={m.id} className="border-t"><td className="p-3"><div>{m.name}</div><div className="text-xs text-stone-500">{m.email}</div></td><td className="p-3"><span className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ${m.role==='admin'?'bg-[#F8EEEE] text-[#8B1E2D]':'bg-stone-100 text-stone-600'}`}>{m.role==='admin'?'Yönetici':'Öğretmen'}</span></td><td className="p-3">{statuses[m.status]||m.status}</td><td className="p-3">{m.questions}</td><td className="p-3">{m.mock_exams} / {m.mock_questions}</td><td className="p-3">{m.voices} / {m.voice_attempts}</td><td className="p-3">{m.characters.toLocaleString('tr')}</td><td className="p-3">{m.exports}</td><td className="p-3">{m.role!=='admin'?<div className="flex flex-wrap gap-2 items-center"><select aria-label={`${m.email} erişimi`} disabled={busy} value={m.status} onChange={e=>void change(m.id,e.target.value)} className="border rounded p-2"><option value="pending">Onay bekliyor</option><option value="approved">Onayla</option><option value="blocked">Durdur</option></select><button type="button" disabled={busy} onClick={()=>void promote(m)} className="border border-[#8B1E2D] text-[#8B1E2D] hover:bg-[#F8EEEE] rounded px-3 py-2 font-semibold whitespace-nowrap">Yönetici Yap</button></div>:<span className="text-xs text-stone-500">Tam yetki</span>}</td></tr>)}</tbody></table></div>
   <p className="text-xs text-stone-500 p-4">Deneme sayısı, öğretmenin girdiği farklı deneme adlarıdır. Ses denemelerine başarısız istekler dahildir. Karakter sayısı fatura tutarı değildir. Video sayısı tarayıcının bildirdiği tamamlanan dışa aktarımlardır.</p></section>
  <section className="bg-white border rounded-xl p-4"><h3 className="font-semibold mb-3">Son 100 soru projesi</h3><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Proje','Öğretmen','Tür','Durum','Güncelleme'].map(t=><th className="p-2" key={t}>{t}</th>)}</tr></thead><tbody>{data?.projects.map(p=><tr key={p.id} className="border-t"><td className="p-2"><button disabled={busy} className="text-[#8b1e2d] underline text-left" onClick={()=>void open(p.id)}>{p.title}</button></td><td className="p-2">{who(p.owner_id)}</td><td className="p-2">{getCategoryLabel(p.category)}</td><td className="p-2">{statuses[p.status]||p.status}</td><td className="p-2">{new Date(p.updated_at).toLocaleString('tr')}</td></tr>)}</tbody></table></div></section>
  <section className="bg-white border rounded-xl p-4"><h3 className="font-semibold mb-3">Son 100 işlem</h3><ul className="divide-y text-sm">{data?.activity.map(a=><li key={a.id} className="py-2">{who(a.owner_id)} · {a.kind==='voice'?'Ses üretimi':a.kind==='video_export'?'Video dışa aktarımı':a.kind==='member_role'?'Rol değişikliği':'Üyelik'} · {({succeeded:'Tamamlandı',requested:'İstek gönderildi',failed:'Başarısız',uncertain:'Sonuç doğrulanamadı',client_reported:'Tarayıcıda tamamlandı',admin:'Yönetici yapıldı',teacher:'Öğretmen yapıldı',...statuses} as Record<string,string>)[a.state]||a.state} <span className="text-stone-400">{new Date(a.created_at).toLocaleString('tr')}</span></li>)}</ul></section>
 </section>;
};
